In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Python environment ready.")

Python environment ready.

In [5]:
import pandas as pd
from pathlib import Path

# Project paths
DATA_DIR = Path("../Dataset")

# Load datasets
accounts = pd.read_csv(DATA_DIR / "accounts.csv")
subscriptions = pd.read_csv(DATA_DIR / "subscriptions.csv")
feature_usage = pd.read_csv(DATA_DIR / "feature_usage.csv")
support_tickets = pd.read_csv(DATA_DIR / "support_tickets.csv")
churn_events = pd.read_csv(DATA_DIR / "churn_events.csv")

datasets = {
    "accounts": accounts,
    "subscriptions": subscriptions,
    "feature_usage": feature_usage,
    "support_tickets": support_tickets,
    "churn_events": churn_events
}

# Basic exploration
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(f"{name.upper()}")
    print("=" * 60)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    print(df.head())

    print("\nData types:")
    print(df.dtypes)

    print("\nMissing values:")
    print(df.isnull().sum())

    print("\nDuplicate rows:")
    print(df.duplicated().sum())

============================================================
ACCOUNTS
============================================================

Shape:
(500, 10)

Columns:
['account_id', 'account_name', 'industry', 'country', 'signup_date', 'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag']

First 5 rows:
  account_id account_name    industry country signup_date referral_source  \
0   A-2e4581    Company_0      EdTech      US  2024-10-16         partner
1   A-43a9e3    Company_1     FinTech      IN  2023-08-17           other
2   A-0a282f    Company_2    DevTools      US  2024-08-27         organic
3   A-1f0ac7    Company_3  HealthTech      UK  2023-08-27           other
4   A-ce550d    Company_4  HealthTech      US  2024-10-27           event

    plan_tier  seats  is_trial  churn_flag
0       Basic      9     False       False
1       Basic     18     False        True
2       Basic      1     False       False
3       Basic     24      True       False
4  Enterprise     35     False        True

Data types:
account_id           str
account_name         str
industry             str
country              str
signup_date          str
referral_source      str
plan_tier            str
seats              int64
is_trial            bool
churn_flag          bool
dtype: object

Missing values:
account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

Duplicate rows:
0

============================================================
SUBSCRIPTIONS
============================================================

Shape:
(5000, 14)

Columns:
['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier', 'seats', 'mrr_amount', 'arr_amount', 'is_trial', 'upgrade_flag', 'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag']

First 5 rows:
  subscription_id account_id  start_date    end_date   plan_tier  seats  \
0        S-8cec59   A-3c1a3f  2023-12-23  2024-04-12  Enterprise     14
1        S-0f6f44   A-9b9fe9  2024-06-11         NaN         Pro     17
2        S-51c0d1   A-659280  2024-11-25         NaN  Enterprise     62
3        S-f81687   A-e7a1e2  2024-11-23  2024-12-13  Enterprise      5
4        S-cff5a2   A-ba6516  2024-01-10         NaN  Enterprise     27

   mrr_amount  arr_amount  is_trial  upgrade_flag  downgrade_flag  churn_flag  \
0        2786       33432     False         False           False        True
1         833        9996     False         False           False       False
2           0           0      True          True           False       False
3         995       11940     False         False           False        True
4        5373       64476     False         False           False       False

  billing_frequency  auto_renew_flag
0           monthly             True
1           monthly             True
2            annual            False
3           monthly             True
4           monthly             True

Data types:
subscription_id        str
account_id             str
start_date             str
end_date               str
plan_tier              str
seats                int64
mrr_amount           int64
arr_amount           int64
is_trial              bool
upgrade_flag          bool
downgrade_flag        bool
churn_flag            bool
billing_frequency      str
auto_renew_flag       bool
dtype: object

Missing values:
subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

Duplicate rows:
0

============================================================
FEATURE_USAGE
============================================================

Shape:
(25000, 8)

Columns:
['usage_id', 'subscription_id', 'usage_date', 'feature_name', 'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature']

First 5 rows:
   usage_id subscription_id  usage_date feature_name  usage_count  \
0  U-1c6c24        S-0fcf7d  2023-07-27   feature_20            9
1  U-f07cb8        S-c25263  2023-08-07    feature_5            9
2  U-096807        S-f29e7f  2023-12-07    feature_3            9
3  U-6b1580        S-be655e  2024-07-28   feature_40            5
4  U-720a29        S-f9b1d0  2024-12-02   feature_12           12

   usage_duration_secs  error_count  is_beta_feature
0                 5004            0            False
1                  369            0            False
2                 1458            0            False
3                 2085            0            False
4                  900            0            False

Data types:
usage_id                 str
subscription_id          str
usage_date               str
feature_name             str
usage_count            int64
usage_duration_secs    int64
error_count            int64
is_beta_feature         bool
dtype: object

Missing values:
usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

Duplicate rows:
0

============================================================
SUPPORT_TICKETS
============================================================

Shape:
(2000, 9)

Columns:
['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'resolution_time_hours', 'priority', 'first_response_time_minutes', 'satisfaction_score', 'escalation_flag']

First 5 rows:
  ticket_id account_id submitted_at            closed_at  \
0  T-0024de   A-712f1c   2023-07-27  2023-07-28 03:00:00
1  T-4d04b9   A-e43bf7   2024-07-08  2024-07-09 03:00:00
2  T-d5e12f   A-0f3e88   2024-10-17  2024-10-17 19:00:00
3  T-dfce9a   A-4c56c9   2024-09-08  2024-09-09 23:00:00
4  T-c59f77   A-6f8ad2   2024-11-30  2024-12-01 02:00:00

   resolution_time_hours priority  first_response_time_minutes  \
0                   27.0     high                           74
1                   27.0   urgent                          144
2                   19.0   urgent                           93
3                   47.0   medium                          126
4                   26.0   medium                            8

   satisfaction_score  escalation_flag
0                 NaN            False
1                 NaN            False
2                 4.0            False
3                 5.0            False
4                 NaN            False

Data types:
ticket_id                          str
account_id                         str
submitted_at                       str
closed_at                          str
resolution_time_hours          float64
priority                           str
first_response_time_minutes      int64
satisfaction_score             float64
escalation_flag                   bool
dtype: object

Missing values:
ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

Duplicate rows:
0

============================================================
CHURN_EVENTS
============================================================

Shape:
(600, 9)

Columns:
['churn_event_id', 'account_id', 'churn_date', 'reason_code', 'refund_amount_usd', 'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation', 'feedback_text']

First 5 rows:
  churn_event_id account_id  churn_date reason_code  refund_amount_usd  \
0       C-816288   A-c37cab  2024-10-27     pricing               4.03
1       C-5a81e7   A-37f969  2024-06-25     support              96.45
2       C-a174be   A-b07346  2024-11-12      budget               0.00
3       C-accb39   A-1e50e0  2023-11-01      budget              54.94
4       C-92f889   A-956988  2024-12-30     unknown               0.00

   preceding_upgrade_flag  preceding_downgrade_flag  is_reactivation  \
0                   False                     False            False
1                    True                     False            False
2                   False                     False            False
3                   False                     False            False
4                   False                      True             True

            feedback_text
0  switched to competitor
1                     NaN
2        missing features
3  switched to competitor
4           too expensive

Data types:
churn_event_id                  str
account_id                      str
churn_date                      str
reason_code                     str
refund_amount_usd           float64
preceding_upgrade_flag         bool
preceding_downgrade_flag       bool
is_reactivation                bool
feedback_text                   str
dtype: object

Missing values:
churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

Duplicate rows:
0

In [6]:


for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"{name.upper()} — DETAILED PROFILE")
    print("=" * 70)

    # -----------------------------
    # 1. Numerical columns
    # -----------------------------
    numerical_cols = df.select_dtypes(include="number").columns.tolist()

    print("\nNumerical Columns:")
    print(numerical_cols)

    if numerical_cols:
        print("\nNumerical Statistics:")
        display(df[numerical_cols].describe().T)


    # -----------------------------
    # 2. Categorical columns
    # -----------------------------
    categorical_cols = df.select_dtypes(
        include=["object", "category", "bool"]
    ).columns.tolist()

    print("\nCategorical Columns:")
    print(categorical_cols)

    if categorical_cols:
        print("\nCategorical Summary:")

        categorical_summary = pd.DataFrame({
            "Column": categorical_cols,
            "Unique_Values": [
                df[col].nunique(dropna=True)
                for col in categorical_cols
            ],
            "Missing_Values": [
                df[col].isna().sum()
                for col in categorical_cols
            ]
        })

        display(categorical_summary)


    # -----------------------------
    # 3. Top categorical values
    # -----------------------------
    if categorical_cols:

        print("\nTop Values by Categorical Column:")

        for col in categorical_cols:
            print(f"\n{col}:")

            display(
                df[col]
                .value_counts(dropna=False)
                .head(10)
                .to_frame("Count")
            )


    # -----------------------------
    # 4. Date-column candidates
    # -----------------------------
    date_candidates = [
        col for col in df.columns
        if any(keyword in col.lower()
               for keyword in [
                   "date", "time", "created",
                   "updated", "start", "end"
               ])
    ]

    print("\nPotential Date/Time Columns:")
    print(date_candidates)


    # -----------------------------
    # 5. Potential ID / Key columns
    # -----------------------------
    id_candidates = [
        col for col in df.columns
        if (
            col.lower().endswith("_id")
            or col.lower() == "id"
            or "uuid" in col.lower()
        )
    ]

    print("\nPotential ID / Key Columns:")
    print(id_candidates)


print("\n" + "=" * 70)
print("DETAILED PROFILING COMPLETE")
print("=" * 70)

======================================================================
ACCOUNTS — DETAILED PROFILE
======================================================================

Numerical Columns:
['seats']

Numerical Statistics:

       count   mean        std  min  25%   50%   75%    max
seats  500.0  20.56  21.044718  1.0  5.0  15.0  28.0  163.0

Categorical Columns:
['account_id', 'account_name', 'industry', 'country', 'signup_date', 'referral_source', 'plan_tier', 'is_trial', 'churn_flag']

Categorical Summary:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\186782046.py:23: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

            Column  Unique_Values  Missing_Values
0       account_id            500               0
1     account_name            500               0
2         industry              5               0
3          country              7               0
4      signup_date            370               0
5  referral_source              5               0
6        plan_tier              3               0
7         is_trial              2               0
8       churn_flag              2               0

Top Values by Categorical Column:

account_id:

            Count
account_id
A-2e4581        1
A-43a9e3        1
A-0a282f        1
A-1f0ac7        1
A-ce550d        1
A-1b9609        1
A-a0ca4e        1
A-e5d6ab        1
A-7dacce        1
A-10b8da        1

account_name:

              Count
account_name
Company_0         1
Company_1         1
Company_2         1
Company_3         1
Company_4         1
Company_5         1
Company_6         1
Company_7         1
Company_8         1
Company_9         1

industry:

               Count
industry
DevTools         113
FinTech          112
Cybersecurity    100
HealthTech        96
EdTech            79

country:

         Count
country
US         291
UK          58
IN          49
AU          32
DE          25
CA          23
FR          22

signup_date:

             Count
signup_date
2024-10-27       4
2024-10-22       4
2024-10-16       3
2023-09-08       3
2024-08-20       3
2024-05-20       3
2024-12-07       3
2024-07-06       3
2024-10-31       3
2024-03-28       3

referral_source:

                 Count
referral_source
organic            114
other              103
ads                 98
event               96
partner             89

plan_tier:

            Count
plan_tier
Pro           178
Basic         168
Enterprise    154

is_trial:

          Count
is_trial
False       403
True         97

churn_flag:

            Count
churn_flag
False         390
True          110

Potential Date/Time Columns:
['signup_date']

Potential ID / Key Columns:
['account_id']

======================================================================
SUBSCRIPTIONS — DETAILED PROFILE
======================================================================

Numerical Columns:
['seats', 'mrr_amount', 'arr_amount']

Numerical Statistics:

,count,mean,std,min,25%,50%,75%,max
seats,5000.0,29.8520,23.089771,1.0,14.0,24.0,40.0,189.0
mrr_amount,5000.0,2267.7494,3421.375348,0.0,285.0,931.0,2786.0,33830.0
arr_amount,5000.0,27212.9928,41056.504178,0.0,3420.0,11172.0,33432.0,405960.0

Categorical Columns:
['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier', 'is_trial', 'upgrade_flag', 'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag']

Categorical Summary:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\186782046.py:23: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

               Column  Unique_Values  Missing_Values
0     subscription_id           5000               0
1          account_id            500               0
2          start_date            625               0
3            end_date            208            4514
4           plan_tier              3               0
5            is_trial              2               0
6        upgrade_flag              2               0
7      downgrade_flag              2               0
8          churn_flag              2               0
9   billing_frequency              2               0
10    auto_renew_flag              2               0

Top Values by Categorical Column:

subscription_id:

                 Count
subscription_id
S-8cec59             1
S-0f6f44             1
S-51c0d1             1
S-f81687             1
S-cff5a2             1
S-4b9b13             1
S-dceac6             1
S-8cad7b             1
S-24796e             1
S-d0c344             1

account_id:

            Count
account_id
A-d4ac0e       19
A-5a92e7       19
A-592832       19
A-726cfa       19
A-5a215a       18
A-8bde0c       18
A-6f8ad2       17
A-692f18       17
A-82d8a6       17
A-417d2f       16

start_date:

            Count
start_date
2024-12-31     45
2024-12-10     45
2024-12-26     40
2024-12-21     39
2024-12-30     37
2024-12-29     37
2024-12-24     36
2024-12-20     36
2024-11-28     35
2024-12-15     35

end_date:

            Count
end_date
NaN          4514
2024-12-31     24
2024-12-29     19
2024-12-30     18
2024-12-28     10
2024-12-26      8
2024-12-18      7
2024-12-03      7
2024-12-21      7
2024-12-15      7

plan_tier:

            Count
plan_tier
Enterprise   1723
Pro          1675
Basic        1602

is_trial:

          Count
is_trial
False      4222
True        778

upgrade_flag:

              Count
upgrade_flag
False          4471
True            529

downgrade_flag:

                Count
downgrade_flag
False            4782
True              218

churn_flag:

            Count
churn_flag
False        4514
True          486

billing_frequency:

                   Count
billing_frequency
monthly             2539
annual              2461

auto_renew_flag:

                 Count
auto_renew_flag
True              4005
False              995

Potential Date/Time Columns:
['start_date', 'end_date']

Potential ID / Key Columns:
['subscription_id', 'account_id']

======================================================================
FEATURE_USAGE — DETAILED PROFILE
======================================================================

Numerical Columns:
['usage_count', 'usage_duration_secs', 'error_count']

Numerical Statistics:

,count,mean,std,min,25%,50%,75%,max
usage_count,25000.0,10.02100,3.143729,0.0,8.0,10.0,12.0,26.0
usage_duration_secs,25000.0,3042.20288,2056.544615,0.0,1350.0,2760.0,4400.0,12696.0
error_count,25000.0,0.56428,1.012595,0.0,0.0,0.0,1.0,8.0

Categorical Columns:
['usage_id', 'subscription_id', 'usage_date', 'feature_name', 'is_beta_feature']

Categorical Summary:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\186782046.py:23: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

            Column  Unique_Values  Missing_Values
0         usage_id          24979               0
1  subscription_id           4967               0
2       usage_date            731               0
3     feature_name             40               0
4  is_beta_feature              2               0

Top Values by Categorical Column:

usage_id:

          Count
usage_id
U-25b56c      2
U-662254      2
U-c878da      2
U-f42b0a      2
U-8128da      2
U-48a4aa      2
U-7a87ed      2
U-6970d1      2
U-d20c6d      2
U-ae1a6c      2

subscription_id:

                 Count
subscription_id
S-0896f4            16
S-52385a            14
S-115823            14
S-02b754            14
S-e7e4bd            13
S-66bae1            13
S-dd220e            13
S-196c1e            13
S-4f7b91            13
S-e63c67            13

usage_date:

            Count
usage_date
2024-10-11     53
2023-04-18     50
2024-07-11     50
2023-03-07     49
2023-02-26     49
2024-06-09     48
2024-07-10     48
2023-01-08     48
2023-03-02     47
2024-10-23     47

feature_name:

              Count
feature_name
feature_12      659
feature_32      659
feature_6       655
feature_17      651
feature_34      650
feature_26      649
feature_36      648
feature_31      644
feature_20      643
feature_24      643

is_beta_feature:

                 Count
is_beta_feature
False            22456
True              2544

Potential Date/Time Columns:
['usage_date']

Potential ID / Key Columns:
['usage_id', 'subscription_id']

======================================================================
SUPPORT_TICKETS — DETAILED PROFILE
======================================================================

Numerical Columns:
['resolution_time_hours', 'first_response_time_minutes', 'satisfaction_score']

Numerical Statistics:

,count,mean,std,min,25%,50%,75%,max
resolution_time_hours,2000.0,35.861000,21.138427,1.0,17.0,35.0,54.0,72.0
first_response_time_minutes,2000.0,88.480000,51.531877,1.0,43.0,88.0,131.0,180.0
satisfaction_score,1175.0,3.981277,0.809646,3.0,3.0,4.0,5.0,5.0

Categorical Columns:
['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'priority', 'escalation_flag']

Categorical Summary:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\186782046.py:23: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

            Column  Unique_Values  Missing_Values
0        ticket_id           2000               0
1       account_id            492               0
2     submitted_at            671               0
3        closed_at           1893               0
4         priority              4               0
5  escalation_flag              2               0

Top Values by Categorical Column:

ticket_id:

           Count
ticket_id
T-0024de       1
T-4d04b9       1
T-d5e12f       1
T-dfce9a       1
T-c59f77       1
T-90f06d       1
T-30b537       1
T-60242d       1
T-7119c9       1
T-b0edf2       1

account_id:

            Count
account_id
A-bb3bd4       11
A-3ce5b8       10
A-e98302        9
A-503d5a        9
A-139c3b        9
A-ed510f        9
A-c42f1f        9
A-86902e        9
A-dcc3f1        9
A-fd7ad3        8

submitted_at:

              Count
submitted_at
2024-12-01       10
2024-10-29        9
2024-05-14        8
2024-04-27        8
2023-03-24        8
2024-11-03        8
2023-01-27        8
2023-03-30        8
2023-09-24        8
2024-09-08        7

closed_at:

                     Count
closed_at
2024-04-28 03:00:00      3
2024-03-01 17:00:00      3
2023-12-21 18:00:00      2
2024-02-10 18:00:00      2
2024-08-05 08:00:00      2
2023-09-17 18:00:00      2
2023-08-08 09:00:00      2
2023-07-23 05:00:00      2
2024-07-18 03:00:00      2
2024-05-30 17:00:00      2

priority:

          Count
priority
urgent      514
high        510
medium      491
low         485

escalation_flag:

                 Count
escalation_flag
False             1905
True                95

Potential Date/Time Columns:
['resolution_time_hours', 'first_response_time_minutes']

Potential ID / Key Columns:
['ticket_id', 'account_id']

======================================================================
CHURN_EVENTS — DETAILED PROFILE
======================================================================

Numerical Columns:
['refund_amount_usd']

Numerical Statistics:

                   count       mean        std  min  25%  50%  75%     max
refund_amount_usd  600.0  14.420417  39.224591  0.0  0.0  0.0  0.0  392.92

Categorical Columns:
['churn_event_id', 'account_id', 'churn_date', 'reason_code', 'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation', 'feedback_text']

Categorical Summary:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\186782046.py:23: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

                     Column  Unique_Values  Missing_Values
0            churn_event_id            600               0
1                account_id            352               0
2                churn_date            311               0
3               reason_code              6               0
4    preceding_upgrade_flag              2               0
5  preceding_downgrade_flag              2               0
6           is_reactivation              2               0
7             feedback_text              3             148

Top Values by Categorical Column:

churn_event_id:

                Count
churn_event_id
C-816288            1
C-5a81e7            1
C-a174be            1
C-accb39            1
C-92f889            1
C-a8ac26            1
C-2e2966            1
C-ee531b            1
C-e6a0f0            1
C-9328ba            1

account_id:

            Count
account_id
A-0a62f5        5
A-180abf        5
A-37f969        4
A-0baac2        4
A-9208f0        4
A-425e76        4
A-533452        4
A-68f37c        4
A-0cc442        4
A-ee42db        4

churn_date:

            Count
churn_date
2024-12-29      7
2024-12-19      7
2024-12-30      6
2024-11-13      6
2024-12-16      6
2024-12-25      6
2024-12-17      6
2024-12-09      6
2024-08-11      5
2024-06-17      5

reason_code:

             Count
reason_code
features       114
support        104
budget         104
unknown         95
competitor      92
pricing         91

preceding_upgrade_flag:

                        Count
preceding_upgrade_flag
False                     477
True                      123

preceding_downgrade_flag:

                          Count
preceding_downgrade_flag
False                       547
True                         53

is_reactivation:

                 Count
is_reactivation
False              539
True                61

feedback_text:

                        Count
feedback_text
too expensive             161
missing features          155
NaN                       148
switched to competitor    136

Potential Date/Time Columns:
['churn_date']

Potential ID / Key Columns:
['churn_event_id', 'account_id']

======================================================================
DETAILED PROFILING COMPLETE
======================================================================

In [7]:


print("=" * 70)
print("DATE/TIME DETECTION & CONVERSION")
print("=" * 70)

date_conversion_report = []

for name, df in datasets.items():

    print(f"\n--- {name.upper()} ---")

    for col in df.columns:

        # Only inspect object/string columns
        if df[col].dtype == "object":

            # Try converting the column to datetime
            converted = pd.to_datetime(
                df[col],
                errors="coerce"
            )

            # Calculate how many non-null values were successfully converted
            original_non_null = df[col].notna().sum()

            if original_non_null > 0:
                conversion_rate = (
                    converted.notna().sum() / original_non_null
                ) * 100
            else:
                conversion_rate = 0

            # Convert only if most non-null values look like dates
            if conversion_rate >= 80:

                df[col] = converted

                date_conversion_report.append({
                    "Dataset": name,
                    "Column": col,
                    "Conversion_Rate_%": round(conversion_rate, 2),
                    "New_Dtype": str(df[col].dtype)
                })

                print(
                    f"✓ Converted: {col} "
                    f"({conversion_rate:.1f}% successfully parsed)"
                )


# --------------------------------------------
# Display conversion report
# --------------------------------------------

print("\n" + "=" * 70)
print("DATE CONVERSION REPORT")
print("=" * 70)

if date_conversion_report:
    date_conversion_report = pd.DataFrame(date_conversion_report)
    display(date_conversion_report)
else:
    print("No columns were automatically converted to datetime.")


# --------------------------------------------
# Verify resulting date columns
# --------------------------------------------

print("\n" + "=" * 70)
print("DATE/TIME COLUMNS AFTER CONVERSION")
print("=" * 70)

for name, df in datasets.items():

    date_cols = df.select_dtypes(
        include=["datetime", "datetimetz"]
    ).columns.tolist()

    print(f"\n{name}:")
    
    if date_cols:
        for col in date_cols:
            print(
                f"  • {col}: "
                f"{df[col].min()} → {df[col].max()}"
            )
    else:
        print("  No datetime columns found.")


print("\n" + "=" * 70)
print("DATE/TIME PREPARATION COMPLETE")
print("=" * 70)

======================================================================
DATE/TIME DETECTION & CONVERSION
======================================================================

--- ACCOUNTS ---

--- SUBSCRIPTIONS ---

--- FEATURE_USAGE ---

--- SUPPORT_TICKETS ---

--- CHURN_EVENTS ---

======================================================================
DATE CONVERSION REPORT
======================================================================
No columns were automatically converted to datetime.

======================================================================
DATE/TIME COLUMNS AFTER CONVERSION
======================================================================

accounts:
  No datetime columns found.

subscriptions:
  No datetime columns found.

feature_usage:
  No datetime columns found.

support_tickets:
  No datetime columns found.

churn_events:
  No datetime columns found.

======================================================================
DATE/TIME PREPARATION COMPLETE
======================================================================

In [8]:


print("=" * 70)
print("KEY & RELATIONSHIP VALIDATION")
print("=" * 70)


# ------------------------------------------------
# 1. Identify ID-like columns
# ------------------------------------------------

print("\n1. ID / KEY COLUMNS")
print("-" * 70)

for name, df in datasets.items():

    id_cols = [
        col for col in df.columns
        if (
            col.lower() == "id"
            or col.lower().endswith("_id")
            or "uuid" in col.lower()
        )
    ]

    print(f"\n{name.upper()}:")
    
    if id_cols:
        for col in id_cols:
            unique_count = df[col].nunique(dropna=True)
            total_count = df[col].notna().sum()

            print(
                f"  • {col}: "
                f"{unique_count:,} unique / "
                f"{total_count:,} non-null"
            )
    else:
        print("  No obvious ID columns detected.")


# ------------------------------------------------
# 2. Check uniqueness of ID columns
# ------------------------------------------------

print("\n\n2. ID UNIQUENESS CHECK")
print("-" * 70)

key_analysis = []

for name, df in datasets.items():

    id_cols = [
        col for col in df.columns
        if (
            col.lower() == "id"
            or col.lower().endswith("_id")
            or "uuid" in col.lower()
        )
    ]

    for col in id_cols:

        non_null = df[col].notna().sum()
        unique = df[col].nunique(dropna=True)

        key_analysis.append({
            "Dataset": name,
            "Column": col,
            "Rows": len(df),
            "Unique_Values": unique,
            "Non_Null": non_null,
            "Is_Unique": unique == non_null
        })

if key_analysis:
    key_analysis = pd.DataFrame(key_analysis)
    display(key_analysis)
else:
    print("No ID columns available for analysis.")


# ------------------------------------------------
# 3. Cross-dataset ID matching
# ------------------------------------------------

print("\n\n3. CROSS-DATASET ID MATCHING")
print("-" * 70)

# Expected relationships based on the SaaS dataset structure.
# We only test relationships when both columns actually exist.

possible_relationships = [
    ("accounts", "account_id", "subscriptions", "account_id"),
    ("accounts", "account_id", "feature_usage", "account_id"),
    ("accounts", "account_id", "support_tickets", "account_id"),
    ("accounts", "account_id", "churn_events", "account_id"),

    ("subscriptions", "subscription_id", "feature_usage", "subscription_id"),
    ("subscriptions", "subscription_id", "support_tickets", "subscription_id"),
    ("subscriptions", "subscription_id", "churn_events", "subscription_id")
]

relationship_results = []

for parent_table, parent_col, child_table, child_col in possible_relationships:

    if (
        parent_table in datasets
        and child_table in datasets
        and parent_col in datasets[parent_table].columns
        and child_col in datasets[child_table].columns
    ):

        parent_ids = set(
            datasets[parent_table][parent_col]
            .dropna()
            .unique()
        )

        child_ids = datasets[child_table][child_col].dropna()

        matched = child_ids.isin(parent_ids).sum()
        total = len(child_ids)

        match_rate = (
            matched / total * 100
            if total > 0 else 0
        )

        relationship_results.append({
            "Parent_Table": parent_table,
            "Parent_Key": parent_col,
            "Child_Table": child_table,
            "Child_Key": child_col,
            "Child_Records": total,
            "Matched_Records": matched,
            "Match_Rate_%": round(match_rate, 2)
        })


if relationship_results:
    relationship_results = pd.DataFrame(relationship_results)
    display(relationship_results)
else:
    print(
        "No predefined relationships could be tested "
        "using the actual column names."
    )


# ------------------------------------------------
# 4. Potential orphan records
# ------------------------------------------------

print("\n\n4. ORPHAN RECORD CHECK")
print("-" * 70)

if relationship_results is not None and len(relationship_results) > 0:

    for _, row in relationship_results.iterrows():

        if row["Match_Rate_%"] < 100:

            print(
                f"⚠ {row['Child_Table']}.{row['Child_Key']} → "
                f"{row['Parent_Table']}.{row['Parent_Key']}: "
                f"{100 - row['Match_Rate_%']:.2f}% unmatched"
            )

        else:

            print(
                f"✓ {row['Child_Table']}.{row['Child_Key']} → "
                f"{row['Parent_Table']}.{row['Parent_Key']}: "
                f"100% matched"
            )


print("\n" + "=" * 70)
print("KEY & RELATIONSHIP VALIDATION COMPLETE")
print("=" * 70)

======================================================================
KEY & RELATIONSHIP VALIDATION
======================================================================

1. ID / KEY COLUMNS
----------------------------------------------------------------------

ACCOUNTS:
  • account_id: 500 unique / 500 non-null

SUBSCRIPTIONS:
  • subscription_id: 5,000 unique / 5,000 non-null
  • account_id: 500 unique / 5,000 non-null

FEATURE_USAGE:
  • usage_id: 24,979 unique / 25,000 non-null
  • subscription_id: 4,967 unique / 25,000 non-null

SUPPORT_TICKETS:
  • ticket_id: 2,000 unique / 2,000 non-null
  • account_id: 492 unique / 2,000 non-null

CHURN_EVENTS:
  • churn_event_id: 600 unique / 600 non-null
  • account_id: 352 unique / 600 non-null


2. ID UNIQUENESS CHECK
----------------------------------------------------------------------

           Dataset           Column   Rows  Unique_Values  Non_Null  Is_Unique
0         accounts       account_id    500            500       500       True
1    subscriptions  subscription_id   5000           5000      5000       True
2    subscriptions       account_id   5000            500      5000      False
3    feature_usage         usage_id  25000          24979     25000      False
4    feature_usage  subscription_id  25000           4967     25000      False
5  support_tickets        ticket_id   2000           2000      2000       True
6  support_tickets       account_id   2000            492      2000      False
7     churn_events   churn_event_id    600            600       600       True
8     churn_events       account_id    600            352       600      False

3. CROSS-DATASET ID MATCHING
----------------------------------------------------------------------

,Parent_Table,Parent_Key,Child_Table,Child_Key,Child_Records,Matched_Records,Match_Rate_%
0,accounts,account_id,subscriptions,account_id,5000,5000,100.0
1,accounts,account_id,support_tickets,account_id,2000,2000,100.0
2,accounts,account_id,churn_events,account_id,600,600,100.0
3,subscriptions,subscription_id,feature_usage,subscription_id,25000,25000,100.0

4. ORPHAN RECORD CHECK
----------------------------------------------------------------------
✓ subscriptions.account_id → accounts.account_id: 100% matched
✓ support_tickets.account_id → accounts.account_id: 100% matched
✓ churn_events.account_id → accounts.account_id: 100% matched
✓ feature_usage.subscription_id → subscriptions.subscription_id: 100% matched

======================================================================
KEY & RELATIONSHIP VALIDATION COMPLETE
======================================================================

In [9]:

print("=" * 70)
print("DATA CLEANING & STANDARDIZATION")
print("=" * 70)

cleaning_report = []

for name, df in datasets.items():

    print(f"\n--- CLEANING: {name.upper()} ---")

    original_rows = len(df)
    original_columns = len(df.columns)

    # --------------------------------------------
    # 1. Standardize column names
    # --------------------------------------------

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )

    # --------------------------------------------
    # 2. Remove completely empty rows
    # --------------------------------------------

    empty_rows = df.isna().all(axis=1).sum()

    if empty_rows > 0:
        df.dropna(how="all", inplace=True)

    # --------------------------------------------
    # 3. Remove completely empty columns
    # --------------------------------------------

    empty_columns = df.isna().all(axis=0).sum()

    if empty_columns > 0:
        df.dropna(axis=1, how="all", inplace=True)

    # --------------------------------------------
    # 4. Standardize text fields
    # --------------------------------------------

    text_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns

    for col in text_columns:
        df[col] = df[col].str.strip()

    # --------------------------------------------
    # 5. Convert blank strings to missing values
    # --------------------------------------------

    for col in text_columns:
        df[col] = df[col].replace(
            ["", " ", "NA", "N/A", "na", "null", "NULL"],
            pd.NA
        )

    # --------------------------------------------
    # 6. Remove exact duplicate rows
    # --------------------------------------------

    duplicates_before = df.duplicated().sum()

    if duplicates_before > 0:
        df.drop_duplicates(inplace=True)

    # --------------------------------------------
    # 7. Reset index
    # --------------------------------------------

    df.reset_index(drop=True, inplace=True)

    # --------------------------------------------
    # Cleaning report
    # --------------------------------------------

    cleaning_report.append({
        "Dataset": name,
        "Original_Rows": original_rows,
        "Final_Rows": len(df),
        "Duplicate_Rows_Removed": duplicates_before,
        "Empty_Rows_Removed": empty_rows,
        "Empty_Columns_Removed": empty_columns,
        "Columns": len(df.columns)
    })

    print(
        f"Rows: {original_rows:,} → {len(df):,}"
    )

    print(
        f"Duplicate rows removed: {duplicates_before:,}"
    )

    print(
        f"Completely empty rows removed: {empty_rows:,}"
    )

    print(
        f"Completely empty columns removed: {empty_columns:,}"
    )


# ------------------------------------------------
# Cleaning summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("CLEANING SUMMARY")
print("=" * 70)

cleaning_report = pd.DataFrame(cleaning_report)

display(cleaning_report)


# ------------------------------------------------
# Verify datasets after cleaning
# ------------------------------------------------

print("\n" + "=" * 70)
print("POST-CLEANING DATASET STATUS")
print("=" * 70)

for name, df in datasets.items():

    print(
        f"{name:<20} "
        f"{df.shape[0]:>8,} rows × "
        f"{df.shape[1]:>3} columns"
    )

print("\nData cleaning and standardization complete.")

======================================================================
DATA CLEANING & STANDARDIZATION
======================================================================

--- CLEANING: ACCOUNTS ---
Rows: 500 → 500
Duplicate rows removed: 0
Completely empty rows removed: 0
Completely empty columns removed: 0

--- CLEANING: SUBSCRIPTIONS ---
Rows: 5,000 → 5,000
Duplicate rows removed: 0
Completely empty rows removed: 0
Completely empty columns removed: 0

--- CLEANING: FEATURE_USAGE ---
Rows: 25,000 → 25,000
Duplicate rows removed: 0
Completely empty rows removed: 0
Completely empty columns removed: 0

--- CLEANING: SUPPORT_TICKETS ---
Rows: 2,000 → 2,000
Duplicate rows removed: 0
Completely empty rows removed: 0
Completely empty columns removed: 0

--- CLEANING: CHURN_EVENTS ---
Rows: 600 → 600
Duplicate rows removed: 0
Completely empty rows removed: 0
Completely empty columns removed: 0

======================================================================
CLEANING SUMMARY
======================================================================

,Dataset,Original_Rows,Final_Rows,Duplicate_Rows_Removed,Empty_Rows_Removed,Empty_Columns_Removed,Columns
0,accounts,500,500,0,0,0,10
1,subscriptions,5000,5000,0,0,0,14
2,feature_usage,25000,25000,0,0,0,8
3,support_tickets,2000,2000,0,0,0,9
4,churn_events,600,600,0,0,0,9

======================================================================
POST-CLEANING DATASET STATUS
======================================================================
accounts                  500 rows ×  10 columns
subscriptions           5,000 rows ×  14 columns
feature_usage          25,000 rows ×   8 columns
support_tickets         2,000 rows ×   9 columns
churn_events              600 rows ×   9 columns

Data cleaning and standardization complete.

In [10]:


print("=" * 70)
print("BUSINESS VALIDITY & ANOMALY CHECKS")
print("=" * 70)

anomaly_report = []


# ------------------------------------------------
# 1. Negative numeric values
# ------------------------------------------------

print("\n1. NEGATIVE NUMERIC VALUES")
print("-" * 70)

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(include="number").columns

    dataset_has_negative = False

    for col in numeric_cols:

        negative_count = (df[col] < 0).sum()

        if negative_count > 0:

            dataset_has_negative = True

            anomaly_report.append({
                "Dataset": name,
                "Check": "Negative numeric values",
                "Column": col,
                "Issue_Count": negative_count,
                "Issue_%": round(
                    negative_count / len(df) * 100, 2
                )
            })

            print(
                f"⚠ {col}: {negative_count:,} negative values"
            )

    if not dataset_has_negative:
        print("✓ No negative numeric values found.")


# ------------------------------------------------
# 2. Zero values in numeric columns
# ------------------------------------------------

print("\n\n2. ZERO VALUES")
print("-" * 70)

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(include="number").columns

    for col in numeric_cols:

        zero_count = (df[col] == 0).sum()

        if zero_count > 0:

            print(
                f"{name}.{col}: "
                f"{zero_count:,} zero values "
                f"({zero_count / len(df) * 100:.2f}%)"
            )


# ------------------------------------------------
# 3. Date consistency checks
# ------------------------------------------------

print("\n\n3. DATE CONSISTENCY")
print("-" * 70)

for name, df in datasets.items():

    date_cols = df.select_dtypes(
        include=["datetime", "datetimetz"]
    ).columns.tolist()

    if not date_cols:
        continue

    print(f"\n{name.upper()}:")

    for col in date_cols:

        future_dates = (
            df[col] > pd.Timestamp.now()
        ).sum()

        null_dates = df[col].isna().sum()

        print(
            f"  {col}: "
            f"{future_dates:,} future dates, "
            f"{null_dates:,} missing dates"
        )


# ------------------------------------------------
# 4. Check common start/end date relationships
# ------------------------------------------------

print("\n\n4. START / END DATE LOGIC")
print("-" * 70)

for name, df in datasets.items():

    date_cols = df.select_dtypes(
        include=["datetime", "datetimetz"]
    ).columns.tolist()

    start_cols = [
        col for col in date_cols
        if "start" in col.lower()
    ]

    end_cols = [
        col for col in date_cols
        if "end" in col.lower()
    ]

    if start_cols and end_cols:

        for start_col in start_cols:
            for end_col in end_cols:

                comparable = df[[start_col, end_col]].dropna()

                invalid_dates = (
                    comparable[end_col] < comparable[start_col]
                ).sum()

                print(
                    f"{name}: "
                    f"{start_col} → {end_col}: "
                    f"{invalid_dates:,} invalid sequences"
                )


# ------------------------------------------------
# 5. Extreme numeric values
# ------------------------------------------------

print("\n\n5. EXTREME NUMERIC VALUES (IQR CHECK)")
print("-" * 70)

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(include="number").columns

    for col in numeric_cols:

        series = df[col].dropna()

        if len(series) < 5:
            continue

        q1 = series.quantile(0.25)
        q3 = series.quantile(0.75)
        iqr = q3 - q1

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        outlier_count = (
            (series < lower_bound) |
            (series > upper_bound)
        ).sum()

        if outlier_count > 0:

            print(
                f"{name}.{col}: "
                f"{outlier_count:,} potential outliers "
                f"({outlier_count / len(series) * 100:.2f}%)"
            )


# ------------------------------------------------
# 6. Final anomaly report
# ------------------------------------------------

print("\n" + "=" * 70)
print("ANOMALY SUMMARY")
print("=" * 70)

if anomaly_report:

    anomaly_report = pd.DataFrame(anomaly_report)

    display(anomaly_report)

else:

    print(
        "No negative-value anomalies were detected."
    )

print("\n" + "=" * 70)
print("BUSINESS VALIDITY CHECK COMPLETE")
print("=" * 70)

print(
    "\nIMPORTANT: No suspicious records were deleted "
    "based on these checks."
)

======================================================================
BUSINESS VALIDITY & ANOMALY CHECKS
======================================================================

1. NEGATIVE NUMERIC VALUES
----------------------------------------------------------------------
✓ No negative numeric values found.
✓ No negative numeric values found.
✓ No negative numeric values found.
✓ No negative numeric values found.
✓ No negative numeric values found.


2. ZERO VALUES
----------------------------------------------------------------------
subscriptions.mrr_amount: 778 zero values (15.56%)
subscriptions.arr_amount: 778 zero values (15.56%)
feature_usage.usage_count: 2 zero values (0.01%)
feature_usage.usage_duration_secs: 2 zero values (0.01%)
feature_usage.error_count: 17,269 zero values (69.08%)
churn_events.refund_amount_usd: 458 zero values (76.33%)


3. DATE CONSISTENCY
----------------------------------------------------------------------


4. START / END DATE LOGIC
----------------------------------------------------------------------


5. EXTREME NUMERIC VALUES (IQR CHECK)
----------------------------------------------------------------------
accounts.seats: 25 potential outliers (5.00%)
subscriptions.seats: 216 potential outliers (4.32%)
subscriptions.mrr_amount: 471 potential outliers (9.42%)
subscriptions.arr_amount: 471 potential outliers (9.42%)
feature_usage.usage_count: 203 potential outliers (0.81%)
feature_usage.usage_duration_secs: 145 potential outliers (0.58%)
feature_usage.error_count: 1,660 potential outliers (6.64%)
churn_events.refund_amount_usd: 142 potential outliers (23.67%)

======================================================================
ANOMALY SUMMARY
======================================================================
No negative-value anomalies were detected.

======================================================================
BUSINESS VALIDITY CHECK COMPLETE
======================================================================

IMPORTANT: No suspicious records were deleted based on these checks.

In [11]:

print("=" * 70)
print("FEATURE & COLUMN PROFILING")
print("=" * 70)

column_profile = []

for name, df in datasets.items():

    for col in df.columns:

        series = df[col]

        # Basic information
        data_type = str(series.dtype)
        missing_count = series.isna().sum()
        missing_pct = round(
            (missing_count / len(df)) * 100, 2
        )

        unique_count = series.nunique(dropna=True)

        # Identify column type
        if pd.api.types.is_numeric_dtype(series):
            column_type = "Numerical"

        elif pd.api.types.is_datetime64_any_dtype(series):
            column_type = "Date/Time"

        else:
            column_type = "Categorical/Text"

        # Example values
        sample_values = (
            series.dropna()
            .astype(str)
            .unique()[:5]
        )

        sample_values = ", ".join(sample_values)

        column_profile.append({
            "Dataset": name,
            "Column": col,
            "Data_Type": data_type,
            "Column_Type": column_type,
            "Unique_Values": unique_count,
            "Missing_Count": missing_count,
            "Missing_%": missing_pct,
            "Example_Values": sample_values
        })


# ------------------------------------------------
# Create profile dataframe
# ------------------------------------------------

column_profile = pd.DataFrame(column_profile)

print("\nComplete column profile:")
display(column_profile)


# ------------------------------------------------
# Numerical feature summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("NUMERICAL FEATURES")
print("=" * 70)

numerical_profile = column_profile[
    column_profile["Column_Type"] == "Numerical"
].copy()

display(numerical_profile)


# ------------------------------------------------
# Categorical feature summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("CATEGORICAL / TEXT FEATURES")
print("=" * 70)

categorical_profile = column_profile[
    column_profile["Column_Type"] == "Categorical/Text"
].copy()

display(categorical_profile)


# ------------------------------------------------
# Date features
# ------------------------------------------------

print("\n" + "=" * 70)
print("DATE / TIME FEATURES")
print("=" * 70)

date_profile = column_profile[
    column_profile["Column_Type"] == "Date/Time"
].copy()

if len(date_profile) > 0:
    display(date_profile)
else:
    print("No datetime columns detected.")


# ------------------------------------------------
# High-cardinality categorical fields
# ------------------------------------------------

print("\n" + "=" * 70)
print("HIGH-CARDINALITY CATEGORICAL FEATURES")
print("=" * 70)

high_cardinality = categorical_profile[
    categorical_profile["Unique_Values"] > 20
].sort_values(
    "Unique_Values",
    ascending=False
)

if len(high_cardinality) > 0:
    display(high_cardinality)
else:
    print("No high-cardinality categorical columns detected.")


print("\n" + "=" * 70)
print("FEATURE PROFILING COMPLETE")
print("=" * 70)

======================================================================
FEATURE & COLUMN PROFILING
======================================================================

Complete column profile:

,Dataset,Column,Data_Type,Column_Type,Unique_Values,Missing_Count,Missing_%,Example_Values
0,accounts,account_id,str,Categorical/Text,500,0,0.00,"A-2e4581, A-43a9e3, A-0a282f, A-1f0ac7, A-ce550d"
1,accounts,account_name,str,Categorical/Text,500,0,0.00,"Company_0, Company_1, Company_2, Company_3, Co..."
2,accounts,industry,str,Categorical/Text,5,0,0.00,"EdTech, FinTech, DevTools, HealthTech, Cyberse..."
3,accounts,country,str,Categorical/Text,7,0,0.00,"US, IN, UK, CA, DE"
4,accounts,signup_date,str,Categorical/Text,370,0,0.00,"2024-10-16, 2023-08-17, 2024-08-27, 2023-08-27..."
5,accounts,referral_source,str,Categorical/Text,5,0,0.00,"partner, other, organic, event, ads"
6,accounts,plan_tier,str,Categorical/Text,3,0,0.00,"Basic, Enterprise, Pro"
7,accounts,seats,int64,Numerical,73,0,0.00,"9, 18, 1, 24, 35"
8,accounts,is_trial,bool,Numerical,2,0,0.00,"False, True"
9,accounts,churn_flag,bool,Numerical,2,0,0.00,"False, True"
10,subscriptions,subscription_id,str,Categorical/Text,5000,0,0.00,"S-8cec59, S-0f6f44, S-51c0d1, S-f81687, S-cff5a2"
11,subscriptions,account_id,str,Categorical/Text,500,0,0.00,"A-3c1a3f, A-9b9fe9, A-659280, A-e7a1e2, A-ba6516"
12,subscriptions,start_date,str,Categorical/Text,625,0,0.00,"2023-12-23, 2024-06-11, 2024-11-25, 2024-11-23..."
13,subscriptions,end_date,str,Categorical/Text,208,4514,90.28,"2024-04-12, 2024-12-13, 2024-08-03, 2024-08-13..."
14,subscriptions,plan_tier,str,Categorical/Text,3,0,0.00,"Enterprise, Pro, Basic"
15,subscriptions,seats,int64,Numerical,123,0,0.00,"14, 17, 62, 5, 27"
16,subscriptions,mrr_amount,int64,Numerical,306,0,0.00,"2786, 833, 0, 995, 5373"
17,subscriptions,arr_amount,int64,Numerical,306,0,0.00,"33432, 9996, 0, 11940, 64476"
18,subscriptions,is_trial,bool,Numerical,2,0,0.00,"False, True"
19,subscriptions,upgrade_flag,bool,Numerical,2,0,0.00,"False, True"
20,subscriptions,downgrade_flag,bool,Numerical,2,0,0.00,"False, True"
21,subscriptions,churn_flag,bool,Numerical,2,0,0.00,"True, False"
22,subscriptions,billing_frequency,str,Categorical/Text,2,0,0.00,"monthly, annual"
23,subscriptions,auto_renew_flag,bool,Numerical,2,0,0.00,"True, False"
24,feature_usage,usage_id,str,Categorical/Text,24979,0,0.00,"U-1c6c24, U-f07cb8, U-096807, U-6b1580, U-720a29"
25,feature_usage,subscription_id,str,Categorical/Text,4967,0,0.00,"S-0fcf7d, S-c25263, S-f29e7f, S-be655e, S-f9b1d0"
26,feature_usage,usage_date,str,Categorical/Text,731,0,0.00,"2023-07-27, 2023-08-07, 2023-12-07, 2024-07-28..."
27,feature_usage,feature_name,str,Categorical/Text,40,0,0.00,"feature_20, feature_5, feature_3, feature_40, ..."
28,feature_usage,usage_count,int64,Numerical,27,0,0.00,"9, 5, 12, 11, 8"
29,feature_usage,usage_duration_secs,int64,Numerical,4168,0,0.00,"5004, 369, 1458, 2085, 900"
30,feature_usage,error_count,int64,Numerical,9,0,0.00,"0, 2, 1, 3, 4"
31,feature_usage,is_beta_feature,bool,Numerical,2,0,0.00,"False, True"
32,support_tickets,ticket_id,str,Categorical/Text,2000,0,0.00,"T-0024de, T-4d04b9, T-d5e12f, T-dfce9a, T-c59f77"
33,support_tickets,account_id,str,Categorical/Text,492,0,0.00,"A-712f1c, A-e43bf7, A-0f3e88, A-4c56c9, A-6f8ad2"
34,support_tickets,submitted_at,str,Categorical/Text,671,0,0.00,"2023-07-27, 2024-07-08, 2024-10-17, 2024-09-08..."
35,support_tickets,closed_at,str,Categorical/Text,1893,0,0.00,"2023-07-28 03:00:00, 2024-07-09 03:00:00, 2024..."
36,support_tickets,resolution_time_hours,float64,Numerical,72,0,0.00,"27.0, 19.0, 47.0, 26.0, 9.0"
37,support_tickets,priority,str,Categorical/Text,4,0,0.00,"high, urgent, medium, low"
38,support_tickets,first_response_time_minutes,int64,Numerical,180,0,0.00,"74, 144, 93, 126, 8"
39,support_tickets,satisfaction_score,float64,Numerical,3,825,41.25,"4.0, 5.0, 3.0"
40,support_tickets,escalation_flag,bool,Numerical,2,0,0.00,"False, True"
41,churn_events,churn_event_id,str,Categorical/Text,600,0,0.00,"C-816288, C-5a81e7, C-a174be, C-accb39, C-92f889"
42,churn_events,account_id,str,Categorical/Text,352,0,0.00,"A-c37cab, A-37f969, A-b07346, A-1e50e0, A-956988"
43,churn_events,churn_date,str,Categorical/Text,311,0,0.00,"2024-10-27, 2024-06-25, 2024-11-12, 2023-11-01..."
44,churn_events,reason_code,str,Categorical/Text,6,0,0.00,"pricing, support, budget, unknown, features"
45,churn_events,refund_amount_usd,float64,Numerical,142,0,0.00,"4.03, 96.45, 0.0, 54.94, 34.4"
46,churn_events,preceding_upgrade_flag,bool,Numerical,2,0,0.00,"False, True"
47,churn_events,preceding_downgrade_flag,bool,Numerical,2,0,0.00,"False, True"
48,churn_events,is_reactivation,bool,Numerical,2,0,0.00,"False, True"
49,churn_events,feedback_text,str,Categorical/Text,3,148,24.67,"switched to competitor, missing features, too ..."

======================================================================
NUMERICAL FEATURES
======================================================================

,Dataset,Column,Data_Type,Column_Type,Unique_Values,Missing_Count,Missing_%,Example_Values
7,accounts,seats,int64,Numerical,73,0,0.00,"9, 18, 1, 24, 35"
8,accounts,is_trial,bool,Numerical,2,0,0.00,"False, True"
9,accounts,churn_flag,bool,Numerical,2,0,0.00,"False, True"
15,subscriptions,seats,int64,Numerical,123,0,0.00,"14, 17, 62, 5, 27"
16,subscriptions,mrr_amount,int64,Numerical,306,0,0.00,"2786, 833, 0, 995, 5373"
17,subscriptions,arr_amount,int64,Numerical,306,0,0.00,"33432, 9996, 0, 11940, 64476"
18,subscriptions,is_trial,bool,Numerical,2,0,0.00,"False, True"
19,subscriptions,upgrade_flag,bool,Numerical,2,0,0.00,"False, True"
20,subscriptions,downgrade_flag,bool,Numerical,2,0,0.00,"False, True"
21,subscriptions,churn_flag,bool,Numerical,2,0,0.00,"True, False"
23,subscriptions,auto_renew_flag,bool,Numerical,2,0,0.00,"True, False"
28,feature_usage,usage_count,int64,Numerical,27,0,0.00,"9, 5, 12, 11, 8"
29,feature_usage,usage_duration_secs,int64,Numerical,4168,0,0.00,"5004, 369, 1458, 2085, 900"
30,feature_usage,error_count,int64,Numerical,9,0,0.00,"0, 2, 1, 3, 4"
31,feature_usage,is_beta_feature,bool,Numerical,2,0,0.00,"False, True"
36,support_tickets,resolution_time_hours,float64,Numerical,72,0,0.00,"27.0, 19.0, 47.0, 26.0, 9.0"
38,support_tickets,first_response_time_minutes,int64,Numerical,180,0,0.00,"74, 144, 93, 126, 8"
39,support_tickets,satisfaction_score,float64,Numerical,3,825,41.25,"4.0, 5.0, 3.0"
40,support_tickets,escalation_flag,bool,Numerical,2,0,0.00,"False, True"
45,churn_events,refund_amount_usd,float64,Numerical,142,0,0.00,"4.03, 96.45, 0.0, 54.94, 34.4"
46,churn_events,preceding_upgrade_flag,bool,Numerical,2,0,0.00,"False, True"
47,churn_events,preceding_downgrade_flag,bool,Numerical,2,0,0.00,"False, True"
48,churn_events,is_reactivation,bool,Numerical,2,0,0.00,"False, True"

======================================================================
CATEGORICAL / TEXT FEATURES
======================================================================

,Dataset,Column,Data_Type,Column_Type,Unique_Values,Missing_Count,Missing_%,Example_Values
0,accounts,account_id,str,Categorical/Text,500,0,0.00,"A-2e4581, A-43a9e3, A-0a282f, A-1f0ac7, A-ce550d"
1,accounts,account_name,str,Categorical/Text,500,0,0.00,"Company_0, Company_1, Company_2, Company_3, Co..."
2,accounts,industry,str,Categorical/Text,5,0,0.00,"EdTech, FinTech, DevTools, HealthTech, Cyberse..."
3,accounts,country,str,Categorical/Text,7,0,0.00,"US, IN, UK, CA, DE"
4,accounts,signup_date,str,Categorical/Text,370,0,0.00,"2024-10-16, 2023-08-17, 2024-08-27, 2023-08-27..."
5,accounts,referral_source,str,Categorical/Text,5,0,0.00,"partner, other, organic, event, ads"
6,accounts,plan_tier,str,Categorical/Text,3,0,0.00,"Basic, Enterprise, Pro"
10,subscriptions,subscription_id,str,Categorical/Text,5000,0,0.00,"S-8cec59, S-0f6f44, S-51c0d1, S-f81687, S-cff5a2"
11,subscriptions,account_id,str,Categorical/Text,500,0,0.00,"A-3c1a3f, A-9b9fe9, A-659280, A-e7a1e2, A-ba6516"
12,subscriptions,start_date,str,Categorical/Text,625,0,0.00,"2023-12-23, 2024-06-11, 2024-11-25, 2024-11-23..."
13,subscriptions,end_date,str,Categorical/Text,208,4514,90.28,"2024-04-12, 2024-12-13, 2024-08-03, 2024-08-13..."
14,subscriptions,plan_tier,str,Categorical/Text,3,0,0.00,"Enterprise, Pro, Basic"
22,subscriptions,billing_frequency,str,Categorical/Text,2,0,0.00,"monthly, annual"
24,feature_usage,usage_id,str,Categorical/Text,24979,0,0.00,"U-1c6c24, U-f07cb8, U-096807, U-6b1580, U-720a29"
25,feature_usage,subscription_id,str,Categorical/Text,4967,0,0.00,"S-0fcf7d, S-c25263, S-f29e7f, S-be655e, S-f9b1d0"
26,feature_usage,usage_date,str,Categorical/Text,731,0,0.00,"2023-07-27, 2023-08-07, 2023-12-07, 2024-07-28..."
27,feature_usage,feature_name,str,Categorical/Text,40,0,0.00,"feature_20, feature_5, feature_3, feature_40, ..."
32,support_tickets,ticket_id,str,Categorical/Text,2000,0,0.00,"T-0024de, T-4d04b9, T-d5e12f, T-dfce9a, T-c59f77"
33,support_tickets,account_id,str,Categorical/Text,492,0,0.00,"A-712f1c, A-e43bf7, A-0f3e88, A-4c56c9, A-6f8ad2"
34,support_tickets,submitted_at,str,Categorical/Text,671,0,0.00,"2023-07-27, 2024-07-08, 2024-10-17, 2024-09-08..."
35,support_tickets,closed_at,str,Categorical/Text,1893,0,0.00,"2023-07-28 03:00:00, 2024-07-09 03:00:00, 2024..."
37,support_tickets,priority,str,Categorical/Text,4,0,0.00,"high, urgent, medium, low"
41,churn_events,churn_event_id,str,Categorical/Text,600,0,0.00,"C-816288, C-5a81e7, C-a174be, C-accb39, C-92f889"
42,churn_events,account_id,str,Categorical/Text,352,0,0.00,"A-c37cab, A-37f969, A-b07346, A-1e50e0, A-956988"
43,churn_events,churn_date,str,Categorical/Text,311,0,0.00,"2024-10-27, 2024-06-25, 2024-11-12, 2023-11-01..."
44,churn_events,reason_code,str,Categorical/Text,6,0,0.00,"pricing, support, budget, unknown, features"
49,churn_events,feedback_text,str,Categorical/Text,3,148,24.67,"switched to competitor, missing features, too ..."

======================================================================
DATE / TIME FEATURES
======================================================================
No datetime columns detected.

======================================================================
HIGH-CARDINALITY CATEGORICAL FEATURES
======================================================================

,Dataset,Column,Data_Type,Column_Type,Unique_Values,Missing_Count,Missing_%,Example_Values
24,feature_usage,usage_id,str,Categorical/Text,24979,0,0.00,"U-1c6c24, U-f07cb8, U-096807, U-6b1580, U-720a29"
10,subscriptions,subscription_id,str,Categorical/Text,5000,0,0.00,"S-8cec59, S-0f6f44, S-51c0d1, S-f81687, S-cff5a2"
25,feature_usage,subscription_id,str,Categorical/Text,4967,0,0.00,"S-0fcf7d, S-c25263, S-f29e7f, S-be655e, S-f9b1d0"
32,support_tickets,ticket_id,str,Categorical/Text,2000,0,0.00,"T-0024de, T-4d04b9, T-d5e12f, T-dfce9a, T-c59f77"
35,support_tickets,closed_at,str,Categorical/Text,1893,0,0.00,"2023-07-28 03:00:00, 2024-07-09 03:00:00, 2024..."
26,feature_usage,usage_date,str,Categorical/Text,731,0,0.00,"2023-07-27, 2023-08-07, 2023-12-07, 2024-07-28..."
34,support_tickets,submitted_at,str,Categorical/Text,671,0,0.00,"2023-07-27, 2024-07-08, 2024-10-17, 2024-09-08..."
12,subscriptions,start_date,str,Categorical/Text,625,0,0.00,"2023-12-23, 2024-06-11, 2024-11-25, 2024-11-23..."
41,churn_events,churn_event_id,str,Categorical/Text,600,0,0.00,"C-816288, C-5a81e7, C-a174be, C-accb39, C-92f889"
0,accounts,account_id,str,Categorical/Text,500,0,0.00,"A-2e4581, A-43a9e3, A-0a282f, A-1f0ac7, A-ce550d"
1,accounts,account_name,str,Categorical/Text,500,0,0.00,"Company_0, Company_1, Company_2, Company_3, Co..."
11,subscriptions,account_id,str,Categorical/Text,500,0,0.00,"A-3c1a3f, A-9b9fe9, A-659280, A-e7a1e2, A-ba6516"
33,support_tickets,account_id,str,Categorical/Text,492,0,0.00,"A-712f1c, A-e43bf7, A-0f3e88, A-4c56c9, A-6f8ad2"
4,accounts,signup_date,str,Categorical/Text,370,0,0.00,"2024-10-16, 2023-08-17, 2024-08-27, 2023-08-27..."
42,churn_events,account_id,str,Categorical/Text,352,0,0.00,"A-c37cab, A-37f969, A-b07346, A-1e50e0, A-956988"
43,churn_events,churn_date,str,Categorical/Text,311,0,0.00,"2024-10-27, 2024-06-25, 2024-11-12, 2023-11-01..."
13,subscriptions,end_date,str,Categorical/Text,208,4514,90.28,"2024-04-12, 2024-12-13, 2024-08-03, 2024-08-13..."
27,feature_usage,feature_name,str,Categorical/Text,40,0,0.00,"feature_20, feature_5, feature_3, feature_40, ..."

======================================================================
FEATURE PROFILING COMPLETE
======================================================================

In [12]:

accounts_df = datasets["accounts"].copy()

print("=" * 70)
print("ACCOUNT / CUSTOMER ANALYSIS")
print("=" * 70)


# ------------------------------------------------
# 1. Dataset overview
# ------------------------------------------------

print("\n1. ACCOUNT OVERVIEW")
print("-" * 70)

print(f"Total account records : {len(accounts_df):,}")

# Find likely account ID
account_id_candidates = [
    col for col in accounts_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if account_id_candidates:
    account_id_col = account_id_candidates[0]
    print(f"Account ID column     : {account_id_col}")
    print(
        f"Unique accounts       : "
        f"{accounts_df[account_id_col].nunique():,}"
    )
else:
    account_id_col = None
    print("Account ID column not automatically identified.")


# ------------------------------------------------
# 2. Customer segmentation
# ------------------------------------------------

print("\n2. CUSTOMER SEGMENTATION")
print("-" * 70)

categorical_cols = accounts_df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

if categorical_cols:

    for col in categorical_cols:

        # Avoid displaying extremely high-cardinality fields
        unique_count = accounts_df[col].nunique(dropna=True)

        if unique_count <= 20:

            print(f"\n{col}:")

            summary = (
                accounts_df[col]
                .value_counts(dropna=False)
                .to_frame("Account_Count")
            )

            summary["Percentage"] = (
                summary["Account_Count"]
                / len(accounts_df)
                * 100
            ).round(2)

            display(summary)

else:
    print("No categorical account fields found.")


# ------------------------------------------------
# 3. Numerical account characteristics
# ------------------------------------------------

print("\n3. NUMERICAL ACCOUNT CHARACTERISTICS")
print("-" * 70)

numeric_cols = accounts_df.select_dtypes(
    include="number"
).columns.tolist()

if numeric_cols:

    account_numeric_summary = (
        accounts_df[numeric_cols]
        .describe()
        .T
    )

    display(account_numeric_summary)

else:
    print("No numerical account fields found.")


# ------------------------------------------------
# 4. Account-level missing data
# ------------------------------------------------

print("\n4. ACCOUNT DATA QUALITY")
print("-" * 70)

account_quality = pd.DataFrame({
    "Missing_Count": accounts_df.isna().sum(),
    "Missing_%": (
        accounts_df.isna().sum()
        / len(accounts_df)
        * 100
    ).round(2),
    "Unique_Values": accounts_df.nunique(dropna=True)
})

account_quality = account_quality.sort_values(
    "Missing_Count",
    ascending=False
)

display(account_quality)


# ------------------------------------------------
# 5. Account date coverage
# ------------------------------------------------

print("\n5. ACCOUNT DATE COVERAGE")
print("-" * 70)

date_cols = accounts_df.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.tolist()

if date_cols:

    for col in date_cols:

        print(
            f"{col}: "
            f"{accounts_df[col].min()} → "
            f"{accounts_df[col].max()}"
        )

else:
    print("No account-level datetime columns detected.")


print("\n" + "=" * 70)
print("ACCOUNT / CUSTOMER ANALYSIS COMPLETE")
print("=" * 70)

======================================================================
ACCOUNT / CUSTOMER ANALYSIS
======================================================================

1. ACCOUNT OVERVIEW
----------------------------------------------------------------------
Total account records : 500
Account ID column     : account_id
Unique accounts       : 500

2. CUSTOMER SEGMENTATION
----------------------------------------------------------------------

industry:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\657715747.py:42: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = accounts_df.select_dtypes(

               Account_Count  Percentage
industry
DevTools                 113        22.6
FinTech                  112        22.4
Cybersecurity            100        20.0
HealthTech                96        19.2
EdTech                    79        15.8

country:

         Account_Count  Percentage
country
US                 291        58.2
UK                  58        11.6
IN                  49         9.8
AU                  32         6.4
DE                  25         5.0
CA                  23         4.6
FR                  22         4.4

referral_source:

                 Account_Count  Percentage
referral_source
organic                    114        22.8
other                      103        20.6
ads                         98        19.6
event                       96        19.2
partner                     89        17.8

plan_tier:

            Account_Count  Percentage
plan_tier
Pro                   178        35.6
Basic                 168        33.6
Enterprise            154        30.8

is_trial:

          Account_Count  Percentage
is_trial
False               403        80.6
True                 97        19.4

churn_flag:

            Account_Count  Percentage
churn_flag
False                 390        78.0
True                  110        22.0

3. NUMERICAL ACCOUNT CHARACTERISTICS
----------------------------------------------------------------------

       count   mean        std  min  25%   50%   75%    max
seats  500.0  20.56  21.044718  1.0  5.0  15.0  28.0  163.0

4. ACCOUNT DATA QUALITY
----------------------------------------------------------------------

                 Missing_Count  Missing_%  Unique_Values
account_id                   0        0.0            500
account_name                 0        0.0            500
industry                     0        0.0              5
country                      0        0.0              7
signup_date                  0        0.0            370
referral_source              0        0.0              5
plan_tier                    0        0.0              3
seats                        0        0.0             73
is_trial                     0        0.0              2
churn_flag                   0        0.0              2

5. ACCOUNT DATE COVERAGE
----------------------------------------------------------------------
No account-level datetime columns detected.

======================================================================
ACCOUNT / CUSTOMER ANALYSIS COMPLETE
======================================================================

In [13]:


subscriptions_df = datasets["subscriptions"].copy()

print("=" * 70)
print("SUBSCRIPTION & REVENUE ANALYSIS")
print("=" * 70)


# ------------------------------------------------
# 1. Subscription overview
# ------------------------------------------------

print("\n1. SUBSCRIPTION OVERVIEW")
print("-" * 70)

print(f"Total subscription records : {len(subscriptions_df):,}")

subscription_id_candidates = [
    col for col in subscriptions_df.columns
    if "subscription" in col.lower() and "id" in col.lower()
]

if subscription_id_candidates:
    subscription_id_col = subscription_id_candidates[0]

    print(f"Subscription ID            : {subscription_id_col}")
    print(
        f"Unique subscriptions       : "
        f"{subscriptions_df[subscription_id_col].nunique():,}"
    )
else:
    subscription_id_col = None
    print("Subscription ID not automatically identified.")


# ------------------------------------------------
# 2. Numerical subscription metrics
# ------------------------------------------------

print("\n2. REVENUE / NUMERICAL METRICS")
print("-" * 70)

numeric_cols = subscriptions_df.select_dtypes(
    include="number"
).columns.tolist()

if numeric_cols:

    revenue_summary = pd.DataFrame({
        "Mean": subscriptions_df[numeric_cols].mean(),
        "Median": subscriptions_df[numeric_cols].median(),
        "Min": subscriptions_df[numeric_cols].min(),
        "Max": subscriptions_df[numeric_cols].max(),
        "Missing": subscriptions_df[numeric_cols].isna().sum()
    })

    display(revenue_summary)

else:
    print("No numerical columns found.")


# ------------------------------------------------
# 3. Identify revenue-related columns
# ------------------------------------------------

print("\n3. REVENUE-RELATED COLUMNS")
print("-" * 70)

revenue_keywords = [
    "mrr",
    "arr",
    "revenue",
    "price",
    "amount",
    "cost",
    "value"
]

revenue_cols = [
    col for col in subscriptions_df.columns
    if any(keyword in col.lower() for keyword in revenue_keywords)
]

print(revenue_cols)


# ------------------------------------------------
# 4. Revenue distribution
# ------------------------------------------------

if revenue_cols:

    print("\n4. REVENUE DISTRIBUTION")
    print("-" * 70)

    for col in revenue_cols:

        if pd.api.types.is_numeric_dtype(
            subscriptions_df[col]
        ):

            print(f"\n{col}:")

            print(
                f"Total   : {subscriptions_df[col].sum():,.2f}"
            )

            print(
                f"Average : {subscriptions_df[col].mean():,.2f}"
            )

            print(
                f"Median  : {subscriptions_df[col].median():,.2f}"
            )

            print(
                f"Min     : {subscriptions_df[col].min():,.2f}"
            )

            print(
                f"Max     : {subscriptions_df[col].max():,.2f}"
            )


# ------------------------------------------------
# 5. Subscription categorical fields
# ------------------------------------------------

print("\n\n5. SUBSCRIPTION SEGMENTATION")
print("-" * 70)

categorical_cols = subscriptions_df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

for col in categorical_cols:

    unique_count = subscriptions_df[col].nunique(
        dropna=True
    )

    if unique_count <= 20:

        print(f"\n{col}:")

        summary = (
            subscriptions_df[col]
            .value_counts(dropna=False)
            .to_frame("Subscription_Count")
        )

        summary["Percentage"] = (
            summary["Subscription_Count"]
            / len(subscriptions_df)
            * 100
        ).round(2)

        display(summary)


# ------------------------------------------------
# 6. Subscription date coverage
# ------------------------------------------------

print("\n6. SUBSCRIPTION DATE COVERAGE")
print("-" * 70)

date_cols = subscriptions_df.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.tolist()

if date_cols:

    for col in date_cols:

        print(
            f"{col}: "
            f"{subscriptions_df[col].min()} → "
            f"{subscriptions_df[col].max()}"
        )

else:
    print("No datetime columns detected.")


# ------------------------------------------------
# 7. Subscription data quality
# ------------------------------------------------

print("\n7. SUBSCRIPTION DATA QUALITY")
print("-" * 70)

quality = pd.DataFrame({
    "Missing_Count": subscriptions_df.isna().sum(),
    "Missing_%": (
        subscriptions_df.isna().sum()
        / len(subscriptions_df)
        * 100
    ).round(2),
    "Unique_Values": subscriptions_df.nunique(
        dropna=True
    )
})

display(
    quality.sort_values(
        "Missing_Count",
        ascending=False
    )
)


print("\n" + "=" * 70)
print("SUBSCRIPTION & REVENUE ANALYSIS COMPLETE")
print("=" * 70)

======================================================================
SUBSCRIPTION & REVENUE ANALYSIS
======================================================================

1. SUBSCRIPTION OVERVIEW
----------------------------------------------------------------------
Total subscription records : 5,000
Subscription ID            : subscription_id
Unique subscriptions       : 5,000

2. REVENUE / NUMERICAL METRICS
----------------------------------------------------------------------

                  Mean   Median  Min     Max  Missing
seats          29.8520     24.0    1     189        0
mrr_amount   2267.7494    931.0    0   33830        0
arr_amount  27212.9928  11172.0    0  405960        0

3. REVENUE-RELATED COLUMNS
----------------------------------------------------------------------
['mrr_amount', 'arr_amount']

4. REVENUE DISTRIBUTION
----------------------------------------------------------------------

mrr_amount:
Total   : 11,338,747.00
Average : 2,267.75
Median  : 931.00
Min     : 0.00
Max     : 33,830.00

arr_amount:
Total   : 136,064,964.00
Average : 27,212.99
Median  : 11,172.00
Min     : 0.00
Max     : 405,960.00


5. SUBSCRIPTION SEGMENTATION
----------------------------------------------------------------------

plan_tier:

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\3568312690.py:132: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = subscriptions_df.select_dtypes(

            Subscription_Count  Percentage
plan_tier
Enterprise                1723       34.46
Pro                       1675       33.50
Basic                     1602       32.04

is_trial:

          Subscription_Count  Percentage
is_trial
False                   4222       84.44
True                     778       15.56

upgrade_flag:

              Subscription_Count  Percentage
upgrade_flag
False                       4471       89.42
True                         529       10.58

downgrade_flag:

                Subscription_Count  Percentage
downgrade_flag
False                         4782       95.64
True                           218        4.36

churn_flag:

            Subscription_Count  Percentage
churn_flag
False                     4514       90.28
True                       486        9.72

billing_frequency:

                   Subscription_Count  Percentage
billing_frequency
monthly                          2539       50.78
annual                           2461       49.22

auto_renew_flag:

                 Subscription_Count  Percentage
auto_renew_flag
True                           4005        80.1
False                           995        19.9

6. SUBSCRIPTION DATE COVERAGE
----------------------------------------------------------------------
No datetime columns detected.

7. SUBSCRIPTION DATA QUALITY
----------------------------------------------------------------------

                   Missing_Count  Missing_%  Unique_Values
end_date                    4514      90.28            208
subscription_id                0       0.00           5000
account_id                     0       0.00            500
start_date                     0       0.00            625
plan_tier                      0       0.00              3
seats                          0       0.00            123
mrr_amount                     0       0.00            306
arr_amount                     0       0.00            306
is_trial                       0       0.00              2
upgrade_flag                   0       0.00              2
downgrade_flag                 0       0.00              2
churn_flag                     0       0.00              2
billing_frequency              0       0.00              2
auto_renew_flag                0       0.00              2

======================================================================
SUBSCRIPTION & REVENUE ANALYSIS COMPLETE
======================================================================

In [14]:


feature_usage_df = datasets["feature_usage"].copy()

print("=" * 70)
print("PRODUCT / FEATURE USAGE ANALYSIS")
print("=" * 70)


# ------------------------------------------------
# 1. Usage dataset overview
# ------------------------------------------------

print("\n1. USAGE OVERVIEW")
print("-" * 70)

print(f"Total usage records : {len(feature_usage_df):,}")

print("\nColumns:")
print(feature_usage_df.columns.tolist())


# ------------------------------------------------
# 2. Numerical usage metrics
# ------------------------------------------------

print("\n2. NUMERICAL USAGE METRICS")
print("-" * 70)

numeric_cols = feature_usage_df.select_dtypes(
    include="number"
).columns.tolist()

if numeric_cols:

    usage_numeric_summary = pd.DataFrame({
        "Mean": feature_usage_df[numeric_cols].mean(),
        "Median": feature_usage_df[numeric_cols].median(),
        "Min": feature_usage_df[numeric_cols].min(),
        "Max": feature_usage_df[numeric_cols].max(),
        "Missing": feature_usage_df[numeric_cols].isna().sum()
    })

    display(usage_numeric_summary)

else:
    print("No numerical usage columns found.")


# ------------------------------------------------
# 3. Feature / product identification
# ------------------------------------------------

print("\n3. FEATURE / PRODUCT FIELDS")
print("-" * 70)

categorical_cols = feature_usage_df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

for col in categorical_cols:

    unique_count = feature_usage_df[col].nunique(
        dropna=True
    )

    print(
        f"{col}: {unique_count:,} unique values"
    )

    # Display manageable categorical fields
    if unique_count <= 30:

        display(
            feature_usage_df[col]
            .value_counts(dropna=False)
            .head(30)
            .to_frame("Usage_Records")
        )


# ------------------------------------------------
# 4. Identify usage-related numeric fields
# ------------------------------------------------

print("\n4. USAGE-RELATED NUMERIC FIELDS")
print("-" * 70)

usage_keywords = [
    "usage",
    "count",
    "frequency",
    "minutes",
    "sessions",
    "events",
    "actions",
    "logins",
    "activity",
    "duration"
]

usage_metric_cols = [
    col for col in numeric_cols
    if any(
        keyword in col.lower()
        for keyword in usage_keywords
    )
]

print(usage_metric_cols)


# ------------------------------------------------
# 5. Usage by feature
# ------------------------------------------------

if usage_metric_cols:

    print("\n5. USAGE BY FEATURE")
    print("-" * 70)

    feature_cols = [
        col for col in categorical_cols
        if any(
            keyword in col.lower()
            for keyword in [
                "feature",
                "product",
                "module",
                "action",
                "event",
                "type"
            ]
        )
    ]

    if feature_cols:

        for feature_col in feature_cols:

            print(f"\n--- {feature_col} ---")

            for metric_col in usage_metric_cols:

                feature_summary = (
                    feature_usage_df
                    .groupby(feature_col)[metric_col]
                    .agg(
                        ["count", "sum", "mean", "median"]
                    )
                    .sort_values(
                        "sum",
                        ascending=False
                    )
                )

                print(f"\nMetric: {metric_col}")

                display(feature_summary.head(20))

    else:
        print(
            "No obvious feature/product column "
            "identified."
        )


# ------------------------------------------------
# 6. Date-based usage coverage
# ------------------------------------------------

print("\n6. USAGE DATE COVERAGE")
print("-" * 70)

date_cols = feature_usage_df.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.tolist()

if date_cols:

    for col in date_cols:

        print(
            f"{col}: "
            f"{feature_usage_df[col].min()} → "
            f"{feature_usage_df[col].max()}"
        )

else:
    print("No datetime columns detected.")


# ------------------------------------------------
# 7. Usage data quality
# ------------------------------------------------

print("\n7. USAGE DATA QUALITY")
print("-" * 70)

usage_quality = pd.DataFrame({
    "Missing_Count": feature_usage_df.isna().sum(),
    "Missing_%": (
        feature_usage_df.isna().sum()
        / len(feature_usage_df)
        * 100
    ).round(2),
    "Unique_Values": feature_usage_df.nunique(
        dropna=True
    )
})

display(
    usage_quality.sort_values(
        "Missing_Count",
        ascending=False
    )
)


print("\n" + "=" * 70)
print("PRODUCT / FEATURE USAGE ANALYSIS COMPLETE")
print("=" * 70)

======================================================================
PRODUCT / FEATURE USAGE ANALYSIS
======================================================================

1. USAGE OVERVIEW
----------------------------------------------------------------------
Total usage records : 25,000

Columns:
['usage_id', 'subscription_id', 'usage_date', 'feature_name', 'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature']

2. NUMERICAL USAGE METRICS
----------------------------------------------------------------------

                           Mean  Median  Min    Max  Missing
usage_count            10.02100    10.0    0     26        0
usage_duration_secs  3042.20288  2760.0    0  12696        0
error_count             0.56428     0.0    0      8        0

3. FEATURE / PRODUCT FIELDS
----------------------------------------------------------------------
usage_id: 24,979 unique values
subscription_id: 4,967 unique values
usage_date: 731 unique values
feature_name: 40 unique values
is_beta_feature: 2 unique values

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\1792482940.py:55: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = feature_usage_df.select_dtypes(

                 Usage_Records
is_beta_feature
False                    22456
True                      2544

4. USAGE-RELATED NUMERIC FIELDS
----------------------------------------------------------------------
['usage_count', 'usage_duration_secs', 'error_count']

5. USAGE BY FEATURE
----------------------------------------------------------------------

--- feature_name ---

Metric: usage_count

              count   sum       mean  median
feature_name
feature_32      659  6686  10.145675    10.0
feature_15      640  6621  10.345313    10.0
feature_6       655  6546   9.993893    10.0
feature_20      643  6541  10.172628    10.0
feature_34      650  6536  10.055385    10.0
feature_12      659  6534   9.915023    10.0
feature_11      643  6533  10.160187    10.0
feature_2       642  6525  10.163551    10.0
feature_38      643  6478  10.074650    10.0
feature_26      649  6470   9.969183    10.0
feature_17      651  6458   9.920123    10.0
feature_39      631  6430  10.190174    10.0
feature_31      644  6425   9.976708    10.0
feature_36      648  6389   9.859568    10.0
feature_24      643  6388   9.934681    10.0
feature_10      634  6384  10.069401    10.0
feature_37      636  6380  10.031447    10.0
feature_4       625  6374  10.198400    10.0
feature_22      636  6366  10.009434    10.0
feature_1       629  6364  10.117647    10.0

Metric: usage_duration_secs

              count      sum         mean  median
feature_name
feature_24      643  2070250  3219.673406  3003.0
feature_12      659  2061481  3128.195751  2948.0
feature_32      659  2052316  3114.288316  2844.0
feature_6       655  2013972  3074.766412  2728.0
feature_11      643  2012779  3130.293935  2950.0
feature_34      650  2006721  3087.263077  2824.5
feature_26      649  1976377  3045.265023  2828.0
feature_4       625  1968622  3149.795200  2872.0
feature_15      640  1966988  3073.418750  2779.5
feature_33      635  1963278  3091.776378  2895.0
feature_27      611  1956868  3202.729951  2961.0
feature_16      622  1952509  3139.081994  2872.0
feature_17      651  1950827  2996.662058  2748.0
feature_20      643  1947193  3028.293935  2800.0
feature_39      631  1945263  3082.825674  2808.0
feature_38      643  1942257  3020.617418  2700.0
feature_37      636  1939656  3049.773585  2770.0
feature_2       642  1935694  3015.099688  2668.5
feature_40      621  1931204  3109.829308  2992.0
feature_29      640  1919259  2998.842187  2656.0

Metric: error_count

              count  sum      mean  median
feature_name
feature_4       625  418  0.668800     0.0
feature_26      649  417  0.642527     0.0
feature_9       624  404  0.647436     0.0
feature_2       642  401  0.624611     0.0
feature_34      650  397  0.610769     0.0
feature_16      622  396  0.636656     0.0
feature_40      621  380  0.611916     0.0
feature_13      612  372  0.607843     0.0
feature_29      640  371  0.579688     0.0
feature_36      648  371  0.572531     0.0
feature_18      588  369  0.627551     0.0
feature_17      651  369  0.566820     0.0
feature_27      611  362  0.592471     0.0
feature_30      629  362  0.575517     0.0
feature_28      623  361  0.579454     0.0
feature_12      659  359  0.544765     0.0
feature_32      659  357  0.541730     0.0
feature_39      631  357  0.565769     0.0
feature_38      643  356  0.553655     0.0
feature_19      589  352  0.597623     0.0

--- is_beta_feature ---

Metric: usage_count

                 count     sum       mean  median
is_beta_feature
False            22456  224939  10.016877    10.0
True              2544   25586  10.057390    10.0

Metric: usage_duration_secs

                 count       sum         mean  median
is_beta_feature
False            22456  68297322  3041.384129  2760.0
True              2544   7757750  3049.430031  2771.0

Metric: error_count

                 count    sum      mean  median
is_beta_feature
False            22456  12691  0.565150     0.0
True              2544   1416  0.556604     0.0

6. USAGE DATE COVERAGE
----------------------------------------------------------------------
No datetime columns detected.

7. USAGE DATA QUALITY
----------------------------------------------------------------------

                     Missing_Count  Missing_%  Unique_Values
usage_id                         0        0.0          24979
subscription_id                  0        0.0           4967
usage_date                       0        0.0            731
feature_name                     0        0.0             40
usage_count                      0        0.0             27
usage_duration_secs              0        0.0           4168
error_count                      0        0.0              9
is_beta_feature                  0        0.0              2

======================================================================
PRODUCT / FEATURE USAGE ANALYSIS COMPLETE
======================================================================

In [15]:


support_df = datasets["support_tickets"].copy()

print("=" * 70)
print("SUPPORT TICKET ANALYSIS")
print("=" * 70)


# ------------------------------------------------
# 1. Support overview
# ------------------------------------------------

print("\n1. SUPPORT OVERVIEW")
print("-" * 70)

print(f"Total support tickets : {len(support_df):,}")

print("\nColumns:")
print(support_df.columns.tolist())


# ------------------------------------------------
# 2. Identify ticket-related fields
# ------------------------------------------------

print("\n2. TICKET / SUPPORT FIELDS")
print("-" * 70)

categorical_cols = support_df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

numeric_cols = support_df.select_dtypes(
    include="number"
).columns.tolist()

print("\nCategorical/Text columns:")
print(categorical_cols)

print("\nNumerical columns:")
print(numeric_cols)


# ------------------------------------------------
# 3. Categorical distributions
# ------------------------------------------------

print("\n3. SUPPORT CATEGORICAL DISTRIBUTIONS")
print("-" * 70)

for col in categorical_cols:

    unique_count = support_df[col].nunique(
        dropna=True
    )

    # Only display reasonably sized categorical fields
    if unique_count <= 30:

        print(f"\n--- {col} ---")

        summary = (
            support_df[col]
            .value_counts(dropna=False)
            .to_frame("Ticket_Count")
        )

        summary["Percentage"] = (
            summary["Ticket_Count"]
            / len(support_df)
            * 100
        ).round(2)

        display(summary)


# ------------------------------------------------
# 4. Numerical support metrics
# ------------------------------------------------

print("\n4. NUMERICAL SUPPORT METRICS")
print("-" * 70)

if numeric_cols:

    support_numeric_summary = pd.DataFrame({
        "Mean": support_df[numeric_cols].mean(),
        "Median": support_df[numeric_cols].median(),
        "Min": support_df[numeric_cols].min(),
        "Max": support_df[numeric_cols].max(),
        "Missing": support_df[numeric_cols].isna().sum()
    })

    display(support_numeric_summary)

else:
    print("No numerical support metrics found.")


# ------------------------------------------------
# 5. Ticket-related metric detection
# ------------------------------------------------

print("\n5. SUPPORT METRIC FIELDS")
print("-" * 70)

support_keywords = [
    "resolution",
    "response",
    "time",
    "duration",
    "priority",
    "severity",
    "rating",
    "satisfaction",
    "score",
    "ticket",
    "wait"
]

support_metric_candidates = [
    col
    for col in support_df.columns
    if any(
        keyword in col.lower()
        for keyword in support_keywords
    )
]

print(support_metric_candidates)


# ------------------------------------------------
# 6. Date coverage
# ------------------------------------------------

print("\n6. SUPPORT DATE COVERAGE")
print("-" * 70)

date_cols = support_df.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.tolist()

if date_cols:

    for col in date_cols:

        print(
            f"{col}: "
            f"{support_df[col].min()} → "
            f"{support_df[col].max()}"
        )

else:
    print("No datetime columns detected.")


# ------------------------------------------------
# 7. Support data quality
# ------------------------------------------------

print("\n7. SUPPORT DATA QUALITY")
print("-" * 70)

support_quality = pd.DataFrame({
    "Missing_Count": support_df.isna().sum(),
    "Missing_%": (
        support_df.isna().sum()
        / len(support_df)
        * 100
    ).round(2),
    "Unique_Values": support_df.nunique(
        dropna=True
    )
})

display(
    support_quality.sort_values(
        "Missing_Count",
        ascending=False
    )
)


print("\n" + "=" * 70)
print("SUPPORT TICKET ANALYSIS COMPLETE")
print("=" * 70)

======================================================================
SUPPORT TICKET ANALYSIS
======================================================================

1. SUPPORT OVERVIEW
----------------------------------------------------------------------
Total support tickets : 2,000

Columns:
['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'resolution_time_hours', 'priority', 'first_response_time_minutes', 'satisfaction_score', 'escalation_flag']

2. TICKET / SUPPORT FIELDS
----------------------------------------------------------------------

Categorical/Text columns:
['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'priority', 'escalation_flag']

Numerical columns:
['resolution_time_hours', 'first_response_time_minutes', 'satisfaction_score']

3. SUPPORT CATEGORICAL DISTRIBUTIONS
----------------------------------------------------------------------

--- priority ---

C:\Users\harsh\AppData\Local\Temp\ipykernel_26564\2421810329.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = support_df.select_dtypes(

          Ticket_Count  Percentage
priority
urgent             514       25.70
high               510       25.50
medium             491       24.55
low                485       24.25

--- escalation_flag ---

                 Ticket_Count  Percentage
escalation_flag
False                    1905       95.25
True                       95        4.75

4. NUMERICAL SUPPORT METRICS
----------------------------------------------------------------------

                                  Mean  Median  Min    Max  Missing
resolution_time_hours        35.861000    35.0  1.0   72.0        0
first_response_time_minutes  88.480000    88.0  1.0  180.0        0
satisfaction_score            3.981277     4.0  3.0    5.0      825

5. SUPPORT METRIC FIELDS
----------------------------------------------------------------------
['ticket_id', 'resolution_time_hours', 'priority', 'first_response_time_minutes', 'satisfaction_score']

6. SUPPORT DATE COVERAGE
----------------------------------------------------------------------
No datetime columns detected.

7. SUPPORT DATA QUALITY
----------------------------------------------------------------------

                             Missing_Count  Missing_%  Unique_Values
satisfaction_score                     825      41.25              3
ticket_id                                0       0.00           2000
account_id                               0       0.00            492
closed_at                                0       0.00           1893
submitted_at                             0       0.00            671
resolution_time_hours                    0       0.00             72
priority                                 0       0.00              4
first_response_time_minutes              0       0.00            180
escalation_flag                          0       0.00              2

======================================================================
SUPPORT TICKET ANALYSIS COMPLETE
======================================================================

In [17]:
# ============================================
# CELL 14 — CUSTOMER-LEVEL DATASET FOUNDATION
# ============================================

print("=" * 70)
print("CUSTOMER-LEVEL ANALYTICAL DATASET")
print("=" * 70)

# ------------------------------------------------
# 1. Identify account IDs in each dataset
# ------------------------------------------------

print("\n1. ACCOUNT ID COLUMNS")
print("-" * 70)

for name, df in datasets.items():

    account_id_cols = [
        col for col in df.columns
        if "account" in col.lower() and "id" in col.lower()
    ]

    print(f"{name:<20}: {account_id_cols}")


# ------------------------------------------------
# 2. Create base account table
# ------------------------------------------------

accounts_df = datasets["accounts"].copy()

account_id_candidates = [
    col for col in accounts_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if not account_id_candidates:
    raise KeyError(
        "No account ID column found in accounts dataset."
    )

ACCOUNT_ID = account_id_candidates[0]

customer_analytics = (
    accounts_df
    .drop_duplicates(subset=[ACCOUNT_ID])
    .copy()
)

print("\nBase customer table created.")
print(f"Account ID: {ACCOUNT_ID}")
print(f"Unique accounts: {len(customer_analytics):,}")


# ------------------------------------------------
# 3. Subscription-level aggregation
# ------------------------------------------------

subscriptions_df = datasets["subscriptions"].copy()

subscription_account_cols = [
    col for col in subscriptions_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if subscription_account_cols:

    SUB_ACCOUNT_ID = subscription_account_cols[0]

    subscription_agg = (
        subscriptions_df
        .groupby(SUB_ACCOUNT_ID)
        .agg(
            subscription_count=(
                SUB_ACCOUNT_ID, "count"
            )
        )
        .reset_index()
    )

    customer_analytics = customer_analytics.merge(
        subscription_agg,
        left_on=ACCOUNT_ID,
        right_on=SUB_ACCOUNT_ID,
        how="left"
    )

    if SUB_ACCOUNT_ID != ACCOUNT_ID:
        customer_analytics.drop(
            columns=[SUB_ACCOUNT_ID],
            inplace=True
        )

    print(
        f"\n✓ Subscription aggregation added: "
        f"{len(subscription_agg):,} accounts"
    )

else:

    print(
        "\n⚠ No account ID found in subscriptions."
    )


# ------------------------------------------------
# 4. Feature usage aggregation
# ------------------------------------------------

feature_usage_df = datasets["feature_usage"].copy()

usage_account_cols = [
    col for col in feature_usage_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if usage_account_cols:

    USAGE_ACCOUNT_ID = usage_account_cols[0]

    usage_agg = (
        feature_usage_df
        .groupby(USAGE_ACCOUNT_ID)
        .agg(
            usage_record_count=(
                USAGE_ACCOUNT_ID, "count"
            )
        )
        .reset_index()
    )

    customer_analytics = customer_analytics.merge(
        usage_agg,
        left_on=ACCOUNT_ID,
        right_on=USAGE_ACCOUNT_ID,
        how="left"
    )

    if USAGE_ACCOUNT_ID != ACCOUNT_ID:
        customer_analytics.drop(
            columns=[USAGE_ACCOUNT_ID],
            inplace=True
        )

    print(
        f"✓ Feature usage aggregation added: "
        f"{len(usage_agg):,} accounts"
    )

else:

    print(
        "\n⚠ No account ID found in feature usage."
    )


# ------------------------------------------------
# 5. Support aggregation
# ------------------------------------------------

support_df = datasets["support_tickets"].copy()

support_account_cols = [
    col for col in support_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if support_account_cols:

    SUPPORT_ACCOUNT_ID = support_account_cols[0]

    support_agg = (
        support_df
        .groupby(SUPPORT_ACCOUNT_ID)
        .agg(
            support_ticket_count=(
                SUPPORT_ACCOUNT_ID, "count"
            )
        )
        .reset_index()
    )

    customer_analytics = customer_analytics.merge(
        support_agg,
        left_on=ACCOUNT_ID,
        right_on=SUPPORT_ACCOUNT_ID,
        how="left"
    )

    if SUPPORT_ACCOUNT_ID != ACCOUNT_ID:
        customer_analytics.drop(
            columns=[SUPPORT_ACCOUNT_ID],
            inplace=True
        )

    print(
        f"✓ Support aggregation added: "
        f"{len(support_agg):,} accounts"
    )

else:

    print(
        "\n⚠ No account ID found in support tickets."
    )


# ------------------------------------------------
# 6. Churn aggregation
# ------------------------------------------------

churn_df = datasets["churn_events"].copy()

churn_account_cols = [
    col for col in churn_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if churn_account_cols:

    CHURN_ACCOUNT_ID = churn_account_cols[0]

    churn_agg = (
        churn_df
        .groupby(CHURN_ACCOUNT_ID)
        .agg(
            churn_event_count=(
                CHURN_ACCOUNT_ID, "count"
            )
        )
        .reset_index()
    )

    # Create binary churn flag
    churn_agg["churned_flag"] = 1

    customer_analytics = customer_analytics.merge(
        churn_agg,
        left_on=ACCOUNT_ID,
        right_on=CHURN_ACCOUNT_ID,
        how="left"
    )

    if CHURN_ACCOUNT_ID != ACCOUNT_ID:
        customer_analytics.drop(
            columns=[CHURN_ACCOUNT_ID],
            inplace=True
        )

    print(
        f"✓ Churn aggregation added: "
        f"{len(churn_agg):,} accounts"
    )

else:

    print(
        "\n⚠ No account ID found in churn events."
    )


# ------------------------------------------------
# 7. Fill aggregation-based missing values
# ------------------------------------------------

aggregation_columns = [
    "subscription_count",
    "usage_record_count",
    "support_ticket_count",
    "churn_event_count",
    "churned_flag"
]

for col in aggregation_columns:

    if col in customer_analytics.columns:
        customer_analytics[col] = (
            customer_analytics[col]
            .fillna(0)
        )


# ------------------------------------------------
# 8. Final customer-level dataset
# ------------------------------------------------

print("\n" + "=" * 70)
print("CUSTOMER ANALYTICAL DATASET")
print("=" * 70)

print(
    f"Rows: {customer_analytics.shape[0]:,}"
)

print(
    f"Columns: {customer_analytics.shape[1]:,}"
)

print("\nColumns:")
print(customer_analytics.columns.tolist())

print("\nFirst 10 rows:")
display(customer_analytics.head(10))


# ------------------------------------------------
# 9. Verify one row per account
# ------------------------------------------------

print("\n" + "=" * 70)
print("ACCOUNT GRAIN VALIDATION")
print("=" * 70)

duplicate_accounts = (
    customer_analytics[ACCOUNT_ID]
    .duplicated()
    .sum()
)

print(
    f"Duplicate account IDs: {duplicate_accounts:,}"
)

if duplicate_accounts == 0:
    print("✓ Confirmed: one row per account.")
else:
    print("⚠ Multiple rows per account detected.")


print("\n" + "=" * 70)
print("CUSTOMER-LEVEL FOUNDATION COMPLETE")
print("=" * 70)

======================================================================
CUSTOMER-LEVEL ANALYTICAL DATASET
======================================================================

1. ACCOUNT ID COLUMNS
----------------------------------------------------------------------
accounts            : ['account_id']
subscriptions       : ['account_id']
feature_usage       : []
support_tickets     : ['account_id']
churn_events        : ['account_id']

Base customer table created.
Account ID: account_id
Unique accounts: 500

✓ Subscription aggregation added: 500 accounts

⚠ No account ID found in feature usage.
✓ Support aggregation added: 492 accounts
✓ Churn aggregation added: 352 accounts

======================================================================
CUSTOMER ANALYTICAL DATASET
======================================================================
Rows: 500
Columns: 14

Columns:
['account_id', 'account_name', 'industry', 'country', 'signup_date', 'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag', 'subscription_count', 'support_ticket_count', 'churn_event_count', 'churned_flag']

First 10 rows:

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,subscription_count,support_ticket_count,churn_event_count,churned_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,10,2.0,2.0,1.0
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,8,3.0,0.0,0.0
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,15,3.0,2.0,1.0
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,7,2.0,1.0,1.0
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,9,7.0,1.0,1.0
5,A-1b9609,Company_5,EdTech,IN,2023-10-12,ads,Enterprise,4,False,False,11,4.0,3.0,1.0
6,A-a0ca4e,Company_6,Cybersecurity,US,2024-03-08,ads,Pro,11,False,False,9,6.0,0.0,0.0
7,A-e5d6ab,Company_7,EdTech,US,2023-04-15,partner,Pro,3,False,False,10,3.0,2.0,1.0
8,A-7dacce,Company_8,Cybersecurity,CA,2024-09-10,event,Enterprise,12,False,True,10,4.0,3.0,1.0
9,A-10b8da,Company_9,DevTools,US,2023-05-08,partner,Enterprise,14,False,True,6,3.0,0.0,0.0

======================================================================
ACCOUNT GRAIN VALIDATION
======================================================================
Duplicate account IDs: 0
✓ Confirmed: one row per account.

======================================================================
CUSTOMER-LEVEL FOUNDATION COMPLETE
======================================================================

In [18]:


print("=" * 70)
print("CUSTOMER REVENUE & SUBSCRIPTION FEATURES")
print("=" * 70)


# ------------------------------------------------
# 1. Prepare subscription data
# ------------------------------------------------

subscriptions_df = datasets["subscriptions"].copy()

subscription_account_cols = [
    col for col in subscriptions_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

if not subscription_account_cols:
    raise KeyError(
        "No account_id column found in subscriptions dataset."
    )

SUB_ACCOUNT_ID = subscription_account_cols[0]

print(f"\nAccount key used: {SUB_ACCOUNT_ID}")


# ------------------------------------------------
# 2. Identify numeric subscription metrics
# ------------------------------------------------

numeric_cols = subscriptions_df.select_dtypes(
    include="number"
).columns.tolist()

# Exclude obvious identifier columns
metric_cols = [
    col for col in numeric_cols
    if not (
        col.lower() == "id"
        or col.lower().endswith("_id")
    )
]

print("\nNumeric subscription metrics detected:")
print(metric_cols)


# ------------------------------------------------
# 3. Aggregate subscription metrics by account
# ------------------------------------------------

if metric_cols:

    revenue_agg = (
        subscriptions_df
        .groupby(SUB_ACCOUNT_ID)[metric_cols]
        .agg(["sum", "mean", "min", "max"])
    )

    # Flatten MultiIndex column names
    revenue_agg.columns = [
        f"{col}_{stat}"
        for col, stat in revenue_agg.columns
    ]

    revenue_agg = revenue_agg.reset_index()

    print("\nSubscription metrics aggregated by account:")
    display(revenue_agg.head(10))


    # ------------------------------------------------
    # 4. Merge into customer analytical dataset
    # ------------------------------------------------

    customer_analytics = customer_analytics.merge(
        revenue_agg,
        left_on=ACCOUNT_ID,
        right_on=SUB_ACCOUNT_ID,
        how="left"
    )

    if SUB_ACCOUNT_ID != ACCOUNT_ID:
        customer_analytics.drop(
            columns=[SUB_ACCOUNT_ID],
            inplace=True
        )

    print(
        "\n✓ Revenue/subscription features added "
        "to customer_analytics."
    )

else:

    print(
        "\n⚠ No numeric subscription metrics "
        "were detected."
    )


# ------------------------------------------------
# 5. Fill aggregation-based missing values
# ------------------------------------------------

if metric_cols:

    aggregated_columns = [
        col for col in revenue_agg.columns
        if col != SUB_ACCOUNT_ID
    ]

    for col in aggregated_columns:

        if col in customer_analytics.columns:

            customer_analytics[col] = (
                customer_analytics[col]
                .fillna(0)
            )


# ------------------------------------------------
# 6. Identify important revenue fields
# ------------------------------------------------

print("\n" + "=" * 70)
print("REVENUE-RELATED FEATURES")
print("=" * 70)

revenue_features = [
    col
    for col in customer_analytics.columns
    if any(
        keyword in col.lower()
        for keyword in [
            "mrr",
            "arr",
            "revenue",
            "price",
            "amount",
            "billing",
            "cost"
        ]
    )
]

print(revenue_features)


# ------------------------------------------------
# 7. Customer revenue summary
# ------------------------------------------------

if revenue_features:

    print("\nRevenue feature statistics:")

    available_revenue_features = [
        col for col in revenue_features
        if pd.api.types.is_numeric_dtype(
            customer_analytics[col]
        )
    ]

    if available_revenue_features:

        display(
            customer_analytics[
                available_revenue_features
            ]
            .describe()
            .T
        )


# ------------------------------------------------
# 8. Final dataset status
# ------------------------------------------------

print("\n" + "=" * 70)
print("CUSTOMER DATASET UPDATED")
print("=" * 70)

print(
    f"Rows    : {customer_analytics.shape[0]:,}"
)

print(
    f"Columns : {customer_analytics.shape[1]:,}"
)

print("\nSample:")
display(customer_analytics.head())


print("\n✓ Customer revenue/subscription feature engineering complete.")

======================================================================
CUSTOMER REVENUE & SUBSCRIPTION FEATURES
======================================================================

Account key used: account_id

Numeric subscription metrics detected:
['seats', 'mrr_amount', 'arr_amount']

Subscription metrics aggregated by account:

,account_id,seats_sum,seats_mean,seats_min,seats_max,mrr_amount_sum,mrr_amount_mean,mrr_amount_min,mrr_amount_max,arr_amount_sum,arr_amount_mean,arr_amount_min,arr_amount_max
0,A-00bed1,342,34.200000,28,61,33506,3350.600000,0,9751,402072,40207.200000,0,117012
1,A-00cac8,138,15.333333,8,39,14121,1569.000000,0,7761,169452,18828.000000,0,93132
2,A-0158bb,155,25.833333,9,45,4070,678.333333,0,2205,48840,8140.000000,0,26460
3,A-016043,225,20.454545,6,59,16516,1501.454545,0,4776,198192,18017.454545,0,57312
4,A-019782,123,13.666667,11,17,8353,928.111111,0,3184,100236,11137.333333,0,38208
5,A-029f69,220,13.750000,3,34,14638,914.875000,0,4776,175656,10978.500000,0,57312
6,A-02cd81,616,44.000000,44,44,32956,2354.000000,0,8756,395472,28248.000000,0,105072
7,A-02fac6,280,25.454545,22,59,26410,2400.909091,418,4577,316920,28810.909091,5016,54924
8,A-034368,125,25.000000,19,29,11194,2238.800000,0,5572,134328,26865.600000,0,66864
9,A-0354fe,238,34.000000,34,34,15470,2210.000000,0,6766,185640,26520.000000,0,81192

✓ Revenue/subscription features added to customer_analytics.

======================================================================
REVENUE-RELATED FEATURES
======================================================================
['mrr_amount_sum', 'mrr_amount_mean', 'mrr_amount_min', 'mrr_amount_max', 'arr_amount_sum', 'arr_amount_mean', 'arr_amount_min', 'arr_amount_max']

Revenue feature statistics:

,count,mean,std,min,25%,50%,75%,max
mrr_amount_sum,500.0,22677.494000,17294.852405,190.0,11884.25,18833.500000,28874.750000,138060.0
mrr_amount_mean,500.0,2264.176843,1600.412647,95.0,1259.45,1923.145833,2744.294643,13806.0
mrr_amount_min,500.0,89.342000,269.151225,0.0,0.00,0.000000,0.000000,2223.0
mrr_amount_max,500.0,7699.980000,4952.732971,190.0,4378.00,6567.000000,9950.000000,33830.0
arr_amount_sum,500.0,272129.928000,207538.228865,2280.0,142611.00,226002.000000,346497.000000,1656720.0
arr_amount_mean,500.0,27170.122121,19204.951766,1140.0,15113.40,23077.750000,32931.535714,165672.0
arr_amount_min,500.0,1072.104000,3229.814697,0.0,0.00,0.000000,0.000000,26676.0
arr_amount_max,500.0,92399.760000,59432.795654,2280.0,52536.00,78804.000000,119400.000000,405960.0

======================================================================
CUSTOMER DATASET UPDATED
======================================================================
Rows    : 500
Columns : 26

Sample:

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,subscription_count,support_ticket_count,churn_event_count,churned_flag,seats_sum,seats_mean,seats_min,seats_max,mrr_amount_sum,mrr_amount_mean,mrr_amount_min,mrr_amount_max,arr_amount_sum,arr_amount_mean,arr_amount_min,arr_amount_max
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,10,2.0,2.0,1.0,312,31.200000,9,102,12603,1260.300000,0,5771,151236,15123.600000,0,69252
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,8,3.0,0.0,0.0,176,22.000000,18,28,10004,1250.500000,342,5572,120048,15006.000000,4104,66864
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,15,3.0,2.0,1.0,282,18.800000,1,60,18286,1219.066667,0,5771,219432,14628.800000,0,69252
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,7,2.0,1.0,1.0,209,29.857143,24,47,9275,1325.000000,0,4776,111300,15900.000000,0,57312
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,9,7.0,1.0,1.0,424,47.111111,35,109,48761,5417.888889,0,21691,585132,65014.666667,0,260292

✓ Customer revenue/subscription feature engineering complete.

In [20]:


feature_usage_df = datasets["feature_usage"].copy()

print("=" * 70)
print("FEATURE USAGE COLUMN DIAGNOSTIC")
print("=" * 70)

print("\nShape:")
print(feature_usage_df.shape)

print("\nColumns:")
for i, col in enumerate(feature_usage_df.columns, start=1):
    print(f"{i}. {col}")

print("\nData types:")
display(feature_usage_df.dtypes.to_frame("dtype"))

print("\nFirst 5 rows:")
display(feature_usage_df.head())

print("\nPotential ID / key columns:")
for col in feature_usage_df.columns:
    if any(
        keyword in col.lower()
        for keyword in ["account", "customer", "user", "subscription", "id"]
    ):
        print(f"- {col}")

======================================================================
FEATURE USAGE COLUMN DIAGNOSTIC
======================================================================

Shape:
(25000, 8)

Columns:
1. usage_id
2. subscription_id
3. usage_date
4. feature_name
5. usage_count
6. usage_duration_secs
7. error_count
8. is_beta_feature

Data types:

                     dtype
usage_id               str
subscription_id        str
usage_date             str
feature_name           str
usage_count          int64
usage_duration_secs  int64
error_count          int64
is_beta_feature       bool

First 5 rows:

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

Potential ID / key columns:
- usage_id
- subscription_id

In [21]:


print("=" * 70)
print("CUSTOMER USAGE & ENGAGEMENT FEATURES")
print("=" * 70)

# ------------------------------------------------
# 1. Prepare datasets
# ------------------------------------------------

feature_usage_df = datasets["feature_usage"].copy()
subscriptions_df = datasets["subscriptions"].copy()

print("\nFeature usage shape:", feature_usage_df.shape)
print("Subscriptions shape:", subscriptions_df.shape)

# ------------------------------------------------
# 2. Identify subscription and account keys
# ------------------------------------------------

usage_subscription_cols = [
    col for col in feature_usage_df.columns
    if "subscription" in col.lower() and "id" in col.lower()
]

subscription_account_cols = [
    col for col in subscriptions_df.columns
    if "account" in col.lower() and "id" in col.lower()
]

subscription_id_cols = [
    col for col in subscriptions_df.columns
    if "subscription" in col.lower() and "id" in col.lower()
]

if not usage_subscription_cols:
    raise KeyError("No subscription ID found in feature_usage.")

if not subscription_account_cols:
    raise KeyError("No account ID found in subscriptions.")

if not subscription_id_cols:
    raise KeyError("No subscription ID found in subscriptions.")

USAGE_SUB_ID = usage_subscription_cols[0]
SUB_ID = subscription_id_cols[0]
SUB_ACCOUNT_ID = subscription_account_cols[0]

print("\nKeys identified:")
print("Feature usage subscription key :", USAGE_SUB_ID)
print("Subscriptions subscription key :", SUB_ID)
print("Subscriptions account key      :", SUB_ACCOUNT_ID)

# ------------------------------------------------
# 3. Map subscription → account
# ------------------------------------------------

subscription_mapping = (
    subscriptions_df[
        [SUB_ID, SUB_ACCOUNT_ID]
    ]
    .drop_duplicates()
)

feature_usage_customer = feature_usage_df.merge(
    subscription_mapping,
    left_on=USAGE_SUB_ID,
    right_on=SUB_ID,
    how="left"
)

print("\nUsage records after subscription → account mapping:")
print(feature_usage_customer.shape)

print(
    "\nUsage records without matching account:",
    feature_usage_customer[SUB_ACCOUNT_ID].isna().sum()
)

# ------------------------------------------------
# 4. Identify numeric usage metrics
# ------------------------------------------------

numeric_usage_cols = feature_usage_customer.select_dtypes(
    include="number"
).columns.tolist()

usage_metric_cols = [
    col
    for col in numeric_usage_cols
    if col not in []
]

print("\nNumeric usage metrics:")
print(usage_metric_cols)

# ------------------------------------------------
# 5. Aggregate usage metrics by account
# ------------------------------------------------

usage_agg = (
    feature_usage_customer
    .groupby(SUB_ACCOUNT_ID)[usage_metric_cols]
    .agg(["sum", "mean", "max"])
)

usage_agg.columns = [
    f"usage_{col}_{stat}"
    for col, stat in usage_agg.columns
]

usage_agg = usage_agg.reset_index()

print("\nAggregated usage metrics:")
display(usage_agg.head(10))

# ------------------------------------------------
# 6. Total usage records per customer
# ------------------------------------------------

usage_record_counts = (
    feature_usage_customer
    .groupby(SUB_ACCOUNT_ID)
    .size()
    .rename("usage_records")
    .reset_index()
)

# ------------------------------------------------
# 7. Number of different features used
# ------------------------------------------------

distinct_features = (
    feature_usage_customer
    .groupby(SUB_ACCOUNT_ID)["feature_name"]
    .nunique()
    .rename("distinct_features_used")
    .reset_index()
)

# ------------------------------------------------
# 8. Active usage days
# ------------------------------------------------

feature_usage_customer["usage_date"] = pd.to_datetime(
    feature_usage_customer["usage_date"],
    errors="coerce"
)

active_usage_days = (
    feature_usage_customer
    .groupby(SUB_ACCOUNT_ID)["usage_date"]
    .nunique()
    .rename("active_usage_days")
    .reset_index()
)

# ------------------------------------------------
# 9. Beta feature usage
# ------------------------------------------------

beta_usage = (
    feature_usage_customer
    .groupby(SUB_ACCOUNT_ID)["is_beta_feature"]
    .sum()
    .rename("beta_feature_usage_count")
    .reset_index()
)

# ------------------------------------------------
# 10. Merge all usage features
# ------------------------------------------------

usage_customer_features = usage_agg.merge(
    usage_record_counts,
    on=SUB_ACCOUNT_ID,
    how="outer"
)

usage_customer_features = usage_customer_features.merge(
    distinct_features,
    on=SUB_ACCOUNT_ID,
    how="outer"
)

usage_customer_features = usage_customer_features.merge(
    active_usage_days,
    on=SUB_ACCOUNT_ID,
    how="outer"
)

usage_customer_features = usage_customer_features.merge(
    beta_usage,
    on=SUB_ACCOUNT_ID,
    how="outer"
)

# ------------------------------------------------
# 11. Merge into customer analytics
# ------------------------------------------------

customer_analytics = customer_analytics.merge(
    usage_customer_features,
    left_on=ACCOUNT_ID,
    right_on=SUB_ACCOUNT_ID,
    how="left"
)

if SUB_ACCOUNT_ID != ACCOUNT_ID:
    customer_analytics.drop(
        columns=[SUB_ACCOUNT_ID],
        inplace=True
    )

# ------------------------------------------------
# 12. Fill usage-based missing values
# ------------------------------------------------

usage_features = [
    col
    for col in customer_analytics.columns
    if (
        col.startswith("usage_")
        or col in [
            "usage_records",
            "distinct_features_used",
            "active_usage_days",
            "beta_feature_usage_count"
        ]
    )
]

for col in usage_features:
    if pd.api.types.is_numeric_dtype(
        customer_analytics[col]
    ):
        customer_analytics[col] = (
            customer_analytics[col]
            .fillna(0)
        )

# ------------------------------------------------
# 13. Final result
# ------------------------------------------------

print("\n" + "=" * 70)
print("USAGE FEATURES ADDED TO CUSTOMER ANALYTICS")
print("=" * 70)

print("\nFeatures created:")
print(usage_features)

print("\nCustomer analytics shape:")
print(customer_analytics.shape)

print("\nCustomer usage feature sample:")
display(
    customer_analytics[
        [ACCOUNT_ID] + usage_features
    ].head(10)
)

print(
    "\n✓ Customer usage & engagement feature engineering complete."
)

======================================================================
CUSTOMER USAGE & ENGAGEMENT FEATURES
======================================================================

Feature usage shape: (25000, 8)
Subscriptions shape: (5000, 14)

Keys identified:
Feature usage subscription key : subscription_id
Subscriptions subscription key : subscription_id
Subscriptions account key      : account_id

Usage records after subscription → account mapping:
(25000, 9)

Usage records without matching account: 0

Numeric usage metrics:
['usage_count', 'usage_duration_secs', 'error_count']

Aggregated usage metrics:

,account_id,usage_usage_count_sum,usage_usage_count_mean,usage_usage_count_max,usage_usage_duration_secs_sum,usage_usage_duration_secs_mean,usage_usage_duration_secs_max,usage_error_count_sum,usage_error_count_mean,usage_error_count_max
0,A-00bed1,514,10.078431,16,143734,2818.313725,7553,27,0.529412,4
1,A-00cac8,602,10.379310,17,171366,2954.586207,8190,31,0.534483,3
2,A-0158bb,364,10.111111,16,122051,3390.305556,8550,22,0.611111,4
3,A-016043,490,10.425532,18,132075,2810.106383,8944,21,0.446809,5
4,A-019782,562,10.218182,21,160848,2924.509091,7761,30,0.545455,4
5,A-029f69,789,9.392857,21,241275,2872.321429,10143,42,0.500000,5
6,A-02cd81,684,9.500000,16,219304,3045.888889,8384,28,0.388889,3
7,A-02fac6,514,9.698113,17,169854,3204.792453,8925,34,0.641509,5
8,A-034368,265,9.464286,15,80423,2872.250000,7200,25,0.892857,5
9,A-0354fe,463,10.288889,21,152435,3387.444444,9303,30,0.666667,5

======================================================================
USAGE FEATURES ADDED TO CUSTOMER ANALYTICS
======================================================================

Features created:
['usage_usage_count_sum', 'usage_usage_count_mean', 'usage_usage_count_max', 'usage_usage_duration_secs_sum', 'usage_usage_duration_secs_mean', 'usage_usage_duration_secs_max', 'usage_error_count_sum', 'usage_error_count_mean', 'usage_error_count_max', 'usage_records', 'distinct_features_used', 'active_usage_days', 'beta_feature_usage_count']

Customer analytics shape:
(500, 39)

Customer usage feature sample:

,account_id,usage_usage_count_sum,usage_usage_count_mean,usage_usage_count_max,usage_usage_duration_secs_sum,usage_usage_duration_secs_mean,usage_usage_duration_secs_max,usage_error_count_sum,usage_error_count_mean,usage_error_count_max,usage_records,distinct_features_used,active_usage_days,beta_feature_usage_count
0,A-2e4581,535,9.727273,15,152339,2769.800000,7728,38,0.690909,5,55,27,55,4
1,A-43a9e3,355,10.142857,19,101136,2889.600000,6228,14,0.400000,3,35,23,35,2
2,A-0a282f,821,9.891566,17,251210,3026.626506,7504,48,0.578313,3,83,34,80,5
3,A-1f0ac7,382,9.317073,15,102528,2500.682927,6090,21,0.512195,3,41,26,40,5
4,A-ce550d,579,9.982759,17,215779,3720.327586,9452,31,0.534483,3,58,32,56,4
5,A-1b9609,457,9.723404,20,140541,2990.234043,10820,21,0.446809,3,47,28,44,6
6,A-a0ca4e,373,9.564103,16,116964,2999.076923,8048,14,0.358974,3,39,26,39,3
7,A-e5d6ab,382,9.317073,16,111506,2719.658537,7322,23,0.560976,4,41,29,39,5
8,A-7dacce,472,9.833333,17,145429,3029.770833,8940,29,0.604167,5,48,27,48,5
9,A-10b8da,257,9.518519,16,73818,2734.000000,7910,14,0.518519,4,27,23,26,2

✓ Customer usage & engagement feature engineering complete.

In [ ]:
# ============================================
# DIAGNOSTIC — SUPPORT TICKET COLUMNS
# ============================================

support_df = datasets["support_tickets"].copy()

print("=" * 70)
print("SUPPORT TICKET COLUMN DIAGNOSTIC")
print("=" * 70)

print("\nShape:")
print(support_df.shape)

print("\nColumns:")
for i, col in enumerate(support_df.columns, start=1):
    print(f"{i}. {col}")

print("\nData types:")
display(support_df.dtypes.to_frame("dtype"))

print("\nFirst 5 rows:")
display(support_df.head())

print("\nPotential ID / key columns:")
for col in support_df.columns:
    if any(
        keyword in col.lower()
        for keyword in [
            "account",
            "customer",
            "user",
        

        print(f"- {col}")

======================================================================
SUPPORT TICKET COLUMN DIAGNOSTIC
======================================================================

Shape:
(2000, 9)

Columns:
1. ticket_id
2. account_id
3. submitted_at
4. closed_at
5. resolution_time_hours
6. priority
7. first_response_time_minutes
8. satisfaction_score
9. escalation_flag

Data types:

                               dtype
ticket_id                        str
account_id                       str
submitted_at                     str
closed_at                        str
resolution_time_hours        float64
priority                         str
first_response_time_minutes    int64
satisfaction_score           float64
escalation_flag                 bool

First 5 rows:

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

Potential ID / key columns:
- ticket_id
- account_id

In [24]:


print("=" * 70)
print("CUSTOMER SUPPORT & SERVICE FEATURES")
print("=" * 70)

# ------------------------------------------------
# 1. Prepare support data
# ------------------------------------------------

support_df = datasets["support_tickets"].copy()

SUPPORT_ACCOUNT_ID = "account_id"

print("\nSupport tickets:", len(support_df))
print("Unique customers:", support_df[SUPPORT_ACCOUNT_ID].nunique())

# ------------------------------------------------
# 2. Convert support dates
# ------------------------------------------------

support_df["submitted_at"] = pd.to_datetime(
    support_df["submitted_at"],
    errors="coerce"
)

support_df["closed_at"] = pd.to_datetime(
    support_df["closed_at"],
    errors="coerce"
)

# ------------------------------------------------
# 3. Create basic support metrics
# ------------------------------------------------

support_df["escalation_flag_numeric"] = (
    support_df["escalation_flag"]
    .astype(int)
)

# ------------------------------------------------
# 4. Aggregate numerical support metrics
# ------------------------------------------------

support_agg = (
    support_df
    .groupby(SUPPORT_ACCOUNT_ID)
    .agg(
        support_ticket_count=("ticket_id", "count"),
        
        avg_resolution_time_hours=(
            "resolution_time_hours",
            "mean"
        ),
        
        max_resolution_time_hours=(
            "resolution_time_hours",
            "max"
        ),
        
        avg_first_response_minutes=(
            "first_response_time_minutes",
            "mean"
        ),
        
        avg_satisfaction_score=(
            "satisfaction_score",
            "mean"
        ),
        
        total_escalations=(
            "escalation_flag_numeric",
            "sum"
        )
    )
    .reset_index()
)

# ------------------------------------------------
# 5. Priority distribution
# ------------------------------------------------

priority_counts = pd.crosstab(
    support_df[SUPPORT_ACCOUNT_ID],
    support_df["priority"]
).reset_index()

priority_counts.columns = [
    str(col).strip().lower().replace(" ", "_")
    if col != SUPPORT_ACCOUNT_ID
    else SUPPORT_ACCOUNT_ID
    for col in priority_counts.columns
]

priority_counts = priority_counts.rename(
    columns={
        col: f"support_{col}_tickets"
        for col in priority_counts.columns
        if col != SUPPORT_ACCOUNT_ID
    }
)

# ------------------------------------------------
# 6. Merge support features together
# ------------------------------------------------

support_customer_features = support_agg.merge(
    priority_counts,
    on=SUPPORT_ACCOUNT_ID,
    how="left"
)

# ------------------------------------------------
# 7. Merge into customer analytics
# ------------------------------------------------

customer_analytics = customer_analytics.merge(
    support_customer_features,
    left_on=ACCOUNT_ID,
    right_on=SUPPORT_ACCOUNT_ID,
    how="left"
)

if SUPPORT_ACCOUNT_ID != ACCOUNT_ID:
    customer_analytics.drop(
        columns=[SUPPORT_ACCOUNT_ID],
        inplace=True
    )

# ------------------------------------------------
# 8. Fill missing support activity
# ------------------------------------------------

support_features = [
    col
    for col in customer_analytics.columns
    if (
        col.startswith("support_")
        or col in [
            "avg_resolution_time_hours",
            "max_resolution_time_hours",
            "avg_first_response_minutes",
            "avg_satisfaction_score",
            "total_escalations"
        ]
    )
]

for col in support_features:
    if pd.api.types.is_numeric_dtype(
        customer_analytics[col]
    ):
        customer_analytics[col] = (
            customer_analytics[col]
            .fillna(0)
        )

# ------------------------------------------------
# 9. Final result
# ------------------------------------------------

print("\n" + "=" * 70)
print("SUPPORT FEATURES ADDED")
print("=" * 70)

print("\nFeatures created:")
print(support_features)

print("\nCustomer analytics shape:")
print(customer_analytics.shape)

print("\nSupport feature sample:")
display(
    customer_analytics[
        [ACCOUNT_ID] + support_features
    ].head(10)
)

print(
    "\n✓ Customer support & service feature engineering complete."
)

======================================================================
CUSTOMER SUPPORT & SERVICE FEATURES
======================================================================

Support tickets: 2000
Unique customers: 492

======================================================================
SUPPORT FEATURES ADDED
======================================================================

Features created:
['support_ticket_count_x', 'support_ticket_count_y', 'avg_resolution_time_hours', 'max_resolution_time_hours', 'avg_first_response_minutes', 'avg_satisfaction_score', 'total_escalations', 'support_high_tickets', 'support_low_tickets', 'support_medium_tickets', 'support_urgent_tickets']

Customer analytics shape:
(500, 49)

Support feature sample:

,account_id,support_ticket_count_x,support_ticket_count_y,avg_resolution_time_hours,max_resolution_time_hours,avg_first_response_minutes,avg_satisfaction_score,total_escalations,support_high_tickets,support_low_tickets,support_medium_tickets,support_urgent_tickets
0,A-2e4581,2.0,2.0,23.000000,27.0,91.000000,3.000000,0.0,1.0,0.0,0.0,1.0
1,A-43a9e3,3.0,3.0,38.000000,64.0,73.333333,4.000000,0.0,0.0,0.0,1.0,2.0
2,A-0a282f,3.0,3.0,43.666667,65.0,63.666667,4.666667,0.0,0.0,0.0,2.0,1.0
3,A-1f0ac7,2.0,2.0,29.000000,44.0,174.000000,0.000000,0.0,1.0,1.0,0.0,0.0
4,A-ce550d,7.0,7.0,42.285714,69.0,107.857143,3.800000,1.0,2.0,0.0,3.0,2.0
5,A-1b9609,4.0,4.0,43.000000,65.0,74.750000,3.000000,0.0,2.0,1.0,0.0,1.0
6,A-a0ca4e,6.0,6.0,39.166667,61.0,89.833333,3.800000,3.0,2.0,4.0,0.0,0.0
7,A-e5d6ab,3.0,3.0,42.666667,54.0,57.000000,0.000000,0.0,2.0,1.0,0.0,0.0
8,A-7dacce,4.0,4.0,32.500000,60.0,75.250000,3.666667,0.0,3.0,0.0,0.0,1.0
9,A-10b8da,3.0,3.0,31.333333,37.0,71.333333,3.500000,0.0,2.0,1.0,0.0,0.0

✓ Customer support & service feature engineering complete.

In [25]:


print("=" * 70)
print("CLEANING DUPLICATE SUPPORT FEATURES")
print("=" * 70)

# ------------------------------------------------
# 1. Check duplicate support ticket columns
# ------------------------------------------------

duplicate_support_cols = [
    col
    for col in [
        "support_ticket_count_x",
        "support_ticket_count_y"
    ]
    if col in customer_analytics.columns
]

print("\nDuplicate columns found:")
print(duplicate_support_cols)

# ------------------------------------------------
# 2. Keep one correct support ticket count
# ------------------------------------------------

if (
    "support_ticket_count_x" in customer_analytics.columns
    and "support_ticket_count_y" in customer_analytics.columns
):

    # Verify both columns contain the same values
    same_values = customer_analytics[
        "support_ticket_count_x"
    ].equals(
        customer_analytics[
            "support_ticket_count_y"
        ]
    )

    print("\nBoth columns identical:", same_values)

    # Keep one clean column
    customer_analytics["support_ticket_count"] = (
        customer_analytics["support_ticket_count_x"]
    )

    customer_analytics.drop(
        columns=[
            "support_ticket_count_x",
            "support_ticket_count_y"
        ],
        inplace=True
    )

elif "support_ticket_count_x" in customer_analytics.columns:

    customer_analytics.rename(
        columns={
            "support_ticket_count_x":
            "support_ticket_count"
        },
        inplace=True
    )

elif "support_ticket_count_y" in customer_analytics.columns:

    customer_analytics.rename(
        columns={
            "support_ticket_count_y":
            "support_ticket_count"
        },
        inplace=True
    )

# ------------------------------------------------
# 3. Check final support features
# ------------------------------------------------

support_features = [
    col
    for col in customer_analytics.columns
    if (
        col.startswith("support_")
        or col in [
            "avg_resolution_time_hours",
            "max_resolution_time_hours",
            "avg_first_response_minutes",
            "avg_satisfaction_score",
            "total_escalations"
        ]
    )
]

print("\nFinal support features:")
print(support_features)

print("\nCustomer analytics shape:")
print(customer_analytics.shape)

print("\n✓ Duplicate support feature cleanup complete.")

======================================================================
CLEANING DUPLICATE SUPPORT FEATURES
======================================================================

Duplicate columns found:
['support_ticket_count_x', 'support_ticket_count_y']

Both columns identical: True

Final support features:
['avg_resolution_time_hours', 'max_resolution_time_hours', 'avg_first_response_minutes', 'avg_satisfaction_score', 'total_escalations', 'support_high_tickets', 'support_low_tickets', 'support_medium_tickets', 'support_urgent_tickets', 'support_ticket_count']

Customer analytics shape:
(500, 48)

✓ Duplicate support feature cleanup complete.

In [28]:


print("=" * 70)
print("REBUILDING CUSTOMER ANALYTICS CLEANLY")
print("=" * 70)

# ------------------------------------------------
# 1. Start from accounts — one row per customer
# ------------------------------------------------

accounts_df = datasets["accounts"].copy()

ACCOUNT_ID = "account_id"

customer_analytics = (
    accounts_df
    .drop_duplicates(subset=[ACCOUNT_ID])
    .copy()
)

print("\nBase customers:", len(customer_analytics))

# ------------------------------------------------
# 2. Subscription features
# ------------------------------------------------

subscriptions_df = datasets["subscriptions"].copy()

subscription_account_id = "account_id"

numeric_subscription_cols = (
    subscriptions_df
    .select_dtypes(include="number")
    .columns
    .tolist()
)

subscription_metric_cols = [
    col
    for col in numeric_subscription_cols
    if not (
        col.lower() == "id"
        or col.lower().endswith("_id")
    )
]

if subscription_metric_cols:

    subscription_features = (
        subscriptions_df
        .groupby(subscription_account_id)[
            subscription_metric_cols
        ]
        .agg(["sum", "mean", "min", "max"])
    )

    subscription_features.columns = [
        f"{col}_{stat}"
        for col, stat in subscription_features.columns
    ]

    subscription_features = (
        subscription_features
        .reset_index()
    )

    customer_analytics = customer_analytics.merge(
        subscription_features,
        on=ACCOUNT_ID,
        how="left"
    )

# Subscription count
subscription_count = (
    subscriptions_df
    .groupby(subscription_account_id)
    .size()
    .rename("subscription_count")
    .reset_index()
)

customer_analytics = customer_analytics.merge(
    subscription_count,
    on=ACCOUNT_ID,
    how="left"
)

# ------------------------------------------------
# 3. Feature usage features
# ------------------------------------------------

feature_usage_df = datasets["feature_usage"].copy()

# Map subscription → account
subscription_mapping = (
    subscriptions_df[
        ["subscription_id", "account_id"]
    ]
    .drop_duplicates()
)

usage_customer = feature_usage_df.merge(
    subscription_mapping,
    on="subscription_id",
    how="left"
)

usage_numeric_cols = (
    usage_customer
    .select_dtypes(include="number")
    .columns
    .tolist()
)

usage_numeric_cols = [
    col
    for col in usage_numeric_cols
    if not (
        col.lower() == "id"
        or col.lower().endswith("_id")
    )
]

if usage_numeric_cols:

    usage_features = (
        usage_customer
        .groupby(ACCOUNT_ID)[usage_numeric_cols]
        .agg(["sum", "mean", "max"])
    )

    usage_features.columns = [
        f"usage_{col}_{stat}"
        for col, stat in usage_features.columns
    ]

    usage_features = usage_features.reset_index()

    customer_analytics = customer_analytics.merge(
        usage_features,
        on=ACCOUNT_ID,
        how="left"
    )

# Usage records
usage_count = (
    usage_customer
    .groupby(ACCOUNT_ID)
    .size()
    .rename("usage_records")
    .reset_index()
)

customer_analytics = customer_analytics.merge(
    usage_count,
    on=ACCOUNT_ID,
    how="left"
)

# Distinct features
distinct_features = (
    usage_customer
    .groupby(ACCOUNT_ID)["feature_name"]
    .nunique()
    .rename("distinct_features_used")
    .reset_index()
)

customer_analytics = customer_analytics.merge(
    distinct_features,
    on=ACCOUNT_ID,
    how="left"
)

# Active usage days
usage_customer["usage_date"] = pd.to_datetime(
    usage_customer["usage_date"],
    errors="coerce"
)

active_days = (
    usage_customer
    .groupby(ACCOUNT_ID)["usage_date"]
    .nunique()
    .rename("active_usage_days")
    .reset_index()
)

customer_analytics = customer_analytics.merge(
    active_days,
    on=ACCOUNT_ID,
    how="left"
)

# Beta feature usage
usage_customer["beta_usage"] = (
    usage_customer["is_beta_feature"]
    .astype(int)
)

beta_usage = (
    usage_customer
    .groupby(ACCOUNT_ID)["beta_usage"]
    .sum()
    .rename("beta_feature_usage_count")
    .reset_index()
)

customer_analytics = customer_analytics.merge(
    beta_usage,
    on=ACCOUNT_ID,
    how="left"
)

# ------------------------------------------------
# 4. Support features
# ------------------------------------------------

support_df = datasets["support_tickets"].copy()

support_df["escalation_numeric"] = (
    support_df["escalation_flag"]
    .astype(int)
)

support_features = (
    support_df
    .groupby(ACCOUNT_ID)
    .agg(
        support_ticket_count=("ticket_id", "count"),
        avg_resolution_time_hours=(
            "resolution_time_hours",
            "mean"
        ),
        max_resolution_time_hours=(
            "resolution_time_hours",
            "max"
        ),
        avg_first_response_minutes=(
            "first_response_time_minutes",
            "mean"
        ),
        avg_satisfaction_score=(
            "satisfaction_score",
            "mean"
        ),
        total_escalations=(
            "escalation_numeric",
            "sum"
        )
    )
    .reset_index()
)

customer_analytics = customer_analytics.merge(
    support_features,
    on=ACCOUNT_ID,
    how="left"
)

# Priority counts
priority_counts = pd.crosstab(
    support_df[ACCOUNT_ID],
    support_df["priority"]
).reset_index()

priority_counts.columns = [
    ACCOUNT_ID
    if col == ACCOUNT_ID
    else f"support_{str(col).lower()}_tickets"
    for col in priority_counts.columns
]

customer_analytics = customer_analytics.merge(
    priority_counts,
    on=ACCOUNT_ID,
    how="left"
)

# ------------------------------------------------
# 5. Churn features
# ------------------------------------------------

churn_df = datasets["churn_events"].copy()

churn_features = (
    churn_df
    .groupby(ACCOUNT_ID)
    .agg(
        churn_event_count=("churn_event_id", "count"),
        reactivation_count=(
            "is_reactivation",
            "sum"
        ),
        preceding_upgrade_count=(
            "preceding_upgrade_flag",
            "sum"
        ),
        preceding_downgrade_count=(
            "preceding_downgrade_flag",
            "sum"
        )
    )
    .reset_index()
)

churn_features["historical_churn_flag"] = 1

customer_analytics = customer_analytics.merge(
    churn_features,
    on=ACCOUNT_ID,
    how="left"
)

# ------------------------------------------------
# 6. Fill feature-engineering missing values
# ------------------------------------------------

engineered_columns = [
    col
    for col in customer_analytics.columns
    if col != ACCOUNT_ID
]

for col in engineered_columns:

    if pd.api.types.is_numeric_dtype(
        customer_analytics[col]
    ):
        customer_analytics[col] = (
            customer_analytics[col]
            .fillna(0)
        )

# ------------------------------------------------
# 7. Convert churn flag to integer
# ------------------------------------------------

customer_analytics["historical_churn_flag"] = (
    customer_analytics[
        "historical_churn_flag"
    ]
    .astype(int)
)

# ------------------------------------------------
# 8. Remove accidental duplicate column names
# ------------------------------------------------

customer_analytics = (
    customer_analytics
    .loc[
        :,
        ~customer_analytics.columns.duplicated()
    ]
)

# ------------------------------------------------
# 9. Final validation
# ------------------------------------------------

print("\n" + "=" * 70)
print("FINAL CUSTOMER ANALYTICS DATASET")
print("=" * 70)

print("\nRows:", customer_analytics.shape[0])
print("Columns:", customer_analytics.shape[1])

print(
    "\nUnique accounts:",
    customer_analytics[ACCOUNT_ID].nunique()
)

print(
    "One row per account:",
    customer_analytics[ACCOUNT_ID].is_unique
)

print("\nChurn distribution:")

display(
    customer_analytics[
        "historical_churn_flag"
    ].value_counts()
)

print("\nDuplicate column names:")
print(
    customer_analytics.columns[
        customer_analytics.columns.duplicated()
    ].tolist()
)

print("\nFirst 5 rows:")
display(customer_analytics.head())

print(
    "\n✓ Customer analytics rebuilt cleanly."
)

======================================================================
REBUILDING CUSTOMER ANALYTICS CLEANLY
======================================================================

Base customers: 500

======================================================================
FINAL CUSTOMER ANALYTICS DATASET
======================================================================

Rows: 500
Columns: 51

Unique accounts: 500
One row per account: True

Churn distribution:

historical_churn_flag
1    352
0    148
Name: count, dtype: int64

Duplicate column names:
[]

First 5 rows:

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,seats_sum,seats_mean,seats_min,seats_max,mrr_amount_sum,mrr_amount_mean,mrr_amount_min,mrr_amount_max,arr_amount_sum,arr_amount_mean,arr_amount_min,arr_amount_max,subscription_count,usage_usage_count_sum,usage_usage_count_mean,usage_usage_count_max,usage_usage_duration_secs_sum,usage_usage_duration_secs_mean,usage_usage_duration_secs_max,usage_error_count_sum,usage_error_count_mean,usage_error_count_max,usage_records,distinct_features_used,active_usage_days,beta_feature_usage_count,support_ticket_count,avg_resolution_time_hours,max_resolution_time_hours,avg_first_response_minutes,avg_satisfaction_score,total_escalations,support_high_tickets,support_low_tickets,support_medium_tickets,support_urgent_tickets,churn_event_count,reactivation_count,preceding_upgrade_count,preceding_downgrade_count,historical_churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,312,31.200000,9,102,12603,1260.300000,0,5771,151236,15123.600000,0,69252,10,535,9.727273,15,152339,2769.800000,7728,38,0.690909,5,55,27,55,4,2.0,23.000000,27.0,91.000000,3.000000,0.0,1.0,0.0,0.0,1.0,2.0,0.0,1.0,0.0,1
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,176,22.000000,18,28,10004,1250.500000,342,5572,120048,15006.000000,4104,66864,8,355,10.142857,19,101136,2889.600000,6228,14,0.400000,3,35,23,35,2,3.0,38.000000,64.0,73.333333,4.000000,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,282,18.800000,1,60,18286,1219.066667,0,5771,219432,14628.800000,0,69252,15,821,9.891566,17,251210,3026.626506,7504,48,0.578313,3,83,34,80,5,3.0,43.666667,65.0,63.666667,4.666667,0.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,1.0,1
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,209,29.857143,24,47,9275,1325.000000,0,4776,111300,15900.000000,0,57312,7,382,9.317073,15,102528,2500.682927,6090,21,0.512195,3,41,26,40,5,2.0,29.000000,44.0,174.000000,0.000000,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,424,47.111111,35,109,48761,5417.888889,0,21691,585132,65014.666667,0,260292,9,579,9.982759,17,215779,3720.327586,9452,31,0.534483,3,58,32,56,4,7.0,42.285714,69.0,107.857143,3.800000,1.0,2.0,0.0,3.0,2.0,1.0,0.0,1.0,0.0,1

✓ Customer analytics rebuilt cleanly.

In [29]:


print("=" * 70)
print("CUSTOMER ANALYTICS — FEATURE & DATA QUALITY AUDIT")
print("=" * 70)

# ------------------------------------------------
# 1. Dataset overview
# ------------------------------------------------

print("\n1. DATASET OVERVIEW")
print("-" * 70)

print("Rows:", customer_analytics.shape[0])
print("Columns:", customer_analytics.shape[1])
print(
    "Unique accounts:",
    customer_analytics[ACCOUNT_ID].nunique()
)
print(
    "One row per account:",
    customer_analytics[ACCOUNT_ID].is_unique
)

# ------------------------------------------------
# 2. Column inventory
# ------------------------------------------------

print("\n2. COLUMN INVENTORY")
print("-" * 70)

column_inventory = pd.DataFrame({
    "column": customer_analytics.columns,
    "dtype": customer_analytics.dtypes.astype(str),
    "missing_count": customer_analytics.isna().sum().values,
    "missing_pct": (
        customer_analytics.isna().mean().values * 100
    ).round(2),
    "unique_values": [
        customer_analytics[col].nunique()
        for col in customer_analytics.columns
    ]
})

display(column_inventory)

# ------------------------------------------------
# 3. Duplicate rows
# ------------------------------------------------

print("\n3. DUPLICATE ROW CHECK")
print("-" * 70)

duplicate_rows = customer_analytics.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

# ------------------------------------------------
# 4. Missing-value audit
# ------------------------------------------------

print("\n4. MISSING VALUE AUDIT")
print("-" * 70)

missing_audit = (
    customer_analytics
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_audit = missing_audit[
    missing_audit > 0
]

if len(missing_audit) > 0:

    missing_table = pd.DataFrame({
        "missing_count": missing_audit,
        "missing_pct": (
            missing_audit /
            len(customer_analytics) *
            100
        ).round(2)
    })

    display(missing_table)

else:

    print("✓ No missing values found.")

# ------------------------------------------------
# 5. Constant / near-constant features
# ------------------------------------------------

print("\n5. CONSTANT FEATURE CHECK")
print("-" * 70)

constant_features = [
    col
    for col in customer_analytics.columns
    if customer_analytics[col].nunique(dropna=False) <= 1
]

print("Constant features:")
print(constant_features)

# ------------------------------------------------
# 6. Numeric feature summary
# ------------------------------------------------

print("\n6. NUMERIC FEATURE SUMMARY")
print("-" * 70)

numeric_features = (
    customer_analytics
    .select_dtypes(include="number")
    .columns
    .tolist()
)

print("Numeric features:", len(numeric_features))

display(
    customer_analytics[
        numeric_features
    ]
    .describe()
    .T
)

# ------------------------------------------------
# 7. Categorical feature summary
# ------------------------------------------------

print("\n7. CATEGORICAL FEATURE SUMMARY")
print("-" * 70)

categorical_features = (
    customer_analytics
    .select_dtypes(
        include=["object", "string", "category", "bool"]
    )
    .columns
    .tolist()
)

print("Categorical features:", len(categorical_features))

for col in categorical_features:

    print(f"\n--- {col} ---")

    print(
        customer_analytics[col]
        .value_counts(dropna=False)
        .head(10)
    )

# ------------------------------------------------
# 8. Potential leakage features
# ------------------------------------------------

print("\n8. POTENTIAL ML LEAKAGE FEATURES")
print("-" * 70)

leakage_keywords = [
    "churn",
    "feedback",
    "reason",
    "cancel",
    "termination",
    "churn_date"
]

potential_leakage = [
    col
    for col in customer_analytics.columns
    if any(
        keyword in col.lower()
        for keyword in leakage_keywords
    )
]

print("Potential leakage columns:")
print(potential_leakage)

# ------------------------------------------------
# 9. ID-like columns
# ------------------------------------------------

print("\n9. ID-LIKE COLUMN CHECK")
print("-" * 70)

id_like_columns = [
    col
    for col in customer_analytics.columns
    if (
        col.lower() == "id"
        or col.lower().endswith("_id")
        or "uuid" in col.lower()
    )
]

print("ID-like columns:")
print(id_like_columns)

# ------------------------------------------------
# 10. Final feature groups
# ------------------------------------------------

print("\n10. FEATURE GROUPS")
print("-" * 70)

revenue_features = [
    col
    for col in customer_analytics.columns
    if any(
        keyword in col.lower()
        for keyword in [
            "mrr",
            "arr",
            "revenue",
            "price",
            "amount",
            "billing",
            "cost"
        ]
    )
]

usage_features = [
    col
    for col in customer_analytics.columns
    if (
        col.startswith("usage_")
        or col in [
            "usage_records",
            "distinct_features_used",
            "active_usage_days",
            "beta_feature_usage_count"
        ]
    )
]

support_features = [
    col
    for col in customer_analytics.columns
    if (
        col.startswith("support_")
        or col in [
            "avg_resolution_time_hours",
            "max_resolution_time_hours",
            "avg_first_response_minutes",
            "avg_satisfaction_score",
            "total_escalations"
        ]
    )
]

churn_features = [
    col
    for col in customer_analytics.columns
    if (
        "churn" in col.lower()
        or "reactivation" in col.lower()
        or "preceding_" in col.lower()
    )
]

print("\nRevenue features:")
print(revenue_features)

print("\nUsage features:")
print(usage_features)

print("\nSupport features:")
print(support_features)

print("\nChurn features:")
print(churn_features)

# ------------------------------------------------
# 11. Final audit status
# ------------------------------------------------

print("\n" + "=" * 70)
print("AUDIT COMPLETE")
print("=" * 70)

print(
    f"\n✓ Customer-level dataset contains "
    f"{customer_analytics.shape[0]} customers "
    f"and {customer_analytics.shape[1]} features."
)

print(
    "✓ One row per customer:",
    customer_analytics[ACCOUNT_ID].is_unique
)

print(
    "✓ Duplicate rows:",
    duplicate_rows
)

print(
    "✓ Potential leakage columns identified:",
    len(potential_leakage)
)

======================================================================
CUSTOMER ANALYTICS — FEATURE & DATA QUALITY AUDIT
======================================================================

1. DATASET OVERVIEW
----------------------------------------------------------------------
Rows: 500
Columns: 51
Unique accounts: 500
One row per account: True

2. COLUMN INVENTORY
----------------------------------------------------------------------

,column,dtype,missing_count,missing_pct,unique_values
account_id,account_id,str,0,0.0,500
account_name,account_name,str,0,0.0,500
industry,industry,str,0,0.0,5
country,country,str,0,0.0,7
signup_date,signup_date,str,0,0.0,370
referral_source,referral_source,str,0,0.0,5
plan_tier,plan_tier,str,0,0.0,3
seats,seats,int64,0,0.0,73
is_trial,is_trial,bool,0,0.0,2
churn_flag,churn_flag,bool,0,0.0,2
seats_sum,seats_sum,int64,0,0.0,323
seats_mean,seats_mean,float64,0,0.0,413
seats_min,seats_min,int64,0,0.0,73
seats_max,seats_max,int64,0,0.0,109
mrr_amount_sum,mrr_amount_sum,int64,0,0.0,496
mrr_amount_mean,mrr_amount_mean,float64,0,0.0,497
mrr_amount_min,mrr_amount_min,int64,0,0.0,51
mrr_amount_max,mrr_amount_max,int64,0,0.0,148
arr_amount_sum,arr_amount_sum,int64,0,0.0,496
arr_amount_mean,arr_amount_mean,float64,0,0.0,497
arr_amount_min,arr_amount_min,int64,0,0.0,51
arr_amount_max,arr_amount_max,int64,0,0.0,148
subscription_count,subscription_count,int64,0,0.0,18
usage_usage_count_sum,usage_usage_count_sum,int64,0,0.0,355
usage_usage_count_mean,usage_usage_count_mean,float64,0,0.0,421
usage_usage_count_max,usage_usage_count_max,int64,0,0.0,15
usage_usage_duration_secs_sum,usage_usage_duration_secs_sum,int64,0,0.0,500
usage_usage_duration_secs_mean,usage_usage_duration_secs_mean,float64,0,0.0,500
usage_usage_duration_secs_max,usage_usage_duration_secs_max,int64,0,0.0,388
usage_error_count_sum,usage_error_count_sum,int64,0,0.0,61
usage_error_count_mean,usage_error_count_mean,float64,0,0.0,339
usage_error_count_max,usage_error_count_max,int64,0,0.0,9
usage_records,usage_records,int64,0,0.0,81
distinct_features_used,distinct_features_used,int64,0,0.0,29
active_usage_days,active_usage_days,int64,0,0.0,77
beta_feature_usage_count,beta_feature_usage_count,int64,0,0.0,16
support_ticket_count,support_ticket_count,float64,0,0.0,12
avg_resolution_time_hours,avg_resolution_time_hours,float64,0,0.0,297
max_resolution_time_hours,max_resolution_time_hours,float64,0,0.0,58
avg_first_response_minutes,avg_first_response_minutes,float64,0,0.0,382
avg_satisfaction_score,avg_satisfaction_score,float64,0,0.0,26
total_escalations,total_escalations,float64,0,0.0,4
support_high_tickets,support_high_tickets,float64,0,0.0,6
support_low_tickets,support_low_tickets,float64,0,0.0,6
support_medium_tickets,support_medium_tickets,float64,0,0.0,5
support_urgent_tickets,support_urgent_tickets,float64,0,0.0,7
churn_event_count,churn_event_count,float64,0,0.0,6
reactivation_count,reactivation_count,float64,0,0.0,3
preceding_upgrade_count,preceding_upgrade_count,float64,0,0.0,3
preceding_downgrade_count,preceding_downgrade_count,float64,0,0.0,3
historical_churn_flag,historical_churn_flag,int64,0,0.0,2

3. DUPLICATE ROW CHECK
----------------------------------------------------------------------
Duplicate rows: 0

4. MISSING VALUE AUDIT
----------------------------------------------------------------------
✓ No missing values found.

5. CONSTANT FEATURE CHECK
----------------------------------------------------------------------
Constant features:
[]

6. NUMERIC FEATURE SUMMARY
----------------------------------------------------------------------
Numeric features: 42

,count,mean,std,min,25%,50%,75%,max
seats,500.0,20.560000,21.044718,1.000000,5.000000,15.000000,28.000000,1.630000e+02
seats_sum,500.0,298.520000,196.844113,18.000000,173.000000,257.000000,367.000000,1.628000e+03
seats_mean,500.0,29.987320,17.478452,4.500000,19.796875,25.572727,33.750000,1.630000e+02
seats_min,500.0,20.726000,20.922965,1.000000,6.000000,15.000000,28.000000,1.630000e+02
seats_max,500.0,59.342000,26.959203,9.000000,41.000000,55.000000,72.000000,1.890000e+02
mrr_amount_sum,500.0,22677.494000,17294.852405,190.000000,11884.250000,18833.500000,28874.750000,1.380600e+05
mrr_amount_mean,500.0,2264.176843,1600.412647,95.000000,1259.450000,1923.145833,2744.294643,1.380600e+04
mrr_amount_min,500.0,89.342000,269.151225,0.000000,0.000000,0.000000,0.000000,2.223000e+03
mrr_amount_max,500.0,7699.980000,4952.732971,190.000000,4378.000000,6567.000000,9950.000000,3.383000e+04
arr_amount_sum,500.0,272129.928000,207538.228865,2280.000000,142611.000000,226002.000000,346497.000000,1.656720e+06
arr_amount_mean,500.0,27170.122121,19204.951766,1140.000000,15113.400000,23077.750000,32931.535714,1.656720e+05
arr_amount_min,500.0,1072.104000,3229.814697,0.000000,0.000000,0.000000,0.000000,2.667600e+04
arr_amount_max,500.0,92399.760000,59432.795654,2280.000000,52536.000000,78804.000000,119400.000000,4.059600e+05
subscription_count,500.0,10.000000,3.271300,2.000000,7.000000,10.000000,12.000000,1.900000e+01
usage_usage_count_sum,500.0,501.050000,173.818910,92.000000,373.000000,498.500000,619.250000,1.053000e+03
usage_usage_count_mean,500.0,10.019730,0.464163,8.090909,9.723404,10.021981,10.308042,1.155556e+01
usage_usage_count_max,500.0,17.680000,2.040079,12.000000,16.000000,17.000000,19.000000,2.600000e+01
usage_usage_duration_secs_sum,500.0,152110.144000,52554.213752,23149.000000,115308.750000,150308.500000,187268.500000,3.262830e+05
usage_usage_duration_secs_mean,500.0,3056.326634,320.061576,1543.266667,2852.023810,3033.168615,3235.928744,4.199722e+03
usage_usage_duration_secs_max,500.0,8286.394000,1294.165366,3852.000000,7440.000000,8148.000000,8944.000000,1.269600e+04
usage_error_count_sum,500.0,28.214000,12.101284,0.000000,19.000000,28.000000,36.000000,7.600000e+01
usage_error_count_mean,500.0,0.564014,0.153814,0.000000,0.460317,0.543706,0.666667,1.062500e+00
usage_error_count_max,500.0,3.928000,0.986287,0.000000,3.000000,4.000000,4.000000,8.000000e+00
usage_records,500.0,50.000000,17.188685,10.000000,38.000000,50.000000,62.000000,1.010000e+02
distinct_features_used,500.0,27.616000,5.658673,9.000000,24.000000,28.000000,32.000000,4.000000e+01
active_usage_days,500.0,48.222000,16.197699,10.000000,36.750000,48.000000,59.000000,9.600000e+01
beta_feature_usage_count,500.0,5.088000,2.733349,0.000000,3.000000,5.000000,7.000000,1.500000e+01
support_ticket_count,500.0,4.000000,1.892925,0.000000,3.000000,4.000000,5.000000,1.100000e+01
avg_resolution_time_hours,500.0,35.658699,12.580350,0.000000,28.666667,35.633333,43.000000,7.200000e+01
max_resolution_time_hours,500.0,55.556000,15.850215,0.000000,50.000000,60.000000,67.000000,7.200000e+01
avg_first_response_minutes,500.0,87.143132,29.865968,0.000000,69.964286,87.900000,105.850000,1.750000e+02
avg_satisfaction_score,500.0,3.694600,1.140672,0.000000,3.500000,4.000000,4.333333,5.000000e+00
total_escalations,500.0,0.190000,0.417431,0.000000,0.000000,0.000000,0.000000,3.000000e+00
support_high_tickets,500.0,1.020000,0.972364,0.000000,0.000000,1.000000,2.000000,5.000000e+00
support_low_tickets,500.0,0.970000,0.993516,0.000000,0.000000,1.000000,2.000000,5.000000e+00
support_medium_tickets,500.0,0.982000,0.971372,0.000000,0.000000,1.000000,2.000000,4.000000e+00
support_urgent_tickets,500.0,1.028000,1.037965,0.000000,0.000000,1.000000,2.000000,6.000000e+00
churn_event_count,500.0,1.200000,1.053670,0.000000,0.000000,1.000000,2.000000,5.000000e+00
reactivation_count,500.0,0.122000,0.362462,0.000000,0.000000,0.000000,0.000000,2.000000e+00
preceding_upgrade_count,500.0,0.246000,0.495960,0.000000,0.000000,0.000000,0.000000,2.000000e+00
preceding_downgrade_count,500.0,0.106000,0.333146,0.000000,0.000000,0.000000,0.000000,2.000000e+00
historical_churn_flag,500.0,0.704000,0.456948,0.000000,0.000000,1.000000,1.000000,1.000000e+00

7. CATEGORICAL FEATURE SUMMARY
----------------------------------------------------------------------
Categorical features: 9

--- account_id ---
account_id
A-2e4581    1
A-43a9e3    1
A-0a282f    1
A-1f0ac7    1
A-ce550d    1
A-1b9609    1
A-a0ca4e    1
A-e5d6ab    1
A-7dacce    1
A-10b8da    1
Name: count, dtype: int64

--- account_name ---
account_name
Company_0    1
Company_1    1
Company_2    1
Company_3    1
Company_4    1
Company_5    1
Company_6    1
Company_7    1
Company_8    1
Company_9    1
Name: count, dtype: int64

--- industry ---
industry
DevTools         113
FinTech          112
Cybersecurity    100
HealthTech        96
EdTech            79
Name: count, dtype: int64

--- country ---
country
US    291
UK     58
IN     49
AU     32
DE     25
CA     23
FR     22
Name: count, dtype: int64

--- signup_date ---
signup_date
2024-10-27    4
2024-10-22    4
2024-10-16    3
2023-09-08    3
2024-08-20    3
2024-05-20    3
2024-12-07    3
2024-07-06    3
2024-10-31    3
2024-03-28    3
Name: count, dtype: int64

--- referral_source ---
referral_source
organic    114
other      103
ads         98
event       96
partner     89
Name: count, dtype: int64

--- plan_tier ---
plan_tier
Pro           178
Basic         168
Enterprise    154
Name: count, dtype: int64

--- is_trial ---
is_trial
False    403
True      97
Name: count, dtype: int64

--- churn_flag ---
churn_flag
False    390
True     110
Name: count, dtype: int64

8. POTENTIAL ML LEAKAGE FEATURES
----------------------------------------------------------------------
Potential leakage columns:
['churn_flag', 'churn_event_count', 'historical_churn_flag']

9. ID-LIKE COLUMN CHECK
----------------------------------------------------------------------
ID-like columns:
['account_id']

10. FEATURE GROUPS
----------------------------------------------------------------------

Revenue features:
['mrr_amount_sum', 'mrr_amount_mean', 'mrr_amount_min', 'mrr_amount_max', 'arr_amount_sum', 'arr_amount_mean', 'arr_amount_min', 'arr_amount_max']

Usage features:
['usage_usage_count_sum', 'usage_usage_count_mean', 'usage_usage_count_max', 'usage_usage_duration_secs_sum', 'usage_usage_duration_secs_mean', 'usage_usage_duration_secs_max', 'usage_error_count_sum', 'usage_error_count_mean', 'usage_error_count_max', 'usage_records', 'distinct_features_used', 'active_usage_days', 'beta_feature_usage_count']

Support features:
['support_ticket_count', 'avg_resolution_time_hours', 'max_resolution_time_hours', 'avg_first_response_minutes', 'avg_satisfaction_score', 'total_escalations', 'support_high_tickets', 'support_low_tickets', 'support_medium_tickets', 'support_urgent_tickets']

Churn features:
['churn_flag', 'churn_event_count', 'reactivation_count', 'preceding_upgrade_count', 'preceding_downgrade_count', 'historical_churn_flag']

======================================================================
AUDIT COMPLETE
======================================================================

✓ Customer-level dataset contains 500 customers and 51 features.
✓ One row per customer: True
✓ Duplicate rows: 0
✓ Potential leakage columns identified: 3

In [30]:


print("=" * 70)
print("SAAS BUSINESS — CORE KPIs")
print("=" * 70)

# Basic customer metrics
total_customers = customer_analytics[ACCOUNT_ID].nunique()

# Subscription metrics
subscription_count = customer_analytics["subscription_count"].sum()

# Revenue metrics
mrr_cols = [col for col in customer_analytics.columns if col.lower() == "mrr"]

arr_cols = [col for col in customer_analytics.columns if col.lower() == "arr"]

if mrr_cols:
    total_mrr = customer_analytics[mrr_cols[0]].sum()
    avg_mrr = customer_analytics[mrr_cols[0]].mean()
else:
    total_mrr = np.nan
    avg_mrr = np.nan

if arr_cols:
    total_arr = customer_analytics[arr_cols[0]].sum()
    avg_arr = customer_analytics[arr_cols[0]].mean()
else:
    total_arr = np.nan
    avg_arr = np.nan

# Churn metrics
churned_customers = customer_analytics["historical_churn_flag"].sum()

churn_rate = (
    churned_customers / total_customers * 100
    if total_customers > 0 else np.nan
)

# Usage metrics
total_usage_records = customer_analytics["usage_records"].sum()

avg_usage_records = customer_analytics["usage_records"].mean()

# Support metrics
total_tickets = customer_analytics["support_ticket_count"].sum()

avg_tickets_per_customer = (
    customer_analytics["support_ticket_count"].mean()
)

# Display KPI table
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Customers",
        "Total Subscriptions",
        "Total MRR",
        "Average MRR per Customer",
        "Total ARR",
        "Average ARR per Customer",
        "Customers with Historical Churn",
        "Historical Churn Rate (%)",
        "Total Usage Records",
        "Average Usage Records per Customer",
        "Total Support Tickets",
        "Average Tickets per Customer"
    ],
    "Value": [
        total_customers,
        subscription_count,
        total_mrr,
        avg_mrr,
        total_arr,
        avg_arr,
        churned_customers,
        churn_rate,
        total_usage_records,
        avg_usage_records,
        total_tickets,
        avg_tickets_per_customer
    ]
})

display(kpi_summary)

print("\n✓ Core SaaS KPIs calculated.")

======================================================================
SAAS BUSINESS — CORE KPIs
======================================================================

                                   KPI    Value
0                      Total Customers    500.0
1                  Total Subscriptions   5000.0
2                            Total MRR      NaN
3             Average MRR per Customer      NaN
4                            Total ARR      NaN
5             Average ARR per Customer      NaN
6      Customers with Historical Churn    352.0
7            Historical Churn Rate (%)     70.4
8                  Total Usage Records  25000.0
9   Average Usage Records per Customer     50.0
10               Total Support Tickets   2000.0
11        Average Tickets per Customer      4.0

✓ Core SaaS KPIs calculated.

In [31]:


print("=" * 70)
print("CUSTOMER SEGMENTATION ANALYSIS")
print("=" * 70)

# Identify useful segmentation columns
segment_candidates = [
    col for col in customer_analytics.columns
    if any(keyword in col.lower() for keyword in [
        "segment",
        "industry",
        "plan",
        "tier",
        "company_size",
        "region",
        "country",
        "customer_type"
    ])
]

print("\nPotential segmentation columns:")
print(segment_candidates)

# Automatically select commonly useful columns
selected_segments = []

for col in [
    "segment",
    "industry",
    "plan",
    "plan_type",
    "subscription_type",
    "company_size",
    "region",
    "country"
]:
    if col in customer_analytics.columns:
        selected_segments.append(col)

print("\nSelected segmentation columns:")
print(selected_segments)

# Revenue column
revenue_col = None

for col in customer_analytics.columns:
    if col.lower() == "mrr":
        revenue_col = col
        break

if revenue_col is None:
    for col in customer_analytics.columns:
        if "mrr" in col.lower() and "mean" not in col.lower():
            revenue_col = col
            break

print("\nRevenue metric used:", revenue_col)

# Analyze each segment
for segment_col in selected_segments:

    print("\n" + "=" * 70)
    print(f"SEGMENT: {segment_col}")
    print("=" * 70)

    if revenue_col:
        segment_analysis = (
            customer_analytics
            .groupby(segment_col, dropna=False)
            .agg(
                customers=(ACCOUNT_ID, "nunique"),
                total_mrr=(revenue_col, "sum"),
                average_mrr=(revenue_col, "mean"),
                avg_usage=("usage_records", "mean"),
                avg_support_tickets=("support_ticket_count", "mean"),
                churned_customers=("historical_churn_flag", "sum")
            )
            .reset_index()
        )
    else:
        segment_analysis = (
            customer_analytics
            .groupby(segment_col, dropna=False)
            .agg(
                customers=(ACCOUNT_ID, "nunique"),
                avg_usage=("usage_records", "mean"),
                avg_support_tickets=("support_ticket_count", "mean"),
                churned_customers=("historical_churn_flag", "sum")
            )
            .reset_index()
        )

    segment_analysis["churn_rate_pct"] = (
        segment_analysis["churned_customers"]
        / segment_analysis["customers"]
        * 100
    ).round(2)

    display(segment_analysis.sort_values(
        "customers",
        ascending=False
    ))

print("\n✓ Customer segmentation analysis completed.")

======================================================================
CUSTOMER SEGMENTATION ANALYSIS
======================================================================

Potential segmentation columns:
['industry', 'country', 'plan_tier']

Selected segmentation columns:
['industry', 'country']

Revenue metric used: mrr_amount_sum

======================================================================
SEGMENT: industry
======================================================================

,industry,customers,total_mrr,average_mrr,avg_usage,avg_support_tickets,churned_customers,churn_rate_pct
1,DevTools,113,2403654,21271.274336,50.849558,3.761062,83,73.45
3,FinTech,112,2669496,23834.785714,49.500000,4.080357,76,67.86
0,Cybersecurity,100,2253318,22533.180000,50.250000,3.940000,72,72.00
4,HealthTech,96,1969112,20511.583333,48.843750,4.250000,64,66.67
2,EdTech,79,2043167,25862.873418,50.582278,4.000000,57,72.15

======================================================================
SEGMENT: country
======================================================================

,country,customers,total_mrr,average_mrr,avg_usage,avg_support_tickets,churned_customers,churn_rate_pct
6,US,291,6634595,22799.295533,50.872852,4.048110,206,70.79
5,UK,58,1220471,21042.603448,49.086207,3.568966,45,77.59
4,IN,49,1194325,24373.979592,51.653061,4.387755,33,67.35
0,AU,32,839980,26249.375000,48.968750,3.562500,22,68.75
2,DE,25,382018,15280.720000,42.360000,3.840000,14,56.00
1,CA,23,477562,20763.565217,48.173913,4.000000,16,69.57
3,FR,22,589796,26808.909091,49.272727,4.454545,16,72.73

✓ Customer segmentation analysis completed.

In [32]:


print("=" * 70)
print("PRODUCT & FEATURE USAGE ANALYSIS")
print("=" * 70)

# Work from the original feature usage data
usage_df = feature_usage.copy()

# Basic usage KPIs
print("\n1. USAGE OVERVIEW")
print("-" * 70)

print("Total usage records:", len(usage_df))
print("Unique subscriptions:", usage_df["subscription_id"].nunique())
print("Unique features:", usage_df["feature_name"].nunique())
print("Usage date range:",
      usage_df["usage_date"].min(),
      "to",
      usage_df["usage_date"].max())

# 2. Feature-level performance
print("\n2. FEATURE USAGE")
print("-" * 70)

feature_analysis = (
    usage_df
    .groupby("feature_name")
    .agg(
        usage_records=("usage_id", "count"),
        total_usage_count=("usage_count", "sum"),
        avg_usage_count=("usage_count", "mean"),
        total_duration_secs=("usage_duration_secs", "sum"),
        avg_duration_secs=("usage_duration_secs", "mean"),
        total_errors=("error_count", "sum"),
        beta_usage_records=("is_beta_feature", "sum")
    )
    .reset_index()
)

feature_analysis["error_rate_pct"] = (
    feature_analysis["total_errors"]
    / feature_analysis["usage_records"]
    * 100
).round(2)

feature_analysis["beta_usage_pct"] = (
    feature_analysis["beta_usage_records"]
    / feature_analysis["usage_records"]
    * 100
).round(2)

# Sort by total usage
feature_analysis = feature_analysis.sort_values(
    "total_usage_count",
    ascending=False
)

display(feature_analysis)

# 3. Top features
print("\n3. TOP 10 FEATURES BY USAGE")
print("-" * 70)

display(
    feature_analysis[
        [
            "feature_name",
            "total_usage_count",
            "usage_records",
            "avg_usage_count",
            "error_rate_pct"
        ]
    ].head(10)
)

# 4. Least-used features
print("\n4. LEAST USED FEATURES")
print("-" * 70)

display(
    feature_analysis[
        [
            "feature_name",
            "total_usage_count",
            "usage_records",
            "avg_usage_count",
            "error_rate_pct"
        ]
    ].tail(10).sort_values("total_usage_count")
)

# 5. Beta vs non-beta usage
print("\n5. BETA FEATURE ADOPTION")
print("-" * 70)

beta_analysis = (
    usage_df
    .groupby("is_beta_feature")
    .agg(
        usage_records=("usage_id", "count"),
        unique_subscriptions=("subscription_id", "nunique"),
        total_usage_count=("usage_count", "sum"),
        avg_usage_count=("usage_count", "mean"),
        total_errors=("error_count", "sum")
    )
    .reset_index()
)

beta_analysis["error_rate_pct"] = (
    beta_analysis["total_errors"]
    / beta_analysis["usage_records"]
    * 100
).round(2)

display(beta_analysis)

print("\n✓ Product and feature usage analysis completed.")

======================================================================
PRODUCT & FEATURE USAGE ANALYSIS
======================================================================

1. USAGE OVERVIEW
----------------------------------------------------------------------
Total usage records: 25000
Unique subscriptions: 4967
Unique features: 40
Usage date range: 2023-01-01 to 2024-12-31

2. FEATURE USAGE
----------------------------------------------------------------------

,feature_name,usage_records,total_usage_count,avg_usage_count,total_duration_secs,avg_duration_secs,total_errors,beta_usage_records,error_rate_pct,beta_usage_pct
25,feature_32,659,6686,10.145675,2052316,3114.288316,357,67,54.17,10.17
6,feature_15,640,6621,10.345313,1966988,3073.418750,349,74,54.53,11.56
36,feature_6,655,6546,9.993893,2013972,3074.766412,339,71,51.76,10.84
12,feature_20,643,6541,10.172628,1947193,3028.293935,308,62,47.90,9.64
27,feature_34,650,6536,10.055385,2006721,3087.263077,397,67,61.08,10.31
3,feature_12,659,6534,9.915023,2061481,3128.195751,359,65,54.48,9.86
2,feature_11,643,6533,10.160187,2012779,3130.293935,352,60,54.74,9.33
11,feature_2,642,6525,10.163551,1935694,3015.099688,401,69,62.46,10.75
31,feature_38,643,6478,10.074650,1942257,3020.617418,356,73,55.37,11.35
18,feature_26,649,6470,9.969183,1976377,3045.265023,417,63,64.25,9.71
8,feature_17,651,6458,9.920123,1950827,2996.662058,369,60,56.68,9.22
32,feature_39,631,6430,10.190174,1945263,3082.825674,357,56,56.58,8.87
24,feature_31,644,6425,9.976708,1834473,2848.560559,335,62,52.02,9.63
29,feature_36,648,6389,9.859568,1874832,2893.259259,371,63,57.25,9.72
16,feature_24,643,6388,9.934681,2070250,3219.673406,349,69,54.28,10.73
1,feature_10,634,6384,10.069401,1873423,2954.925868,348,52,54.89,8.20
30,feature_37,636,6380,10.031447,1939656,3049.773585,306,66,48.11,10.38
33,feature_4,625,6374,10.198400,1968622,3149.795200,418,77,66.88,12.32
14,feature_22,636,6366,10.009434,1890956,2973.201258,343,71,53.93,11.16
0,feature_1,629,6364,10.117647,1836835,2920.246423,336,71,53.42,11.29
21,feature_29,640,6362,9.940625,1919259,2998.842187,371,64,57.97,10.00
23,feature_30,629,6309,10.030207,1893467,3010.281399,362,62,57.55,9.86
26,feature_33,635,6274,9.880315,1963278,3091.776378,336,63,52.91,9.92
7,feature_16,622,6273,10.085209,1952509,3139.081994,396,44,63.67,7.07
19,feature_27,611,6231,10.198036,1956868,3202.729951,362,62,59.25,10.15
34,feature_40,621,6222,10.019324,1931204,3109.829308,380,79,61.19,12.72
20,feature_28,623,6213,9.972713,1905657,3058.839486,361,54,57.95,8.67
39,feature_9,624,6207,9.947115,1876451,3007.133013,404,70,64.74,11.22
37,feature_7,619,6113,9.875606,1886544,3047.728595,311,59,50.24,9.53
4,feature_13,612,6099,9.965686,1812995,2962.410131,372,74,60.78,12.09
17,feature_25,615,6091,9.904065,1846029,3001.673171,344,52,55.93,8.46
38,feature_8,596,6030,10.117450,1877700,3150.503356,284,63,47.65,10.57
13,feature_21,591,5950,10.067682,1818658,3077.255499,349,59,59.05,9.98
22,feature_3,598,5917,9.894649,1786307,2987.135452,345,66,57.69,11.04
10,feature_19,589,5900,10.016978,1783390,3027.826825,352,57,59.76,9.68
5,feature_14,600,5880,9.800000,1793394,2988.990000,307,62,51.17,10.33
9,feature_18,588,5850,9.948980,1760936,2994.789116,369,61,62.76,10.37
28,feature_35,587,5816,9.908007,1733394,2952.971039,313,67,53.32,11.41
35,feature_5,577,5759,9.980936,1778264,3081.913345,316,53,54.77,9.19
15,feature_23,563,5601,9.948490,1677853,2980.200710,306,55,54.35,9.77

3. TOP 10 FEATURES BY USAGE
----------------------------------------------------------------------

,feature_name,total_usage_count,usage_records,avg_usage_count,error_rate_pct
25,feature_32,6686,659,10.145675,54.17
6,feature_15,6621,640,10.345313,54.53
36,feature_6,6546,655,9.993893,51.76
12,feature_20,6541,643,10.172628,47.90
27,feature_34,6536,650,10.055385,61.08
3,feature_12,6534,659,9.915023,54.48
2,feature_11,6533,643,10.160187,54.74
11,feature_2,6525,642,10.163551,62.46
31,feature_38,6478,643,10.074650,55.37
18,feature_26,6470,649,9.969183,64.25

4. LEAST USED FEATURES
----------------------------------------------------------------------

,feature_name,total_usage_count,usage_records,avg_usage_count,error_rate_pct
15,feature_23,5601,563,9.948490,54.35
35,feature_5,5759,577,9.980936,54.77
28,feature_35,5816,587,9.908007,53.32
9,feature_18,5850,588,9.948980,62.76
5,feature_14,5880,600,9.800000,51.17
10,feature_19,5900,589,10.016978,59.76
22,feature_3,5917,598,9.894649,57.69
13,feature_21,5950,591,10.067682,59.05
38,feature_8,6030,596,10.117450,47.65
17,feature_25,6091,615,9.904065,55.93

5. BETA FEATURE ADOPTION
----------------------------------------------------------------------

,is_beta_feature,usage_records,unique_subscriptions,total_usage_count,avg_usage_count,total_errors,error_rate_pct
0,False,22456,4946,224939,10.016877,12691,56.51
1,True,2544,2023,25586,10.057390,1416,55.66

✓ Product and feature usage analysis completed.

In [36]:

print("=" * 70)
print("ACTUAL CUSTOMER ANALYTICS COLUMNS")
print("=" * 70)

for i, col in enumerate(customer_analytics.columns, start=1):
    print(f"{i:02d}. {col}")

======================================================================
ACTUAL CUSTOMER ANALYTICS COLUMNS
======================================================================
01. account_id
02. account_name
03. industry
04. country
05. signup_date
06. referral_source
07. plan_tier
08. seats
09. is_trial
10. churn_flag
11. seats_sum
12. seats_mean
13. seats_min
14. seats_max
15. mrr_amount_sum
16. mrr_amount_mean
17. mrr_amount_min
18. mrr_amount_max
19. arr_amount_sum
20. arr_amount_mean
21. arr_amount_min
22. arr_amount_max
23. subscription_count
24. usage_usage_count_sum
25. usage_usage_count_mean
26. usage_usage_count_max
27. usage_usage_duration_secs_sum
28. usage_usage_duration_secs_mean
29. usage_usage_duration_secs_max
30. usage_error_count_sum
31. usage_error_count_mean
32. usage_error_count_max
33. usage_records
34. distinct_features_used
35. active_usage_days
36. beta_feature_usage_count
37. support_ticket_count
38. avg_resolution_time_hours
39. max_resolution_time_hours
40. avg_first_response_minutes
41. avg_satisfaction_score
42. total_escalations
43. support_high_tickets
44. support_low_tickets
45. support_medium_tickets
46. support_urgent_tickets
47. churn_event_count
48. reactivation_count
49. preceding_upgrade_count
50. preceding_downgrade_count
51. historical_churn_flag

In [37]:


print("=" * 70)
print("PRODUCT USAGE VS CHURN ANALYSIS")
print("=" * 70)

# 1. Churned vs non-churned customers
print("\n1. CHURNED VS NON-CHURNED CUSTOMERS")
print("-" * 70)

usage_churn_analysis = (
    customer_analytics
    .groupby("historical_churn_flag")
    .agg(
        customers=("account_id", "nunique"),
        avg_usage_records=("usage_records", "mean"),
        median_usage_records=("usage_records", "median"),
        avg_distinct_features=("distinct_features_used", "mean"),
        avg_active_usage_days=("active_usage_days", "mean"),
        avg_usage_count=("usage_usage_count_sum", "mean"),
        avg_usage_duration_secs=("usage_usage_duration_secs_sum", "mean"),
        avg_usage_errors=("usage_error_count_sum", "mean"),
        avg_support_tickets=("support_ticket_count", "mean"),
        avg_satisfaction=("avg_satisfaction_score", "mean")
    )
    .reset_index()
)

usage_churn_analysis["customer_status"] = (
    usage_churn_analysis["historical_churn_flag"]
    .map({
        0: "Non-Churned",
        1: "Churned"
    })
)

display(
    usage_churn_analysis[
        [
            "customer_status",
            "customers",
            "avg_usage_records",
            "median_usage_records",
            "avg_distinct_features",
            "avg_active_usage_days",
            "avg_usage_count",
            "avg_usage_duration_secs",
            "avg_usage_errors",
            "avg_support_tickets",
            "avg_satisfaction"
        ]
    ]
)


# 2. Customer engagement bands
print("\n2. CUSTOMER ENGAGEMENT BANDS")
print("-" * 70)

customer_analytics["engagement_band"] = pd.qcut(
    customer_analytics["usage_records"],
    q=4,
    labels=[
        "Low Engagement",
        "Medium-Low Engagement",
        "Medium-High Engagement",
        "High Engagement"
    ],
    duplicates="drop"
)

engagement_churn = (
    customer_analytics
    .groupby("engagement_band", observed=False)
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_usage_records=("usage_records", "mean"),
        avg_distinct_features=("distinct_features_used", "mean"),
        avg_support_tickets=("support_ticket_count", "mean")
    )
    .reset_index()
)

engagement_churn["churn_rate_pct"] = (
    engagement_churn["churned_customers"]
    / engagement_churn["customers"]
    * 100
).round(2)

display(engagement_churn)


# 3. Feature adoption breadth vs churn
print("\n3. FEATURE ADOPTION BREADTH VS CHURN")
print("-" * 70)

feature_adoption_churn = (
    customer_analytics
    .groupby("distinct_features_used")
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum")
    )
    .reset_index()
)

feature_adoption_churn["churn_rate_pct"] = (
    feature_adoption_churn["churned_customers"]
    / feature_adoption_churn["customers"]
    * 100
).round(2)

display(feature_adoption_churn)

print("\n✓ Usage vs churn analysis completed.")

======================================================================
PRODUCT USAGE VS CHURN ANALYSIS
======================================================================

1. CHURNED VS NON-CHURNED CUSTOMERS
----------------------------------------------------------------------

,customer_status,customers,avg_usage_records,median_usage_records,avg_distinct_features,avg_active_usage_days,avg_usage_count,avg_usage_duration_secs,avg_usage_errors,avg_support_tickets,avg_satisfaction
0,Non-Churned,148,49.391892,49.0,27.270270,47.689189,495.378378,149885.236486,27.790541,4.087838,3.648375
1,Churned,352,50.255682,50.0,27.761364,48.446023,503.434659,153045.616477,28.392045,3.963068,3.714035

2. CUSTOMER ENGAGEMENT BANDS
----------------------------------------------------------------------

,engagement_band,customers,churned_customers,avg_usage_records,avg_distinct_features,avg_support_tickets,churn_rate_pct
0,Low Engagement,134,93,28.895522,20.425373,4.007463,69.40
1,Medium-Low Engagement,127,89,44.905512,27.267717,4.086614,70.08
2,Medium-High Engagement,123,84,56.780488,30.268293,4.130081,68.29
3,High Engagement,116,86,72.767241,33.491379,3.758621,74.14

3. FEATURE ADOPTION BREADTH VS CHURN
----------------------------------------------------------------------

    distinct_features_used  customers  churned_customers  churn_rate_pct
0                        9          1                  1          100.00
1                       12          3                  2           66.67
2                       13          3                  1           33.33
3                       14          6                  4           66.67
4                       15          6                  5           83.33
5                       16          9                  7           77.78
6                       17          8                  7           87.50
7                       18          6                  4           66.67
8                       19         11                  9           81.82
9                       20         12                  9           75.00
10                      21          8                  4           50.00
11                      22         14                  9           64.29
12                      23         18                 11           61.11
13                      24         22                 11           50.00
14                      25         22                 16           72.73
15                      26         27                 19           70.37
16                      27         36                 24           66.67
17                      28         40                 29           72.50
18                      29         43                 30           69.77
19                      30         27                 15           55.56
20                      31         39                 32           82.05
21                      32         48                 33           68.75
22                      33         30                 23           76.67
23                      34         26                 20           76.92
24                      35         10                  8           80.00
25                      36          9                  8           88.89
26                      37          9                  7           77.78
27                      38          6                  3           50.00
28                      40          1                  1          100.00

✓ Usage vs churn analysis completed.

In [38]:


print("=" * 70)
print("SUPPORT EXPERIENCE VS CHURN ANALYSIS")
print("=" * 70)

# 1. Churned vs non-churned customers
print("\n1. SUPPORT METRICS — CHURNED VS NON-CHURNED")
print("-" * 70)

support_churn_analysis = (
    customer_analytics
    .groupby("historical_churn_flag")
    .agg(
        customers=("account_id", "nunique"),
        avg_tickets=("support_ticket_count", "mean"),
        median_tickets=("support_ticket_count", "median"),
        avg_resolution_hours=("avg_resolution_time_hours", "mean"),
        avg_first_response_minutes=("avg_first_response_minutes", "mean"),
        avg_satisfaction=("avg_satisfaction_score", "mean"),
        avg_escalations=("total_escalations", "mean"),
        avg_high_priority_tickets=("support_high_tickets", "mean"),
        avg_urgent_tickets=("support_urgent_tickets", "mean")
    )
    .reset_index()
)

support_churn_analysis["customer_status"] = (
    support_churn_analysis["historical_churn_flag"]
    .map({
        0: "Non-Churned",
        1: "Churned"
    })
)

display(
    support_churn_analysis[
        [
            "customer_status",
            "customers",
            "avg_tickets",
            "median_tickets",
            "avg_resolution_hours",
            "avg_first_response_minutes",
            "avg_satisfaction",
            "avg_escalations",
            "avg_high_priority_tickets",
            "avg_urgent_tickets"
        ]
    ]
)


# 2. Support ticket volume bands
print("\n2. SUPPORT TICKET VOLUME VS CHURN")
print("-" * 70)

customer_analytics["support_volume_band"] = pd.cut(
    customer_analytics["support_ticket_count"],
    bins=[-1, 0, 2, 5, float("inf")],
    labels=[
        "No Tickets",
        "1-2 Tickets",
        "3-5 Tickets",
        "6+ Tickets"
    ]
)

support_volume_churn = (
    customer_analytics
    .groupby("support_volume_band", observed=False)
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_satisfaction=("avg_satisfaction_score", "mean"),
        avg_resolution_hours=("avg_resolution_time_hours", "mean"),
        avg_escalations=("total_escalations", "mean")
    )
    .reset_index()
)

support_volume_churn["churn_rate_pct"] = (
    support_volume_churn["churned_customers"]
    / support_volume_churn["customers"]
    * 100
).round(2)

display(support_volume_churn)


# 3. Satisfaction bands
print("\n3. CUSTOMER SATISFACTION VS CHURN")
print("-" * 70)

customer_analytics["satisfaction_band"] = pd.cut(
    customer_analytics["avg_satisfaction_score"],
    bins=[-0.01, 2, 3, 4, 5],
    labels=[
        "Low Satisfaction",
        "Moderate Satisfaction",
        "Good Satisfaction",
        "High Satisfaction"
    ]
)

satisfaction_churn = (
    customer_analytics
    .groupby("satisfaction_band", observed=False)
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_tickets=("support_ticket_count", "mean"),
        avg_resolution_hours=("avg_resolution_time_hours", "mean")
    )
    .reset_index()
)

satisfaction_churn["churn_rate_pct"] = (
    satisfaction_churn["churned_customers"]
    / satisfaction_churn["customers"]
    * 100
).round(2)

display(satisfaction_churn)

print("\n✓ Support vs churn analysis completed.")

======================================================================
SUPPORT EXPERIENCE VS CHURN ANALYSIS
======================================================================

1. SUPPORT METRICS — CHURNED VS NON-CHURNED
----------------------------------------------------------------------

,customer_status,customers,avg_tickets,median_tickets,avg_resolution_hours,avg_first_response_minutes,avg_satisfaction,avg_escalations,avg_high_priority_tickets,avg_urgent_tickets
0,Non-Churned,148,4.087838,4.0,35.512028,86.256336,3.648375,0.162162,0.952703,1.155405
1,Churned,352,3.963068,4.0,35.720367,87.515990,3.714035,0.201705,1.048295,0.974432

2. SUPPORT TICKET VOLUME VS CHURN
----------------------------------------------------------------------

,support_volume_band,customers,churned_customers,avg_satisfaction,avg_resolution_hours,avg_escalations,churn_rate_pct
0,No Tickets,8,5,0.000000,0.000000,0.000000,62.50
1,1-2 Tickets,104,73,3.221154,38.923077,0.086538,70.19
2,3-5 Tickets,292,213,3.877454,35.452568,0.188356,72.95
3,6+ Tickets,96,61,3.959201,35.720828,0.322917,63.54

3. CUSTOMER SATISFACTION VS CHURN
----------------------------------------------------------------------

,satisfaction_band,customers,churned_customers,avg_tickets,avg_resolution_hours,churn_rate_pct
0,Low Satisfaction,34,22,1.676471,32.546569,64.71
1,Moderate Satisfaction,61,47,3.032787,35.643443,77.05
2,Good Satisfaction,251,171,4.274900,36.026034,68.13
3,High Satisfaction,154,112,4.448052,35.753128,72.73

✓ Support vs churn analysis completed.

In [39]:


print("=" * 70)
print("REVENUE & SUBSCRIPTION BEHAVIOR VS CHURN")
print("=" * 70)

# 1. Revenue metrics — churned vs non-churned
print("\n1. REVENUE PROFILE — CHURNED VS NON-CHURNED")
print("-" * 70)

revenue_churn_analysis = (
    customer_analytics
    .groupby("historical_churn_flag")
    .agg(
        customers=("account_id", "nunique"),
        avg_mrr=("mrr_amount_sum", "mean"),
        median_mrr=("mrr_amount_sum", "median"),
        total_mrr=("mrr_amount_sum", "sum"),
        avg_arr=("arr_amount_sum", "mean"),
        median_arr=("arr_amount_sum", "median"),
        total_arr=("arr_amount_sum", "sum"),
        avg_subscriptions=("subscription_count", "mean")
    )
    .reset_index()
)

revenue_churn_analysis["customer_status"] = (
    revenue_churn_analysis["historical_churn_flag"]
    .map({
        0: "Non-Churned",
        1: "Churned"
    })
)

display(
    revenue_churn_analysis[
        [
            "customer_status",
            "customers",
            "avg_mrr",
            "median_mrr",
            "total_mrr",
            "avg_arr",
            "median_arr",
            "total_arr",
            "avg_subscriptions"
        ]
    ]
)


# 2. MRR bands
print("\n2. MRR BANDS VS CHURN")
print("-" * 70)

customer_analytics["mrr_band"] = pd.qcut(
    customer_analytics["mrr_amount_sum"],
    q=4,
    labels=[
        "Low MRR",
        "Medium-Low MRR",
        "Medium-High MRR",
        "High MRR"
    ],
    duplicates="drop"
)

mrr_churn = (
    customer_analytics
    .groupby("mrr_band", observed=False)
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_mrr=("mrr_amount_sum", "mean"),
        avg_arr=("arr_amount_sum", "mean"),
        avg_usage=("usage_records", "mean")
    )
    .reset_index()
)

mrr_churn["churn_rate_pct"] = (
    mrr_churn["churned_customers"]
    / mrr_churn["customers"]
    * 100
).round(2)

display(mrr_churn)


# 3. Subscription count vs churn
print("\n3. SUBSCRIPTION COUNT VS CHURN")
print("-" * 70)

subscription_churn = (
    customer_analytics
    .groupby("subscription_count")
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_mrr=("mrr_amount_sum", "mean"),
        avg_usage=("usage_records", "mean")
    )
    .reset_index()
)

subscription_churn["churn_rate_pct"] = (
    subscription_churn["churned_customers"]
    / subscription_churn["customers"]
    * 100
).round(2)

display(subscription_churn)


# 4. Plan tier vs churn
print("\n4. PLAN TIER VS CHURN")
print("-" * 70)

plan_churn = (
    customer_analytics
    .groupby("plan_tier", dropna=False)
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_mrr=("mrr_amount_sum", "mean"),
        avg_arr=("arr_amount_sum", "mean"),
        avg_usage=("usage_records", "mean"),
        avg_support_tickets=("support_ticket_count", "mean")
    )
    .reset_index()
)

plan_churn["churn_rate_pct"] = (
    plan_churn["churned_customers"]
    / plan_churn["customers"]
    * 100
).round(2)

display(plan_churn)

print("\n✓ Revenue and subscription vs churn analysis completed.")

======================================================================
REVENUE & SUBSCRIPTION BEHAVIOR VS CHURN
======================================================================

1. REVENUE PROFILE — CHURNED VS NON-CHURNED
----------------------------------------------------------------------

,customer_status,customers,avg_mrr,median_mrr,total_mrr,avg_arr,median_arr,total_arr,avg_subscriptions
0,Non-Churned,148,22620.033784,18008.0,3347765,271440.405405,216096.0,40173180,9.945946
1,Churned,352,22701.653409,19047.0,7990982,272419.840909,228564.0,95891784,10.022727

2. MRR BANDS VS CHURN
----------------------------------------------------------------------

,mrr_band,customers,churned_customers,avg_mrr,avg_arr,avg_usage,churn_rate_pct
0,Low MRR,125,87,7310.072,87720.864,37.592,69.6
1,Medium-Low MRR,125,85,15095.904,181150.848,47.976,68.0
2,Medium-High MRR,125,84,23455.912,281470.944,54.304,67.2
3,High MRR,125,96,44848.088,538177.056,60.128,76.8

3. SUBSCRIPTION COUNT VS CHURN
----------------------------------------------------------------------

,subscription_count,customers,churned_customers,avg_mrr,avg_usage,churn_rate_pct
0,2,1,1,190.000000,10.000000,100.00
1,3,5,3,4030.200000,17.000000,60.00
2,4,10,8,5243.200000,19.900000,80.00
3,5,24,21,11673.000000,25.166667,87.50
4,6,31,17,11256.580645,27.225806,54.84
5,7,57,44,18646.421053,36.842105,77.19
6,8,47,35,19660.723404,40.361702,74.47
7,9,50,26,19406.500000,45.920000,52.00
8,10,56,37,25107.607143,50.607143,66.07
9,11,54,36,23714.648148,56.129630,66.67
10,12,62,48,27689.290323,60.048387,77.42
11,13,31,22,27462.225806,64.290323,70.97
12,14,18,15,27648.222222,65.000000,83.33
13,15,24,19,37650.000000,76.166667,79.17
14,16,21,14,31777.047619,77.000000,66.67
15,17,3,2,28148.000000,81.666667,66.67
16,18,2,1,82175.000000,80.000000,50.00
17,19,4,3,26895.250000,91.000000,75.00

4. PLAN TIER VS CHURN
----------------------------------------------------------------------

,plan_tier,customers,churned_customers,avg_mrr,avg_arr,avg_usage,avg_support_tickets,churn_rate_pct
0,Basic,168,115,24094.488095,289133.857143,52.684524,3.750000,68.45
1,Enterprise,154,108,21572.441558,258869.298701,48.837662,4.149351,70.13
2,Pro,178,129,22296.162921,267553.955056,48.471910,4.106742,72.47

✓ Revenue and subscription vs churn analysis completed.

In [40]:

print("=" * 70)
print("CUSTOMER SEGMENT & CHURN ANALYSIS")
print("=" * 70)

# Candidate business dimensions
segment_columns = [
    "industry",
    "country",
    "plan_tier",
    "is_trial",
    "referral_source"
]

# Keep only columns that actually exist
segment_columns = [
    col for col in segment_columns
    if col in customer_analytics.columns
]

print("\nDimensions analyzed:")
print(segment_columns)


# Analyze each dimension
for segment_col in segment_columns:

    print("\n" + "=" * 70)
    print(f"{segment_col.upper()} VS CHURN")
    print("=" * 70)

    segment_churn = (
        customer_analytics
        .groupby(segment_col, dropna=False)
        .agg(
            customers=("account_id", "nunique"),
            churned_customers=("historical_churn_flag", "sum"),
            avg_mrr=("mrr_amount_sum", "mean"),
            avg_usage=("usage_records", "mean"),
            avg_support_tickets=("support_ticket_count", "mean")
        )
        .reset_index()
    )

    segment_churn["churn_rate_pct"] = (
        segment_churn["churned_customers"]
        / segment_churn["customers"]
        * 100
    ).round(2)

    # Revenue contribution
    segment_churn["estimated_total_mrr"] = (
        segment_churn["customers"]
        * segment_churn["avg_mrr"]
    ).round(2)

    # Sort by customer count so tiny groups don't dominate the table
    segment_churn = segment_churn.sort_values(
        "customers",
        ascending=False
    )

    display(segment_churn)


# Trial customers specifically
if "is_trial" in customer_analytics.columns:

    print("\n" + "=" * 70)
    print("TRIAL VS NON-TRIAL CUSTOMER ANALYSIS")
    print("=" * 70)

    trial_analysis = (
        customer_analytics
        .groupby("is_trial", dropna=False)
        .agg(
            customers=("account_id", "nunique"),
            churned_customers=("historical_churn_flag", "sum"),
            avg_mrr=("mrr_amount_sum", "mean"),
            avg_usage=("usage_records", "mean"),
            avg_features=("distinct_features_used", "mean")
        )
        .reset_index()
    )

    trial_analysis["churn_rate_pct"] = (
        trial_analysis["churned_customers"]
        / trial_analysis["customers"]
        * 100
    ).round(2)

    display(trial_analysis)


print("\n✓ Customer segment vs churn analysis completed.")

======================================================================
CUSTOMER SEGMENT & CHURN ANALYSIS
======================================================================

Dimensions analyzed:
['industry', 'country', 'plan_tier', 'is_trial', 'referral_source']

======================================================================
INDUSTRY VS CHURN
======================================================================

,industry,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct,estimated_total_mrr
1,DevTools,113,83,21271.274336,50.849558,3.761062,73.45,2403654.0
3,FinTech,112,76,23834.785714,49.500000,4.080357,67.86,2669496.0
0,Cybersecurity,100,72,22533.180000,50.250000,3.940000,72.00,2253318.0
4,HealthTech,96,64,20511.583333,48.843750,4.250000,66.67,1969112.0
2,EdTech,79,57,25862.873418,50.582278,4.000000,72.15,2043167.0

======================================================================
COUNTRY VS CHURN
======================================================================

,country,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct,estimated_total_mrr
6,US,291,206,22799.295533,50.872852,4.048110,70.79,6634595.0
5,UK,58,45,21042.603448,49.086207,3.568966,77.59,1220471.0
4,IN,49,33,24373.979592,51.653061,4.387755,67.35,1194325.0
0,AU,32,22,26249.375000,48.968750,3.562500,68.75,839980.0
2,DE,25,14,15280.720000,42.360000,3.840000,56.00,382018.0
1,CA,23,16,20763.565217,48.173913,4.000000,69.57,477562.0
3,FR,22,16,26808.909091,49.272727,4.454545,72.73,589796.0

======================================================================
PLAN_TIER VS CHURN
======================================================================

,plan_tier,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct,estimated_total_mrr
2,Pro,178,129,22296.162921,48.471910,4.106742,72.47,3968717.0
0,Basic,168,115,24094.488095,52.684524,3.750000,68.45,4047874.0
1,Enterprise,154,108,21572.441558,48.837662,4.149351,70.13,3322156.0

======================================================================
IS_TRIAL VS CHURN
======================================================================

,is_trial,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct,estimated_total_mrr
0,False,403,285,22551.151365,49.766749,3.985112,70.72,9088114.0
1,True,97,67,23202.402062,50.969072,4.061856,69.07,2250633.0

======================================================================
REFERRAL_SOURCE VS CHURN
======================================================================

,referral_source,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct,estimated_total_mrr
2,organic,114,85,24550.061404,51.947368,3.842105,74.56,2798707.0
3,other,103,73,23084.737864,49.291262,4.194175,70.87,2377728.0
0,ads,98,59,21904.275510,50.367347,4.275510,60.20,2146619.0
1,event,96,68,20015.104167,48.770833,3.916667,70.83,1921450.0
4,partner,89,67,23530.820225,49.247191,3.764045,75.28,2094243.0

======================================================================
TRIAL VS NON-TRIAL CUSTOMER ANALYSIS
======================================================================

,is_trial,customers,churned_customers,avg_mrr,avg_usage,avg_features,churn_rate_pct
0,False,403,285,22551.151365,49.766749,27.451613,70.72
1,True,97,67,23202.402062,50.969072,28.298969,69.07

✓ Customer segment vs churn analysis completed.

In [41]:


print("=" * 70)
print("CUSTOMER HEALTH SEGMENTATION")
print("=" * 70)

# Create percentile-based scores so different metrics
# can be compared on a common 0-100 scale.

def percentile_score(series):
    return series.rank(pct=True) * 100


# 1. Engagement score
customer_analytics["engagement_score"] = (
    percentile_score(customer_analytics["usage_records"])
    + percentile_score(customer_analytics["distinct_features_used"])
    + percentile_score(customer_analytics["active_usage_days"])
) / 3


# 2. Support experience score
# Higher satisfaction = better
# Lower resolution time = better
# Lower escalation count = better

satisfaction_score = percentile_score(
    customer_analytics["avg_satisfaction_score"].fillna(
        customer_analytics["avg_satisfaction_score"].median()
    )
)

resolution_score = 100 - percentile_score(
    customer_analytics["avg_resolution_time_hours"].fillna(
        customer_analytics["avg_resolution_time_hours"].median()
    )
)

escalation_score = 100 - percentile_score(
    customer_analytics["total_escalations"]
)

customer_analytics["support_health_score"] = (
    satisfaction_score
    + resolution_score
    + escalation_score
) / 3


# 3. Revenue value score
customer_analytics["revenue_value_score"] = percentile_score(
    customer_analytics["mrr_amount_sum"]
)


# 4. Overall customer health score
customer_analytics["customer_health_score"] = (
    customer_analytics["engagement_score"] * 0.50
    + customer_analytics["support_health_score"] * 0.25
    + customer_analytics["revenue_value_score"] * 0.25
).round(2)


# 5. Health segments
customer_analytics["customer_health_segment"] = pd.cut(
    customer_analytics["customer_health_score"],
    bins=[-1, 25, 50, 75, 101],
    labels=[
        "At Risk",
        "Needs Attention",
        "Healthy",
        "Highly Engaged"
    ]
)


# 6. Segment performance
health_analysis = (
    customer_analytics
    .groupby("customer_health_segment", observed=False)
    .agg(
        customers=("account_id", "nunique"),
        churned_customers=("historical_churn_flag", "sum"),
        avg_health_score=("customer_health_score", "mean"),
        avg_mrr=("mrr_amount_sum", "mean"),
        avg_usage=("usage_records", "mean"),
        avg_features=("distinct_features_used", "mean"),
        avg_support_tickets=("support_ticket_count", "mean"),
        avg_satisfaction=("avg_satisfaction_score", "mean")
    )
    .reset_index()
)

health_analysis["churn_rate_pct"] = (
    health_analysis["churned_customers"]
    / health_analysis["customers"]
    * 100
).round(2)

display(health_analysis)


# 7. Customer-level health view
print("\nCUSTOMER HEALTH SAMPLE")
print("-" * 70)

health_columns = [
    "account_id",
    "plan_tier",
    "mrr_amount_sum",
    "usage_records",
    "distinct_features_used",
    "support_ticket_count",
    "avg_satisfaction_score",
    "engagement_score",
    "support_health_score",
    "revenue_value_score",
    "customer_health_score",
    "customer_health_segment",
    "historical_churn_flag"
]

display(
    customer_analytics[health_columns]
    .sort_values("customer_health_score")
    .head(20)
)

print("\n✓ Customer health segmentation completed.")

======================================================================
CUSTOMER HEALTH SEGMENTATION
======================================================================

,customer_health_segment,customers,churned_customers,avg_health_score,avg_mrr,avg_usage,avg_features,avg_support_tickets,avg_satisfaction,churn_rate_pct
0,At Risk,62,42,19.669194,6996.919355,25.516129,18.112903,4.000000,3.203648,67.74
1,Needs Attention,184,127,38.300978,16082.739130,40.804348,25.418478,4.005435,3.594423,69.02
2,Healthy,196,141,61.968265,27832.852041,58.709184,30.698980,4.091837,3.850255,71.94
3,Highly Engaged,58,42,79.666379,42939.224138,75.913793,34.327586,3.672414,4.011207,72.41

CUSTOMER HEALTH SAMPLE
----------------------------------------------------------------------

,account_id,plan_tier,mrr_amount_sum,usage_records,distinct_features_used,support_ticket_count,avg_satisfaction_score,engagement_score,support_health_score,revenue_value_score,customer_health_score,customer_health_segment,historical_churn_flag
201,A-354f12,Pro,8889,15,14,2.0,0.000000,1.366667,22.666667,15.0,10.10,At Risk,1
462,A-f19b24,Pro,2523,12,12,2.0,4.000000,0.466667,38.233333,2.4,10.39,At Risk,0
161,A-856b1e,Basic,6321,23,17,5.0,0.000000,6.600000,20.433333,9.6,10.81,At Risk,0
354,A-b54c01,Enterprise,3393,23,15,5.0,3.000000,5.066667,32.766667,3.6,11.62,At Risk,1
333,A-9a532a,Enterprise,10945,18,16,2.0,0.000000,3.166667,22.433333,21.4,12.54,At Risk,0
208,A-508199,Basic,8436,24,16,3.0,3.000000,6.333333,27.200000,13.4,13.32,At Risk,0
408,A-751bd4,Pro,190,10,9,6.0,4.250000,0.200000,56.433333,0.2,14.26,At Risk,1
227,A-b2af2e,Enterprise,3112,18,14,2.0,4.000000,2.266667,50.366667,3.0,14.48,At Risk,1
351,A-94c3cd,Enterprise,9036,31,18,4.0,3.500000,12.266667,18.700000,15.8,14.76,At Risk,0
152,A-439b2f,Enterprise,1796,20,14,3.0,0.000000,3.266667,51.300000,1.4,14.81,At Risk,1
454,A-0be015,Pro,1178,28,19,7.0,4.200000,10.666667,38.266667,0.8,15.10,At Risk,1
311,A-3d957b,Pro,11852,15,13,3.0,3.000000,1.066667,34.300000,24.8,15.31,At Risk,1
181,A-5b051a,Enterprise,2332,16,14,1.0,3.000000,1.633333,56.666667,2.2,15.53,At Risk,0
156,A-038089,Pro,2104,20,15,6.0,3.666667,3.666667,54.266667,1.8,15.85,At Risk,1
381,A-0a62f5,Pro,4861,25,20,2.0,0.000000,9.533333,39.400000,7.2,16.42,At Risk,1
182,A-296d7c,Enterprise,1989,33,21,5.0,3.750000,15.600000,35.700000,1.6,17.12,At Risk,1
246,A-331424,Basic,6776,20,17,2.0,0.000000,5.066667,48.900000,10.2,17.31,At Risk,1
494,A-b9f5b1,Pro,7072,30,21,6.0,3.333333,13.900000,30.933333,10.6,17.33,At Risk,1
135,A-117171,Basic,12015,21,15,6.0,3.666667,4.666667,34.633333,25.8,17.44,At Risk,1
438,A-558c72,Basic,9171,30,19,4.0,4.500000,12.066667,31.666667,16.0,17.95,At Risk,1

✓ Customer health segmentation completed.

In [42]:


print("=" * 70)
print("CHURN DRIVER ASSOCIATION ANALYSIS")
print("=" * 70)

# Numeric features available for analysis
numeric_cols = customer_analytics.select_dtypes(
    include="number"
).columns.tolist()

# Remove identifiers and churn-derived variables
excluded_cols = [
    "historical_churn_flag",
    "churn_flag",
    "churn_event_count",
    "reactivation_count",
    "preceding_upgrade_count",
    "preceding_downgrade_count",
    "account_id"
]

analysis_features = [
    col for col in numeric_cols
    if col not in excluded_cols
]

# Calculate correlation with historical churn
churn_correlation = (
    customer_analytics[analysis_features + ["historical_churn_flag"]]
    .corr(numeric_only=True)["historical_churn_flag"]
    .drop("historical_churn_flag")
    .dropna()
    .sort_values()
)

correlation_table = pd.DataFrame({
    "feature": churn_correlation.index,
    "correlation_with_churn": churn_correlation.values
})

correlation_table["absolute_correlation"] = (
    correlation_table["correlation_with_churn"]
    .abs()
)

correlation_table = correlation_table.sort_values(
    "absolute_correlation",
    ascending=False
)

print("\nTop features associated with historical churn:")
display(correlation_table.head(20))


# 1. Strongest positive associations
print("\n" + "=" * 70)
print("STRONGEST POSITIVE ASSOCIATIONS")
print("=" * 70)

positive = correlation_table[
    correlation_table["correlation_with_churn"] > 0
].head(10)

display(positive)


# 2. Strongest negative associations
print("\n" + "=" * 70)
print("STRONGEST NEGATIVE ASSOCIATIONS")
print("=" * 70)

negative = correlation_table[
    correlation_table["correlation_with_churn"] < 0
].sort_values(
    "correlation_with_churn"
).head(10)

display(negative)


# 3. Save shortlist for later ML work
candidate_features = correlation_table.head(15)["feature"].tolist()

print("\nCandidate analytical features for further investigation:")
print(candidate_features)

print("\n✓ Churn driver association analysis completed.")
print("⚠ Correlation shows association, not causation.")

======================================================================
CHURN DRIVER ASSOCIATION ANALYSIS
======================================================================

Top features associated with historical churn:

,feature,correlation_with_churn,absolute_correlation
0,support_urgent_tickets,-0.079671,0.079671
1,usage_usage_count_max,-0.060967,0.060967
40,usage_error_count_max,0.059336,0.059336
39,seats_max,0.051181,0.051181
38,support_high_tickets,0.044922,0.044922
37,total_escalations,0.043286,0.043286
36,arr_amount_min,0.040518,0.040518
35,mrr_amount_min,0.040518,0.040518
34,distinct_features_used,0.039657,0.039657
33,revenue_value_score,0.039536,0.039536
32,customer_health_score,0.037860,0.037860
31,engagement_score,0.032898,0.032898
2,support_ticket_count,-0.030119,0.030119
3,beta_feature_usage_count,-0.028842,0.028842
30,usage_usage_duration_secs_sum,0.027479,0.027479
29,avg_satisfaction_score,0.026303,0.026303
28,usage_records,0.022963,0.022963
27,usage_error_count_sum,0.022713,0.022713
26,max_resolution_time_hours,0.022215,0.022215
25,active_usage_days,0.021351,0.021351

======================================================================
STRONGEST POSITIVE ASSOCIATIONS
======================================================================

                   feature  correlation_with_churn  absolute_correlation
40   usage_error_count_max                0.059336              0.059336
39               seats_max                0.051181              0.051181
38    support_high_tickets                0.044922              0.044922
37       total_escalations                0.043286              0.043286
36          arr_amount_min                0.040518              0.040518
35          mrr_amount_min                0.040518              0.040518
34  distinct_features_used                0.039657              0.039657
33     revenue_value_score                0.039536              0.039536
32   customer_health_score                0.037860              0.037860
31        engagement_score                0.032898              0.032898

======================================================================
STRONGEST NEGATIVE ASSOCIATIONS
======================================================================

                         feature  correlation_with_churn  absolute_correlation
0         support_urgent_tickets               -0.079671              0.079671
1          usage_usage_count_max               -0.060967              0.060967
2           support_ticket_count               -0.030119              0.030119
3       beta_feature_usage_count               -0.028842              0.028842
4            support_low_tickets               -0.019599              0.019599
5         usage_error_count_mean               -0.016818              0.016818
6                      seats_sum               -0.014327              0.014327
7           support_health_score               -0.007661              0.007661
8  usage_usage_duration_secs_max               -0.005872              0.005872

Candidate analytical features for further investigation:
['support_urgent_tickets', 'usage_usage_count_max', 'usage_error_count_max', 'seats_max', 'support_high_tickets', 'total_escalations', 'arr_amount_min', 'mrr_amount_min', 'distinct_features_used', 'revenue_value_score', 'customer_health_score', 'engagement_score', 'support_ticket_count', 'beta_feature_usage_count', 'usage_usage_duration_secs_sum']

✓ Churn driver association analysis completed.
⚠ Correlation shows association, not causation.

In [43]:


print("=" * 70)
print("KEY CHURN DRIVER SEGMENTATION")
print("=" * 70)

# Create interpretable bands for the strongest business variables

# 1. Support ticket volume
customer_analytics["ticket_band"] = pd.cut(
    customer_analytics["support_ticket_count"],
    bins=[-1, 0, 2, 5, float("inf")],
    labels=[
        "No Tickets",
        "1-2 Tickets",
        "3-5 Tickets",
        "6+ Tickets"
    ]
)

# 2. Feature adoption
customer_analytics["feature_adoption_band"] = pd.cut(
    customer_analytics["distinct_features_used"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=[
        "0-2 Features",
        "3-5 Features",
        "6-10 Features",
        "11+ Features"
    ]
)

# 3. Product usage
customer_analytics["usage_band"] = pd.qcut(
    customer_analytics["usage_usage_count_sum"],
    q=4,
    labels=[
        "Low Usage",
        "Medium-Low Usage",
        "Medium-High Usage",
        "High Usage"
    ],
    duplicates="drop"
)

# 4. Seats
customer_analytics["seat_band"] = pd.qcut(
    customer_analytics["seats_sum"],
    q=4,
    labels=[
        "Small",
        "Medium-Low",
        "Medium-High",
        "Large"
    ],
    duplicates="drop"
)


# Helper function
def churn_summary(data, group_col):

    result = (
        data
        .groupby(group_col, observed=False)
        .agg(
            customers=("account_id", "nunique"),
            churned_customers=("historical_churn_flag", "sum"),
            avg_mrr=("mrr_amount_sum", "mean"),
            avg_usage=("usage_usage_count_sum", "mean"),
            avg_support_tickets=("support_ticket_count", "mean")
        )
        .reset_index()
    )

    result["churn_rate_pct"] = (
        result["churned_customers"]
        / result["customers"]
        * 100
    ).round(2)

    return result


# Analyze each driver
driver_bands = [
    "ticket_band",
    "feature_adoption_band",
    "usage_band",
    "seat_band"
]

for driver in driver_bands:

    print("\n" + "=" * 70)
    print(driver.upper())
    print("=" * 70)

    display(
        churn_summary(
            customer_analytics,
            driver
        )
    )


print("\n✓ Key churn driver segmentation completed.")

======================================================================
KEY CHURN DRIVER SEGMENTATION
======================================================================

======================================================================
TICKET_BAND
======================================================================

,ticket_band,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct
0,No Tickets,8,5,15699.500000,480.625000,0.000000,62.50
1,1-2 Tickets,104,73,21456.201923,495.798077,1.711538,70.19
2,3-5 Tickets,292,213,24491.626712,513.383562,3.982877,72.95
3,6+ Tickets,96,61,19064.072917,470.927083,6.864583,63.54

======================================================================
FEATURE_ADOPTION_BAND
======================================================================

,feature_adoption_band,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct
0,0-2 Features,0,0,NaN,NaN,NaN,NaN
1,3-5 Features,0,0,NaN,NaN,NaN,NaN
2,6-10 Features,1,1,190.000000,92.000000,6.000000,100.00
3,11+ Features,499,351,22722.559118,501.869739,3.995992,70.34

======================================================================
USAGE_BAND
======================================================================

,usage_band,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct
0,Low Usage,126,86,13676.420635,282.190476,4.031746,68.25
1,Medium-Low Usage,124,89,21949.604839,439.862903,4.016129,71.77
2,Medium-High Usage,125,82,23830.688000,559.168000,4.264000,65.60
3,High Usage,125,95,31319.448000,724.240000,3.688000,76.00

======================================================================
SEAT_BAND
======================================================================

,seat_band,customers,churned_customers,avg_mrr,avg_usage,avg_support_tickets,churn_rate_pct
0,Small,126,84,9940.825397,354.126984,3.960317,66.67
1,Medium-Low,125,84,16206.064000,476.016000,3.960000,67.20
2,Medium-High,125,100,23514.832000,570.744000,4.104000,80.00
3,Large,124,84,41299.120968,605.322581,3.975806,67.74

✓ Key churn driver segmentation completed.

In [44]:


print("=" * 70)
print("CREATING EXCEL-READY ANALYTICAL DATASET")
print("=" * 70)

# Start with the customer-level analytical dataset
excel_customer_data = customer_analytics.copy()

# Remove temporary analysis columns that are not part of the
# core analytical dataset
temporary_columns = [
    "engagement_band",
    "support_volume_band",
    "satisfaction_band",
    "mrr_band",
    "customer_health_segment",
    "ticket_band",
    "feature_adoption_band",
    "usage_band",
    "seat_band"
]

excel_customer_data = excel_customer_data.drop(
    columns=[
        col for col in temporary_columns
        if col in excel_customer_data.columns
    ],
    errors="ignore"
)

# Remove duplicate column names if any
excel_customer_data = excel_customer_data.loc[
    :, ~excel_customer_data.columns.duplicated()
]

# Sort by account ID
excel_customer_data = excel_customer_data.sort_values(
    "account_id"
).reset_index(drop=True)

# Final validation
print("\nDataset shape:", excel_customer_data.shape)
print("Unique accounts:", excel_customer_data["account_id"].nunique())
print("One row per account:", excel_customer_data["account_id"].is_unique)
print("Duplicate rows:", excel_customer_data.duplicated().sum())

print("\nColumns:")
print(excel_customer_data.columns.tolist())

print("\nFirst 5 rows:")
display(excel_customer_data.head())

print("\n✓ Excel-ready customer dataset created.")

======================================================================
CREATING EXCEL-READY ANALYTICAL DATASET
======================================================================

Dataset shape: (500, 55)
Unique accounts: 500
One row per account: True
Duplicate rows: 0

Columns:
['account_id', 'account_name', 'industry', 'country', 'signup_date', 'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag', 'seats_sum', 'seats_mean', 'seats_min', 'seats_max', 'mrr_amount_sum', 'mrr_amount_mean', 'mrr_amount_min', 'mrr_amount_max', 'arr_amount_sum', 'arr_amount_mean', 'arr_amount_min', 'arr_amount_max', 'subscription_count', 'usage_usage_count_sum', 'usage_usage_count_mean', 'usage_usage_count_max', 'usage_usage_duration_secs_sum', 'usage_usage_duration_secs_mean', 'usage_usage_duration_secs_max', 'usage_error_count_sum', 'usage_error_count_mean', 'usage_error_count_max', 'usage_records', 'distinct_features_used', 'active_usage_days', 'beta_feature_usage_count', 'support_ticket_count', 'avg_resolution_time_hours', 'max_resolution_time_hours', 'avg_first_response_minutes', 'avg_satisfaction_score', 'total_escalations', 'support_high_tickets', 'support_low_tickets', 'support_medium_tickets', 'support_urgent_tickets', 'churn_event_count', 'reactivation_count', 'preceding_upgrade_count', 'preceding_downgrade_count', 'historical_churn_flag', 'engagement_score', 'support_health_score', 'revenue_value_score', 'customer_health_score']

First 5 rows:

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,seats_sum,seats_mean,seats_min,seats_max,mrr_amount_sum,mrr_amount_mean,mrr_amount_min,mrr_amount_max,arr_amount_sum,arr_amount_mean,arr_amount_min,arr_amount_max,subscription_count,usage_usage_count_sum,usage_usage_count_mean,usage_usage_count_max,usage_usage_duration_secs_sum,usage_usage_duration_secs_mean,usage_usage_duration_secs_max,usage_error_count_sum,usage_error_count_mean,usage_error_count_max,usage_records,distinct_features_used,active_usage_days,beta_feature_usage_count,support_ticket_count,avg_resolution_time_hours,max_resolution_time_hours,avg_first_response_minutes,avg_satisfaction_score,total_escalations,support_high_tickets,support_low_tickets,support_medium_tickets,support_urgent_tickets,churn_event_count,reactivation_count,preceding_upgrade_count,preceding_downgrade_count,historical_churn_flag,engagement_score,support_health_score,revenue_value_score,customer_health_score
0,A-00bed1,Company_306,Cybersecurity,US,2023-11-14,ads,Basic,28,True,False,342,34.200000,28,61,33506,3350.600000,0,9751,402072,40207.200000,0,117012,10,514,10.078431,16,143734,2818.313725,7553,27,0.529412,4,51,32,49,2,4.0,31.750000,66.0,106.25,4.0,0.0,2.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1,60.833333,58.866667,82.6,65.78
1,A-00cac8,Company_26,HealthTech,AU,2023-09-15,organic,Enterprise,8,True,False,138,15.333333,8,39,14121,1569.000000,0,7761,169452,18828.000000,0,93132,9,602,10.379310,17,171366,2954.586207,8190,31,0.534483,3,58,30,57,7,2.0,33.000000,65.0,120.50,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0,66.300000,40.233333,34.2,51.76
2,A-0158bb,Company_461,FinTech,DE,2024-05-22,partner,Basic,5,False,False,155,25.833333,9,45,4070,678.333333,0,2205,48840,8140.000000,0,26460,6,364,10.111111,16,122051,3390.305556,8550,22,0.611111,4,36,19,35,3,1.0,32.000000,32.0,50.00,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,17.566667,44.633333,5.4,21.29
3,A-016043,Company_405,EdTech,CA,2024-07-31,organic,Basic,4,True,False,225,20.454545,6,59,16516,1501.454545,0,4776,198192,18017.454545,0,57312,11,490,10.425532,18,132075,2810.106383,8944,21,0.446809,5,47,26,46,3,3.0,30.333333,59.0,78.00,4.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1,40.433333,60.866667,42.2,45.98
4,A-019782,Company_142,DevTools,FR,2023-04-19,event,Enterprise,11,False,False,123,13.666667,11,17,8353,928.111111,0,3184,100236,11137.333333,0,38208,9,562,10.218182,21,160848,2924.509091,7761,30,0.545455,4,55,28,55,3,2.0,10.000000,10.0,107.00,3.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0,57.600000,56.400000,13.2,46.20

✓ Excel-ready customer dataset created.

In [46]:


from pathlib import Path

# Output location
OUTPUT_DIR = Path("../outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

excel_file = OUTPUT_DIR / "SaaS_Product_Analytics.xlsx"

# Export the main customer-level analytical dataset
with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
    excel_customer_data.to_excel(
        writer,
        sheet_name="Customer Analytics",
        index=False
    )

print("=" * 70)
print("EXCEL EXPORT COMPLETE")
print("=" * 70)

print("\nFile created:")
print(excel_file.resolve())

print("\nRows:", len(excel_customer_data))
print("Columns:", len(excel_customer_data.columns))

print("\nSheet created:")
print("1. Customer Analytics")

print("\n✓ Open the generated .xlsx file in Excel.")

======================================================================
EXCEL EXPORT COMPLETE
======================================================================

File created:
C:\Users\harsh\OneDrive\Desktop\Saas project\outputs\SaaS_Product_Analytics.xlsx

Rows: 500
Columns: 55

Sheet created:
1. Customer Analytics

✓ Open the generated .xlsx file in Excel.

In [47]:


print("=" * 70)
print("CHURN DATA VALIDATION")
print("=" * 70)

# 1. Total churn event records
total_churn_events = len(churn_events)

# 2. Unique accounts appearing in churn events
unique_churned_accounts = churn_events["account_id"].nunique()

# 3. Total accounts
total_accounts = accounts["account_id"].nunique()

# 4. Historical churn rate
historical_churn_rate = unique_churned_accounts / total_accounts

# 5. Distribution of churn events per affected account
churn_events_per_account = (
    churn_events
    .groupby("account_id")
    .size()
)

print(f"\nTotal churn event records       : {total_churn_events:,}")
print(f"Unique accounts with churn     : {unique_churned_accounts:,}")
print(f"Total accounts                 : {total_accounts:,}")
print(f"Historical churn rate          : {historical_churn_rate:.2%}")

print("\nChurn events per affected account:")
print(churn_events_per_account.describe())

print("\nNumber of accounts by churn-event count:")
print(churn_events_per_account.value_counts().sort_index())

print("\n✓ Churn validation complete.")

======================================================================
CHURN DATA VALIDATION
======================================================================

Total churn event records       : 600
Unique accounts with churn     : 352
Total accounts                 : 500
Historical churn rate          : 70.40%

Churn events per affected account:
count    352.000000
mean       1.704545
std        0.846095
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        5.000000
dtype: float64

Number of accounts by churn-event count:
1    177
2    116
3     47
4     10
5      2
Name: count, dtype: int64

✓ Churn validation complete.